### ISSUE TITLE
Error while building.

### ISSUE THREAD

**Issue by Akshay-Prakash** [Framstag/libosmscout#1010]
Cloned the repo in linux and ran the following set of commands to build libosmscout.
```
$ mkdir build
$ cd build
$ cmake -DCMAKE_BUILD_TYPE=DEBUG -DOSMSCOUT_BUILD_BINDING_JAVA=OFF ..
$ make
```

Got the following error:

```
Scanning dependencies of target AsyncProcessing
[ 89%] Building CXX object Tests/CMakeFiles/AsyncProcessing.dir/src/AsyncProcessing.cpp.o
Tests/CMakeFiles/AsyncProcessing.dir/build.make:62: recipe for target 'Tests/CMakeFiles/AsyncProcessing.dir/src/AsyncProcessing.cpp.o' failed
CMakeFiles/Makefile2:2238: recipe for target 'Tests/CMakeFiles/AsyncProcessing.dir/all' failed
Makefile:140: recipe for target 'all' failed
/home/userA/c++maps/libosmscout/Tests/src/AsyncProcessing.cpp:115:53:   required from  here
/home/userA/c++maps/libosmscout/libosmscout/include/osmscout/util/ProcessingQueue.h:176:12: error: could not convert ‘task’ from ‘VectorData’ to ‘std::optional<VectorData>’
     return task;
``` 
Please help to build the library.
Thanks in advance.

PS: I am trying to build an application using c++ on linux(ubuntu 18.04) to display map, and get routes.

**Comment by Akshay-Prakash** [comment]
SOLVED

changed line 169 in libosmscout/libosmscout/include/osmscout/util/ProcessingQueue.h from

>     T task=std::move(tasks.front());
to

>     std::optional<T> task=std::move(tasks.front());

**Comment by Karry** [comment]
Than you for report. It is reproducible with our Ubuntu 18.04 docker image. It seems that older gcc have problem with implicit conversion from `T` to `optional<T>` when only move constructor/assignment is possible.

Here is merge request with your fix: https://github.com/Framstag/libosmscout/pull/1011

Thank you again
