### ISSUE TITLE
Support caching of low level text objects for rendering

### ISSUE THREAD

**Issue by Framstag** [Framstag/libosmscout#104]
currently low level graphics engine specific object like QTextLayout or PangoLayout are once created for getting text bounding box and later again for actual rendering. Find a way to cache these objects for later reuse, reducing CPU overhead and improving rendering speed.

**Comment by Framstag** [comment]
@Karry What is your opinion, is this really necessary? It would cost additional memory and IMHO the renderer is currently fast enough?

**Comment by Karry** [comment]
Well, the original statement 
> once created for getting text bounding box and later again for actual rendering

is not true anymore. All label properties can be stored in `NativeLabel` class inside `Label` (`LabelLayouter.h`) and its dimension is evaluated just once. I don't see obvious place for optimisations, at least with Qt and Pango backend. You can close this ticket I guess...
