### ISSUE TITLE
Improve clipping contour label rendering

### ISSUE THREAD

**Issue by Framstag** [Framstag/libosmscout#105]
Currently all contour labels are rendered in case the bounding box of a way intersects with the visible area.

Since for big ways the bounding boxes may interleave though the way is not visible at all, because it is just meandering around the visible area but not crossing it, we should find a better algorithm for intersection and label clipping.

**Comment by Karry** [comment]
I think that we can close it. At least for Qt we have implementation that check possible visibility for each glyph before renderign.

**Comment by Framstag** [comment]
Yes, of course. All backends should use a similar trick. It would be nice, if the required functionality would be part of the base class, so it is much easier for backends to make use of this feature.

**Comment by Karry** [comment]
I will try to rewrite label layouter to use glyph as base unit for all backends (except OpenGL and DirectX probably).

**Comment by Karry** [comment]
I am closing this issue. All glyphs outside visible  area (layouter viewport more precisely) are skipped in `Layouter::RegisterContourLabel` and are not rendered now.
