### ISSUE TITLE
https://osmscout.karry.cz server is not providing data

### ISSUE THREAD

**Issue by jheaff1** [Framstag/libosmscout#1112]
Hi,

It appears that the server hosted at https://osmscout.karry.cz is currently not providing any map data. Is this intentional? If so, may I ask when the map data be reinstated?

**Comment by Karry** [comment]
Hi. I had hardware problems with that "server" last week (died power supply, dying disk), it had multiple outages while I was fixing that. This server has no mirror unfortunately... 

As one improvement, I moved map data to smaller but faster SD card :-) To be able to do it, I removed older map databases (format version < 22). So, is server working for you right now? If not, which libosmscout revision you are using? What it is printing to the log?

**Comment by jheaff1** [comment]
Hi @Karry,

Thank you for the prompt response. The server isn't working for me at the moment.

I am using commit 8949f223db631cada9a468d6297ce355babecab3 (March 2020). I'll look into getting the logs. Thanks

**Comment by jheaff1** [comment]
It does seem like the directories at https://osmscout.karry.cz/ are empty though, e.g. https://osmscout.karry.cz/africa/algeria-22-20210804-2311/

**Comment by Karry** [comment]
Your version of libosmscout is too old. It supports database format 19, see https://github.com/Framstag/libosmscout/blob/8949f223db631cada9a468d6297ce355babecab3/libosmscout/include/osmscout/TypeConfig.h#L811 These map databases are not available on the server anymore. Please upgrade library to recent version if you can.

**Comment by jheaff1** [comment]
Ah I see, thanks!
