### ISSUE TITLE
iOS 15 Tiling Bug

### ISSUE THREAD

**Issue by frogg** [Framstag/libosmscout#1113]
I just tried running the iOS sample project for the first time on iOS 15.
This is a totally unexpected result, something with the MapKit tiling must have changed? Or the scaling of the screen?

Same code with same map data running on both devices.

![IMG_0869](https://user-images.githubusercontent.com/5204169/130327518-def8e1ca-1f23-4ee9-8ac3-11f0c534a0a2.jpeg)

**Comment by vyskocil** [comment]
Damnit ! I didn’t tried iOS 15 yet… 
Do you merged the fixes for the demo app from the merge request ?

**Comment by vyskocil** [comment]
It may be the same issue I fixed for Mac OSX in this commit : https://github.com/Framstag/libosmscout/pull/1106/commits/c250d8009b566e4ebfc8db018bd8ca5ac8bb9107

**Comment by vyskocil** [comment]
Hi @frogg ! I tryied the demo app on the iOS 15 beta simulator using XCode 13.0 beta 5 and could reproduce the issue.
I pushed a commit (https://github.com/Framstag/libosmscout/pull/1106/commits/a3751af37a807c199377c0d680cb43cc88036412) to the https://github.com/Framstag/libosmscout/pull/1106  pull request that fix the issue for iOS device and simulator for iOS version < 15 and for iOS simulator for iOS version >= 15 but I couldn't try yet with a real device, maybe you could try ?

**Comment by vyskocil** [comment]
It seems there is a bug in the XCode 13.0 beta 5 iOS simulator or the MapKit framework, the first tile is not drawn at the right scale or is not refreshed correctly. I don't see this with iOS < 15
![Uploading Screenshot 2021-08-22 at 14.50.22.png…]()

**Comment by vyskocil** [comment]
It seems there is a bug in the XCode 13.0 beta 5 iOS simulator or the MapKit framework, the first tile is not drawn at the right scale or is not refreshed correctly. I don't see this with iOS < 15

<img width="455" alt="Screenshot 2021-08-22 at 14 50 22" src="https://user-images.githubusercontent.com/452704/130356038-69c8788c-e857-43b6-96f1-89ae27356ab3.png">

**Comment by vyskocil** [comment]
@frogg @Framstag this should be fixed.
