### ISSUE TITLE
moved objects in OpenGL renderer

### ISSUE THREAD

**Issue by Karry** [Framstag/libosmscout#1175]
With Czech database, OpenGL renderer computes objects coordinates incorrectly, near place [49.2375 14.3702](https://www.openstreetmap.org/search?query=49.2375%2014.3702#map=16/49.2375/14.3714) (zoom level ~14). 

See screenshot - upper part is OpenGL, below is Qt renderer:

![Screenshot_20211218_134054](https://user-images.githubusercontent.com/309458/146641442-401ebf20-5bf2-408a-b78d-2b598ddc4b76.png)

**Comment by Framstag** [comment]
@Karry : Is this alreay fixed by some of your OpenGL changes?

**Comment by Karry** [comment]
Nope. This is bug in OpenGL projection shader. It needs to be fixed to provide same positioning like C++ projection methods.
