### ISSUE TITLE
SSE is detected incorrectly on ARM cpu with Clang

### ISSUE THREAD

**Issue by Karry** [Framstag/libosmscout#1197]
On Czech OSM mailing list, I suggested to one user with Pinephone and Posh to try Osmin. But he replied that compilation fails (with Clang). Osmin setup [OSMSCOUT_ENABLE_SSE to true](https://github.com/janbar/osmin/blob/master/backend/CMakeLists.txt#L167) when it is not compiling for Android. It should not be problem, build system should detect when SSE is available for current platform. It works fine with GCC, but Clang tries to compile SSE code on arm cpu! 

I was able to reproduce it on my Raspberry:
```
CC=clang CXX=clang++ cmake -DCMAKE_BUILD_TYPE=Debug -DOSMSCOUT_ENABLE_SSE=ON .. 
...
-- Performing Test HAVE_ALTIVEC
-- Performing Test HAVE_ALTIVEC - Failed
-- Performing Test HAVE_AVX
-- Performing Test HAVE_AVX - Success
-- Performing Test HAVE_MMX
-- Performing Test HAVE_MMX - Success
-- Performing Test HAVE_SSE
-- Performing Test HAVE_SSE - Success
-- Performing Test HAVE_SSE2
-- Performing Test HAVE_SSE2 - Success
-- Performing Test HAVE_SSE3
-- Performing Test HAVE_SSE3 - Success
-- Performing Test HAVE_SSE4_1
-- Performing Test HAVE_SSE4_1 - Success
-- Performing Test HAVE_SSE4_2
-- Performing Test HAVE_SSE4_2 - Success
-- Performing Test HAVE_SSSE3
-- Performing Test HAVE_SSSE3 - Success
...
```

It is check by this cmake function: `check_c_compiler_flag(-msse2 HAVE_SSE2)`. It seems that we should verify function availability by `try_compile()`

**Comment by Karry** [comment]
Or should be SSE disabled in Osmin? cc @janbar

**Comment by nesnera** [comment]
With Karry's suggested modifications (thanks for the support) and the following prerequisites I was able to complete the build on the PinePhone Manjaro/[Phosh-dev](https://github.com/manjaro-pinephone/phosh-dev) ([packages](https://github.com/manjaro-pinephone/phosh-dev/releases/download/202201090254/Manjaro-ARM-phosh-pinephone-20220109-pkgs.txt))
Additional prerequisites: cmake, clang, make, qt5-quickcontrols2, qt5-sensors, qt5-multimedia, openmp, make, openmp, qt5-graphicaleffects.
Launch fails with this output:
```
[manjaro@manjaro-arm build]$ ./osmin
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
Signal handler is enabled.
User locale setting is C
using file ':/i18n/osmin_en.qm' for translations.
Checking installed assets...
Found assets version 1.7.0
Resource directory is /home/manjaro/osmin/resources
Found hillshade tile server file '/home/manjaro/osmin/resources/hillshade-tile-server.json'
Loading online tile providers from  "/home/manjaro/osmin/resources/online-tile-providers.json"
Loading providers from  "/home/manjaro/osmin/resources/map-providers.json"
Loading providers from  "/home/manjaro/osmin/resources/voice-providers.json"
MapManager ctor
Lookup databases
Basemap found and loaded from ' "/home/manjaro/osmin/resources/world" '...
Register sensor backend: builtin.compass
QQmlApplicationEngine failed to load component
qrc:/controls2/osmin.qml:467:5: Type MapPosition unavailable
qrc:/controls2/components/MapPosition.qml:19:1: module "QtPositioning" is not installed
Failed to load QML
Signal handler is destroyed.
onFlushRecording
~TrackerModule
~Tracker
```
I assume the missing QtPositioning indicates a missing [positioning package](https://distrowatch.com/dwres.php?resource=compare-packages&firstlist=ubuntu&secondlist=manjaro&firstversions=0&secondversions=0&showall=yes#allpackages). However, I can only find it in the gt6 version. 🥴

**Comment by nesnera** [comment]
The last missing package was `qt5-location`. @Karry, thank you for your help 🍺
![image](https://user-images.githubusercontent.com/1737463/148758759-aac8ee17-8b98-4322-85dd-e2107656e0c9.png)

**Comment by Karry** [comment]
Great to hear that Osmin, libosmscout-based application may run on another platform... Ok, it is just another Linux distribution, but mobile distribution :-) 

Closing this issue as SSE detection should work properly now.

**Comment by janbar** [comment]
Very late, but best later than never. Yes SSE is disabled when cmake build on ANDROID. I didn't think the app could be build for a Linux distribution on ARM cpu. @Karry thanks for adding the check on configure.
