### ISSUE TITLE
tbb/task_scheduler_init.h has been removed.

### ISSUE THREAD

**Issue by godefv** [Framstag/libosmscout#1228]
`Import.cpp` includes `tbb/task_scheduler_init.h`, stating that it is deprecated. It has now been removed and causes a compilation error when running `cmake --build <build_dir>`

**Comment by Framstag** [comment]
@Karry AFAIK you added the explicit usage of task_scheduler

I assume that the comment is by you:

"    // create tbb scheduler explicitly to avoid leaks by default scheduler
    // NOTE that task_scheduler_init is deprecated, but there is no way to destruct global scheduler - it is leaking"

It is not a problem to remove the corresponding lines, but I'm not sure if it will break something important?

**Comment by Karry** [comment]
Yes, we can remove this line. But the test will start failing with activated asan :-( I will look to it, it seems that there is another mechanism for that in newer tbb: https://oneapi-src.github.io/oneTBB/main/tbb_userguide/Migration_Guide/Task_Scheduler_Init.html

**Comment by Karry** [comment]
Hi @godefv , can you try https://github.com/Framstag/libosmscout/pull/1229 please? I don't have enough new tbb library on my system...

**Comment by godefv** [comment]
Hi, I get the following error :
```
/data/devel/git/planete3d/extern/libosmscout/libosmscout-import/src/osmscoutimport/Import.cpp:337:18: erreur: « task_scheduler_handle » n'est pas un membre de « oneapi::tbb »
  337 |     oneapi::tbb::task_scheduler_handle handle{tbb::attach{}};
      |                  ^~~~~~~~~~~~~~~~~~~~~
```

**Comment by godefv** [comment]
FYI, my current workaround is simply to remove the deprecated lines like this : 
```diff
--- a/libosmscout-import/src/osmscoutimport/Import.cpp
+++ b/libosmscout-import/src/osmscoutimport/Import.cpp
@@ -75,10 +75,6 @@
 #include <osmscoutimport/GenTextIndex.h>
 #endif
 
-#if defined(HAVE_STD_EXECUTION)
-#include "tbb/task_scheduler_init.h"
-#endif
-
 #include <osmscout/util/MemoryMonitor.h>
 #include <osmscout/util/Progress.h>
 
@@ -332,12 +328,6 @@ namespace osmscout {
 
   bool Importer::Import(ImportProgress& progress)
   {
-#if defined(HAVE_STD_EXECUTION)
-    // create tbb scheduler explicitly to avoid leaks by default scheduler
-    // NOTE that task_scheduler_init is deprecated, but there is no way to destruct global scheduler - it is leaking
-    [[maybe_unused]] tbb::task_scheduler_init task_scheduler;
-#endif
-
     TypeConfigRef typeConfig(std::make_shared<TypeConfig>());
     progress.StartImport(parameter);
```

**Comment by godefv** [comment]
My version of the tbb library is `2021.5.0-1`.

**Comment by Karry** [comment]
So, there is another attempt: https://github.com/Framstag/libosmscout/pull/1230 I don't want to remove it completely because I am running ASAN build of Import time to time to make sure that we are not leaking some resources...

**Comment by godefv** [comment]
It compiles on my system !
I didn't know about `try_compile` in cmake, interesting.

**Comment by Karry** [comment]
Great. Tim merged the fix, closing the issue. Thank you for patience.

**Comment by godefv** [comment]
Thanks ! 
It's great to be able to work with the official repository without a patch :)
