### ISSUE TITLE
Android build

### ISSUE THREAD

**Issue by nishiths23** [Framstag/libosmscout#1291]
How to build android lib for all available architectures?

I tried the build.sh script from Android/OsmScoutLib/jni but it gives this error : 

/root/libosm/libosmscout/Android/OsmScoutLib/jni/src/jniDatabase.cpp:24:10: fatal error: 'osmscout/AdminRegion.h' file not found
#include <osmscout/AdminRegion.h>

**Comment by Framstag** [comment]
Hi,

over the years, we tried a few approaches to better support use of the library under Android. You hit one of them in the repository. In this regard, we need some cleanup by someone that is actively using the library under Android.

To answer your question...What do we currently have:
* We have a GitHub Actions based build that builds the core libraries against Qt5 using cmake under Ubuntu for the Android platform (arm64). See https://github.com/Framstag/libosmscout/blob/master/.github/workflows and /build_on_ubuntu_18_04_qt_android.yml or https://github.com/Framstag/libosmscout/runs/7892804938?check_suite_focus=true
* There is a working Android application based on Qt. See https://github.com/janbar/osmin

What we do not have:
* Multi-Platform Android build, though that should be doable based on our build
* Active Support for integration of the library in to Java/Kotlin application. We did experiment with SWIG, but that is lacking features. Currently it looks like one needs a high-level C Wrapper for integration or uses separate processes for UI and backend. Help in this area is welcomed.

**Comment by nishiths23** [comment]
I did not expect such a quick reply. Thank you so much. This sample application actually helps a lot

**Comment by Framstag** [comment]
Hi @nishiths23 As we have initially answered your request, can we close the issue? If you have further questions, please create new issues.

**Comment by nishiths23** [comment]
A suggestion for future - https://github.com/heremaps/gluecodium

Gluecodium works with lime files but is great at generating bindings. Not just for android you would be able to generate bindings for flutter as well.

Other then this, yes we can close this issue

**Comment by Framstag** [comment]
Closing the issue
