### ISSUE TITLE
Add additional import flags for cleanup of files

### ISSUE THREAD

**Issue by Framstag** [Framstag/libosmscout#133]
As shortly discussed on the mailing list: It may make sense to add additional flags to the import to delete some files automatically in case the import call runs through and there is no error.

Suggestions:
--delete-tmp
--delete-debug
--delete-optional (possibly we should add a flag for each group of optional files)

**Comment by Framstag** [comment]
Added
* --delete-temporary-files
* --delete-debugging-files

Will add:
* --delete-analysis-files
* something about "optional files"

**Comment by rinigus** [comment]
Thank you for taking it in! Right now, it looks that the following files are not deleted when I use --delete-temporary-files true --delete-debugging-files true during import:

index.html  location_full.txt  location.html  location_region.txt  relation.html  way.html

In particular, location_full.txt is huge (20% extra from what you need).

Thank you again for working on it!

**Comment by Framstag** [comment]
These would be deleted by the "to be implemented" --delete-analysis-files. The importer however currently does not have any metadata about these files. It has to be added first. Note, that the bug is not closed yet because of this :-)

**Comment by Framstag** [comment]
Now also

* --delete-analysis-files
* --delete-report-files

added.
