### ISSUE TITLE
Get city name from region array

### ISSUE THREAD

**Issue by Dizzy55** [Framstag/libosmscout#1339]
I try to create searching of map objects by its names. For this purpose I have used "LocationListModel" model in my QML page. I have a region array for each found item. Now I use it as text string
`text: region.join(", ")`
But result text is too long and I would like to show city name only (if it exists of course). How to determine index of region array for the city, or may be there is another way to get the city name?
Thanks in advance

**Comment by Karry** [comment]
Hi. Region list is build from [OpenStreetMap administrative regions](https://wiki.openstreetmap.org/wiki/Tag:boundary%3Dadministrative). City name is usually region with `admin_level = 8`. Problem is that we are not exposing admin level to QML model. When some lower admin region will be missing, you will find city on lower index... I will try to address that.

**Comment by Karry** [comment]
I looked to this problem more deeply. Administration level is is part of the Area's features. So it is possible to lookup region list from location index and then lookup areas and its features for these admin regions. But I don't like this, it is too complicated. Instead, I will try to add admin level to location index directly.

**Comment by Framstag** [comment]
Would be the evaluation of admin_centre the right thing, see https://wiki.openstreetmap.org/wiki/Key:capital#Retrieving_capitals_from_boundary_relations? It is a while since I initially wrote the code (and Kerry later improved it), but a first scan shows, that we do not evaluate this information, yet.

To clarify the requirements...

Currently, (looking at my home region) the index looks like this (excerpt from location_full.txt):

```
     + Eving Area 10221142
       = Lindenhorst Node 4370032
       = Holthausen Node 4459282
       = Kemminghausen Node 4460529
       = Brechten Node 4532302
       * Peking Metropole Area 7539861
       * Parkplatz KGV Brechten Area 7560222
       * eat Area 7584669
...
# 44339
         - Alfred-Lange-Straße
           = Way 23592993
           = Way 23593062
           = Way 23593556
             @ 21 Area 7558421
             @ 40a Area 7558441
         - Alte Ellinghauser Straße
           = Way 22865203
           = Way 22866800
           = Way 22868369
           = Way 22868412
             @ 88 Area 7801235

```

The "*" mark the area", "=" are aliases "* is the start of the list of POIs. Later on you have postal areas "#", locations "-", OSM objects "=" and adresses "@".

I assume you want something like this. You found an object (a poi or an address) and write something like "ZOO (Dortmund)", where "Dortmund" is the name of the parent area(?) the area that represents a city (which is represented by a certain admin level, which could be some more regions above the innermost)...or?

Btw., we currently do not dump the admin level in this file ;-)

**Comment by Framstag** [comment]
Btw, the aliases for the region exist, because these are lower admin levels for historical regions which do not have a clear border now (the city does not specify where "Brechten" within "Eving" exactly is placed).

**Comment by Karry** [comment]
@Framstag you are right, we do not have admin level as part of location index. But we can pickup `region.object` read corresponding Area and then pickup admin region from `AdminLevelFeature`. But it is a bit complicated. As I wrote, it would be easier to add this byte to location index directly.

**Comment by Framstag** [comment]
The admin level it at least part of the GenLocationIndex() data structures. But it looks like it is not written to the index.

FYI: I'm currently preparing a pull request that adds the admin level to the *debug output*. I'm also fixing some sonar issue while at it.

**Comment by Karry** [comment]
> But it looks like it is not written to the index.

Exactly. It would be easy to add it there. Just keep in mind that it would be change of database format and require increase of format version.

Meanwhile, I implemented the change in Qt models by area lookup:
https://github.com/Framstag/libosmscout/pull/1344

**Comment by Framstag** [comment]
@Karry I have done now some refactoring of the code (more refactoring necessary, but time is up). Should I add the admin level of the region to the location index? I'm not sure, if this would be helpful. It would not be a big deal, but is it worth changing the file format version?

**Comment by Karry** [comment]
Well, not sure either. In current implementation, admin level is looked up from the Area object. It require some extra cpu cycles, but I don't measure how much. I other words, I believe that we don't need it - at least now. Location index (tree) contains admin region name, alternative name, aliases, postal codes... All these fields are necessary for region lookup. I don't have usecase when region lookup would require to know admin level. 

But I may imagine the case when someone will be searching just district name, or city name (specific region level)... Like - I'm looking for Washington state, not the city, I'm looking the Prague city, not the region and so on...

**Comment by Karry** [comment]
Hi @Dizzy55 , LocationListModel now has `indexedAdminRegion` role. You will find city/town name at index 8 in most countries. Feel free to reopen this issue when there is something wrong or missing.
