### ISSUE TITLE
Build failed on Ubuntu 20.04.5

### ISSUE THREAD

**Issue by cmosig** [Framstag/libosmscout#1357]
I followed the installation instructions on the website, but the build failed. 

```
[ 46%] Building CXX object libosmscout-map-cairo/CMakeFiles/OSMScoutMapCairo.dir/src/osmscout/MapPainterCairo.cpp.o
In file included from /usr/include/pango-1.0/pango/pango-font.h:25,
                 from /usr/include/pango-1.0/pango/pango-attributes.h:25,
                 from /usr/include/pango-1.0/pango/pango.h:25,
                 from /usr/include/pango-1.0/pango/pangocairo.h:25,
                 from /home/cmosig/gitRepos/libosmscout-code/libosmscout-map-cairo/include/osmscout/MapPainterCairo.h:35,
                 from /home/cmosig/gitRepos/libosmscout-code/libosmscout-map-cairo/src/osmscout/MapPainterCairo.cpp:20:
/usr/include/pango-1.0/pango/pango-coverage.h:28:10: fatal error: hb.h: No such file or directory
   28 | #include <hb.h>
      |          ^~~~~~
compilation terminated.
make[2]: *** [libosmscout-map-cairo/CMakeFiles/OSMScoutMapCairo.dir/build.make:90: libosmscout-map-cairo/CMakeFiles/OSMScoutMapCairo.dir/src/osmscout/MapPainterCairo.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:635: libosmscout-map-cairo/CMakeFiles/OSMScoutMapCairo.dir/all] Error 2
make: *** [Makefile:146: all] Error 2
```

`/usr/include/harfbuzz/hb.h` exists on my system, so I am unsure how to proceed. Or is it an issue in pango?

**Comment by Karry** [comment]
Hi. Can you put following lines to the end of `libosmscout-map-cairo/CMakeLists.txt` and run CMake again?

```
MESSAGE(STATUS "HARFBUZZ_FOUND: ${HARFBUZZ_FOUND}")
MESSAGE(STATUS "HARFBUZZ_INCLUDE_DIRS: ${HARFBUZZ_INCLUDE_DIRS}")
MESSAGE(STATUS "HARFBUZZ_LIBRARIES: ${HARFBUZZ_LIBRARIES}")
```

Was this HarfBuzz library detected on your system? What System do you have?

**Comment by cmosig** [comment]
These variables don't seem to have any values. I get:

```
-- HARFBUZZ_FOUND: 
-- HARFBUZZ_INCLUDE_DIRS: 
-- HARFBUZZ_LIBRARIES: 
``` 

> Was this HarfBuzz library detected on your system?

That is a yes?

    > $ sudo ldconfig -p | grep harf                                                                                                
	    libharfbuzz.so.0 (libc6,x86-64) => /lib/x86_64-linux-gnu/libharfbuzz.so.0
	    libharfbuzz.so (libc6,x86-64) => /lib/x86_64-linux-gnu/libharfbuzz.so
	    libharfbuzz-icu.so.0 (libc6,x86-64) => /lib/x86_64-linux-gnu/libharfbuzz-icu.so.0
	    libharfbuzz-icu.so (libc6,x86-64) => /lib/x86_64-linux-gnu/libharfbuzz-icu.so
	    libharfbuzz-gobject.so.0 (libc6,x86-64) => /lib/x86_64-linux-gnu/libharfbuzz-gobject.so.0
	    libharfbuzz-gobject.so (libc6,x86-64) => /lib/x86_64-linux-gnu/libharfbuzz-gobject.so

**Comment by Framstag** [comment]
Are you willing to try the meson build instead? If both builds fail this may be the sign, that either distribution packages are missing or the installation is broken (which should not be, but who knows). Pango -Dev Dependencies should already trigger installation of the low level harfbuzz library. But either this does not happen, or the library is not found or pango and harfbuzz are not compatible...(and yes, I expect not such problem with Ubuntu).

**Comment by Framstag** [comment]
I used the ci/docker/ubuntu_20.04._gcc_cmake Docker-Image to check the build there:

I can see that lgbuzz was installed (by depdencies)
```
Setting up libharfbuzz0b:amd64 (2.6.4-1ubuntu4.2) ...
```

The cmake build itself

```
...
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Found MARISA: /usr/include  
-- Found LibXml2: /usr/lib/x86_64-linux-gnu/libxml2.so (found version "2.9.10") 
-- Found Protobuf: /usr/lib/x86_64-linux-gnu/libprotobuf.so;-lpthread (found version "3.6.1") 
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.11") 
-- Checking prototype iconv for ICONV_SECOND_ARGUMENT_IS_CONST - False
-- Found ICONV: /usr/include  
-- Could NOT find LIBLZMA (missing: LIBLZMA_INCLUDE_DIRS LIBLZMA_LIBRARIES) 
-- Checking for module 'cairo'
--   Found cairo, version 1.16.0
-- Found LIBAGG: /usr/include  
-- Found Pango: /usr/include/pango-1.0  
-- Found Glib2: /usr/include/glib-2.0;/usr/lib/x86_64-linux-gnu/glib-2.0/include  
-- Found Gobject: /usr/include/glib-2.0;/usr/lib/x86_64-linux-gnu/glib-2.0/include  
-- Found Pangocairo: /usr/include/pango-1.0  
-- Found Freetype: /usr/lib/x86_64-linux-gnu/libfreetype.so (found version "2.10.1") 
-- Checking for module 'fontconfig'
--   Found fontconfig, version 2.13.1
-- Found Fontconfig: /usr/lib/x86_64-linux-gnu/libfontconfig.so  
-- Found Pangoft2: /usr/include/pango-1.0;/usr/include/glib-2.0;/usr/lib/x86_64-linux-gnu/glib-2.0/include;/usr/include/glib-2.0;/usr/lib/x86_64-linux-gnu/glib-2.0/include;/usr/include/pango-1.0;/usr/include/pango-1.0;/usr/include/freetype2;/usr/include  
-- Found HARFBUZZ: /usr/include/harfbuzz  
-- Xrandr library not found - required for GLFW
-- xf86vmode library not found - required for GLFW
-- Xcursor library not found - required for GLFW
-- Xinerama library not found - required for GLFW
-- Xi library not found - required for GLFW
...
```

The build succeeded. So maybe you check the package list of that docker images against your currently installed packages?

**Comment by cmosig** [comment]
> Are you willing to try the meson build instead?

I compiled it using meson as described on the website. I am not sure how to tell if it succeeded because I never used meson/ninja. It did not crash and the last output line on stdout was `[458/458] Linking target Tests/Base64Test.`

> I used the ci/docker/ubuntu_20.04._gcc_cmake Docker-Image to check the build there:

That docker image does not seem to exist for me.

**Oh I seem to have an old version of libosmscout.** I used the clone link from your [website](https://libosmscout.sourceforge.net/documentation/download/). The last commit in the downloaded repo was 2018.

I will check now if the installation works with the current github version. I presume it will, but I will report back

**Comment by cmosig** [comment]
Yes, the build does work with the github version. I suggest maybe updating the website? :)

**Comment by Karry** [comment]
Oh god, there is still SourceForge... We are still using it for hosting the website, but the sources, continuous build and whole development is happening on the Github right now.

**Comment by Karry** [comment]
Hi @cmosig , may we close the issue?

**Comment by cmosig** [comment]
Yes, of course.
