### ISSUE TITLE
Building on CentOS8/9

### ISSUE THREAD

**Issue by ross-newman** [Framstag/libosmscout#1364]
I submodule this project in my repo and it all works fine under ubuntu but am having issues with CentOS. This seems to be due to std::filesystem not being supported by default on GCC 8.5.0. I tried adding  -lstdc++fs  as shown below. Will try updating to GCC 9.x but if anyone has a fix. Tried may ways to force  -lstdc++fs with no success.

`[ 49%] Linking CXX executable LocationLookupForm
cd /root/vivoe-lite/build/external/libosmscout/build/Demos && /usr/bin/cmake -E cmake_link_script CMakeFiles/LocationLookupForm.dir/link.txt --verbose=1
/usr/bin/c++ -lstdc++fs -std=c++11 -fvisibility=hidden -fopenmp -Wall -Winit-self -Wno-overloaded-virtual -Wcast-qual -Wwrite-strings -Wextra -Wno-long-long -Wno-unused-but-set-parameter -O3 -DNDEBUG CMakeFiles/LocationLookupForm.dir/Unity/unity_0_cxx.cxx.o -o LocationLookupForm-1.1.1  -Wl,-rpath,/root/vivoe-lite/build/external/libosmscout/build/libosmscout: ../libosmscout/libosmscout.so.1.1.1 -lc -lpthread 
../libosmscout/libosmscout.so.1.1.1: undefined reference to `std::filesystem::remove(std::filesystem::__cxx11::path const&)'
../libosmscout/libosmscout.so.1.1.1: undefined reference to `typeinfo for std::filesystem::__cxx11::filesystem_error'
../libosmscout/libosmscout.so.1.1.1: undefined reference to `std::filesystem::__cxx11::path::has_root_directory() const'
../libosmscout/libosmscout.so.1.1.1: undefined reference to `std::filesystem::status(std::filesystem::__cxx11::path const&)'
../libosmscout/libosmscout.so.1.1.1: undefined reference to `std::filesystem::__cxx11::path::_M_split_cmpts()'
../libosmscout/libosmscout.so.1.1.1: undefined reference to `std::filesystem::rename(std::filesystem::__cxx11::path const&, std::filesystem::__cxx11::path const&)'
../libosmscout/libosmscout.so.1.1.1: undefined reference to `std::filesystem::__cxx11::path::remove_filename()'
../libosmscout/libosmscout.so.1.1.1: undefined reference to `std::filesystem::file_size(std::filesystem::__cxx11::path const&)'
../libosmscout/libosmscout.so.1.1.1: undefined reference to `std::filesystem::__cxx11::path::has_filename() const'
collect2: error: ld returned 1 exit status`

**Comment by Framstag** [comment]
Sorry, now. We expect C++17 (and I would like to go even further, but Sailfish is "slow" in this regard.

I suggest updating the compiler, since I do not have knowledge about getting the older compiler working regarding file system support.

**Comment by Karry** [comment]
Hi. GCC 8.5 should support filesystem as I remember. But do you have an idea why it is build with `-std=c++11` argument?

**Comment by Karry** [comment]
There should be `-std=c++17`

**Comment by ross-newman** [comment]
The C++ 11 flag was a typo.

Issue fixed when updating to gcc9. To do this on CentOS 8 run the following commands before building osmscout2:
`
dnf -y install gcc-toolset-9-gcc gcc-toolset-9-gcc-c++
source /opt/rh/gcc-toolset-9/enable
`
