### ISSUE TITLE
Allow routing start on restricted way

### ISSUE THREAD

**Issue by Karry** [Framstag/libosmscout#1372]
For simplicity, we are handling access values "delivery", "destination" and "private" the same way. Vehicle may access these ways, but it cannot leave it back to unrestricted way. It is correct for access=destination, but not really correct for access=private. Anyway, routing fails when such "private" way is start of the routing, because router cannot leave it...

As discussed originally here: https://github.com/janbar/osmin/issues/35

**Comment by Framstag** [comment]
See further explanation in the referenced ticket regarding  the initial idea behind the access handling in the routing. And the use cases supported.
