### ISSUE TITLE
Meson install dir strips include prefixes

### ISSUE THREAD

**Issue by jheaff1** [Framstag/libosmscout#1375]
Hi,

When building libosmscout with meson, the installation directory (i.e. the directory created after running `meson install`) copies all header files into <installation directory>/include. What should happen is that the header directory structure is maintained, in which case the installation directory would look like:

- <installation directory>/include/osmscout/
- <installation directory>/include/osmscout-client-qt

etc.

As only the meson build supports Qt6, this is blocking me from using libosmscout in a Qt6 application.

**Comment by Framstag** [comment]
The meson install_headers command has a subdir parameter that allows to fix this.

Example for qt:

```
install_headers(osmscoutmapqtHeader, subdir : 'libosmscout-map-qt')
```

results in:

```
...
Installing /home/tim/projects/libosmscout/libosmscout-map-qt/include/osmscoutmapqt/MapQtImportExport.h to /usr/local/include/libosmscout-map-qt/
...
```

If you additional add `preserve_path : true`, this will result in:

```
...
Installing /home/tim/projects/libosmscout/libosmscout-map-qt/include/osmscoutmapqt/MapQtImportExport.h to /usr/local/include/libosmscout-map-qt/osmscoutmapqt
...
```

I'll have to check, what the cmake installation does. Both build systems should result to the same structure.

**Comment by Framstag** [comment]
It looks like the CMake build does similar (though not for all libraries?):

```
	install(DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}/include/osmscout DESTINATION include FILES_MATCHING PATTERN "*.h" PATTERN "private" EXCLUDE)
```

@Karry , @jheaff1 : Any opinions against using version two (subdir and preserve) of the meson install above?

**Comment by jheaff1** [comment]
Apologies I was incorrect in my original description, the CMake output structure looks like:

include/osmscout
include/osmscoutclientqt
include/osmscoutmap
include/osmscoutmapqt

In [this](https://github.com/Framstag/libosmscout/issues/1375#issuecomment-1442265332) comment, @Framstag, your meson build would generate an output structure like:

include/libosmscout
include/libosmscout-client-qt
include/libosmscout-map
include/libosmscout-map-qt

This would result in unresolved includes in dependant projects

**Comment by Karry** [comment]
On Linux, CMake install directory structure looks like this (relative to install prefix):
```
./bin
./share/osmscout (stylesheets, shaders, fonts, demos, OSMScout2, docs, tests)
./lib/cmake/libosmscout

./include/osmscout
./include/osmscoutimport
./include/osmscoutgpx
./include/osmscoutmap
./include/osmscoutmapagg
./include/osmscoutmapcairo
./include/osmscoutmapopengl
./include/osmscoutmapqt
./include/osmscoutmapsvg
./include/osmscoutclientqt
./include/osmscout-test
```
So the only problem is that Meson is using directory names with dash, right? Or is there anything wrong on CMake install dir structure?

**Comment by jheaff1** [comment]
> On Linux, CMake install directory structure looks like this (relative to install prefix):
> 
> ```
> 
> ./bin
> 
> ./share/osmscout (stylesheets, shaders, fonts, demos, OSMScout2, docs, tests)
> 
> ./lib/cmake/libosmscout
> 
> 
> 
> ./include/osmscout
> 
> ./include/osmscoutimport
> 
> ./include/osmscoutgpx
> 
> ./include/osmscoutmap
> 
> ./include/osmscoutmapagg
> 
> ./include/osmscoutmapcairo
> 
> ./include/osmscoutmapopengl
> 
> ./include/osmscoutmapqt
> 
> ./include/osmscoutmapsvg
> 
> ./include/osmscoutclientqt
> 
> ./include/osmscout-test
> 
> ```
> 
> So the only problem is that Meson is using directory names with dash, right? Or is there anything wrong on CMake install dir structure?

Yeah that's right. The CMake install dir structure is fine, the issue is that the meson install structure has a "lib" prefix and has dashes in the name. It needs to match the CMake install dir structure exactly

**Comment by Framstag** [comment]
As you can see from https://mesonbuild.com/Reference-manual_functions.html#install_headers meson is flexible regarding the naming and structure.

The current code in master does not set subdir and uses the default for preserve_path, which is false. This is wrong.

IMHO, we should set preserve_path to true and the value of the subdir attribute should be in line with the cmake files. As I assume this is the dashed subdirectory name I set it accordingly, but seems, I'm wrong. From your input regarding the cmake structure, subdir should stay empty. Correct?

One can easily check what would happen by calling `meson install --dry-run` in the build directory. I can make a pull request, just tell me which values you want and will work ;-)

Btw., should the meson build also create *.pc files?

**Comment by Karry** [comment]
Yes, `preserve_path: true` helps. But it not supported with Meson 0.63.0 and newer... I also synced installation directories of demos and tests: https://github.com/Framstag/libosmscout/pull/1378

**Comment by Framstag** [comment]
You mean, it *is* supported since 0.63.0?

**Comment by Karry** [comment]
Yes, exactly ;-)

**Comment by jheaff1** [comment]
> As you can see from https://mesonbuild.com/Reference-manual_functions.html#install_headers meson is flexible regarding the naming and structure.
> 
> 
> 
> The current code in master does not set subdir and uses the default for preserve_path, which is false. This is wrong.
> 
> 
> 
> IMHO, we should set preserve_path to true and the value of the subdir attribute should be in line with the cmake files. As I assume this is the dashed subdirectory name I set it accordingly, but seems, I'm wrong. From your input regarding the cmake structure, subdir should stay empty. Correct?
> 
> 
> 
> One can easily check what would happen by calling `meson install --dry-run` in the build directory. I can make a pull request, just tell me which values you want and will work ;-)
> 
> 
> 
> Btw., should the meson build also create *.pc files?

Thank you very much. I'm not familiar with meson so can my really offer any help there, but as long as the output install structure matches that of the cmake build, client applications should be able to include osmscout header files with no issue :

**Comment by Framstag** [comment]
The change by @Karry was merged. Can you close the issue, if it was resolved for you?

**Comment by jheaff1** [comment]
Thank you very much for resolving this issue so quickly!
