### ISSUE TITLE
M_PI not declared on windows

### ISSUE THREAD

**Issue by adrian-ollero** [Framstag/libosmscout#1376]
Hi,
I'm developing a cross-platform tool that uses this library to create an SVG frmo an OSM file. On Linux everything goes as expected, however, I'm facing the following error on windows with not much success:
```
{libosmscout-install-path}\include\osmscout/util/Bearing.h(74,28):` error C2065: 'M_PI': undeclared identifier
{libosmscout-install-path}\include\osmscout/util/Bearing.h(126,30): error C2065: 'M_PI': undeclared identifier
{libosmscout-install-path}\include\osmscout/util/Geometry.h(73,22): error C2065: 'M_PI': undeclared identifier
{libosmscout-install-path}\include\osmscout/util/Geometry.h(88,16): error C2065: 'M_PI': undeclared identifier
{libosmscout-install-path}\include\osmscout/util/Geometry.h(89,18): error C2065: 'M_PI': undeclared identifier
```

I've tried to add the _USE_MATH_DEFINES macro, or include <math.h> manually, but anything seems to fix it. The only possible solution I found, which is not very correct, is defining for windows the M_PI macro manually in system/Math.h file, as follows:
```
#if defined(WIN32) || defined(_WIN64)
  #define M_PI       3.14159265358979323846
#endif
#include <cmath> // Current existing line
``` 
Eventhough it is not the best solution, for some cases it could fix this error,  however not in my case. My build system clones this repository when setting up the project, so this change will not be included.

**Is there anything I'm missing so I can have M_PI defined in windows? Should this be fixed in the repo itself with a better solution than defining the macro manually?**

Thanks

**Comment by adrian-ollero** [comment]
In the end I was able to solve it changing the content of the Math.h file like this:
```
#include <cmath>

#if defined(_WIN32) || defined(_WIN64)
  #ifndef _USE_MATH_DEFINES
    #define _USE_MATH_DEFINES
  #endif
#include <math.h>
#endif
```

@Framstag I'm creating a PR so if you consider it is worthy and there is no other solution, maybe you could add it to master,

Thanks

**Comment by Framstag** [comment]
The clean solution would be to use https://en.cppreference.com/w/cpp/numeric/constants - but we are not et C++20 :-(

For our builds we set the define via compiler options (take a look at meson.build for example). So this is fixed a central place. Would this solution possible for you, too?

**Comment by adrian-ollero** [comment]
I'm actually using CMake, and I can see the macro definition is included in the CMakelist of this project. The compilation of the library for windows is done as follows:
```
if not exist "%LIBOSMSCOUT_SOURCE_PATH%" git clone %LIBOSMSCOUT_REPO% %LIBOSMSCOUT_SOURCE_PATH%

if not exist "%LIBOSMSCOUT_VSPROJECT_PATH%" mkdir "%LIBOSMSCOUT_VSPROJECT_PATH%"
cd "%LIBOSMSCOUT_VSPROJECT_PATH%"

cmake -G "Visual Studio 16 2019"^
    -DCMAKE_INSTALL_PREFIX="%DEPENDENCIES_INSTALLATION_PATH:\=/%"^
    -DCMAKE_CXX_FLAGS_RELEASE="/EHsc"^
    -DOSMSCOUT_BUILD_TOOL_STYLEEDITOR=OFF^
    -DOSMSCOUT_BUILD_TOOL_OSMSCOUT2=OFF^
    -DOSMSCOUT_BUILD_TESTS=OFF^
    -DOSMSCOUT_BUILD_CLIENT_QT=OFF^
    -DOSMSCOUT_BUILD_DEMOS=OFF^
    "%LIBOSMSCOUT_SOURCE_PATH%"

cmake --build . --config=Release --target install
``` 
This process is done correctly. The library get installs in my project, however, after that, when compiling my project itself, some lines below in the .bat file. So far, everything seems to be configured correctly, but the error is still comming up, as far as I don't include the lines stated in the previuos comment. I'm sure there is something I'm doing in the worng way or missing something... 

Thank you so much for your quick reply!

**Comment by Framstag** [comment]
The relevant code for libosmscout is in the CMakeList.txt in the root directory in line 154

```
add_definitions(-D_USE_MATH_DEFINES)
```


It is possible, that you add this you build, too?

**Comment by adrian-ollero** [comment]
Finally solved. As you mentioned, I had to add `add_definitions(-D_USE_MATH_DEFINES)` to my CMake file as I was including the math.h header indirectly within my project, so my project needed the `_USE_MATH_DEFINES` macro to be activated.

Thanks.
