### ISSUE TITLE
Routing: taking left turn when its restricted 

### ISSUE THREAD

**Issue by rinigus** [Framstag/libosmscout#141]
I had a chance to test routing and found a case when the left turn was taken by libosmscout while the turn is restricted. The prohibited turn is indicated as such in OSM database and other routers do take a correct path (don't take this turn).

See attached screenshots to see route
![screenshot-16-10-23-13-51-41](https://cloud.githubusercontent.com/assets/15706605/19626376/0513d62e-9939-11e6-9e66-bd7ad170b239.png) , 
restriction in OSM 
![screenshot from 2016-10-23 13-54-25](https://cloud.githubusercontent.com/assets/15706605/19626382/20aec506-9939-11e6-81fc-d9b10eef871c.png) .

Location at OSM: https://www.openstreetmap.org/relation/2164745#map=19/59.43287/24.74650

Latest version of the map was used. Please let me know if I can help debugging it.

**Comment by Framstag** [comment]
Libosmsocout should support TurnRestrictions of the type from (Way), via (Node), to (Way). The initial parsing is done in Preprocess::IsTurnRestriction and TurnRestrictionSubTask.

This raw data is later on resolved and used by the GenRouteData.cpp and evaluated by the CanTurn() method.

In your case the relevant relation seems to be https://www.openstreetmap.org/relation/2244315. If you tcan point me to the actual import you are using (geofrabrik?), I can debug it and tell you what is happening.

My initial idea would be to use DumpData to dump the relevant route node. I hope I can resolve the route node id by resolving the OSM id of the via to an libosmscout node id. By I admit I have not yet tried this. If this fails, I would add some std:.cout in the code to get the ids and dump the data structures and the result of the CanTurn() method...

**Comment by rinigus** [comment]
For some reason, my reply from yesterday did not get through.

Data is coming from geofabrik: http://download.geofabrik.de/europe/estonia-latest.osm.pbf 

I must say that this is beyond my abilities right now to debug this issue. The simple route that has an issue  is for example from / to:

    "locations": [
        {
            "lat": 59.432798843330147,
            "lng": 24.743602311190983
        },
        {
            "lat": 59.437215000000002,
            "lng": 24.745370000000001
        }
    ],

Would be great if you could help with it - I guess it is probably showing up in other places as well.

Best wishes,

rinigus

**Comment by Framstag** [comment]
If have just pushed a change to the GitHub repository. You can now also dump the exclusions of the route node:

src/DumpData ../maps/estonia -rn 312969622

RouteNode {
  fileOffset: 7863374
  OSMScoutId: 3793310957328790017
  lat: 59.43301
  lon: 24.74598

  path {
     object: Way 9939905
  }

  path {
     object: Way 9940428
  }

  path {
     object: Way 9940428
  }

  path {
     object: Way 9942927
  }

  exclude {
     from: Way 9939905
     to: Way 9940428
  }
}

With https://www.openstreetmap.org/node/312969622

So it seems like the turn restriction has been detected.

**Comment by rinigus** [comment]
It is coming from geofabrik:
http://download.geofabrik.de/europe/estonia-latest.osm.pbf . I may try to
debug it later, probably tomorrow evening, if you wouldn't beat me to that
:)

Best wishes,

rinigus

**Comment by rinigus** [comment]
Strange - email went through 2 days later. 

I'll have to read on the restrictions and try to understand how OpenStreetMaps presents them. The route that I am interested in (and which is wrong) goes from the left and turns up (screenshot from Poor Maps). I am not sure whether the restriction that you linked corresponds to the way going from left to right or to the way going from right to left. 

[pure speculation] Maybe the library detects it for another direction only and that's why its not taken into account? I surely have to read more about it...

Thank you for looking into it!

**Comment by rinigus** [comment]
I looked a bit into the relations and here is what I found. For some reason, I cannot find https://www.openstreetmap.org/way/168407119 in the import:

```
/usr/local/osmscout/bin/DumpData estonia -w 168407119
Cannot find 'Way' with id 168407119
```

The relation in OSM for the node 1432105289 (https://www.openstreetmap.org/node/1432105289) is detected by the library:
```
/usr/local/osmscout/bin/DumpData estonia -rn 1432105289                                                                    1 :(
RouteNode {
  fileOffset: 7856403
  OSMScoutId: 3793310953046338817
  lat: 59.43292
  lon: 24.74597

  path {
     object: Way 9936186
  }

  path {
     object: Way 9936186
  }

  path {
     object: Way 9936627
  }

  path {
     object: Way 9936851
  }

  exclude {
     from: Way 9936627
     to: Way 9936186
  }
}
```

However the way 9936186 is 
```
/usr/local/osmscout/bin/DumpData estonia -wo 9936186  
Way {
  OSM id: 4852936
  fileOffset: 9936186
  type: highway_secondary
  boundingBox: [59.42729 N 24.74276 E - 59.43301 N 24.74598 E]
  center: 59.43015 N 24.74437 E
  cell level: 14
...
```
which is different from the one that is used in OSM relation and, at least in OSM, this way starts a bit later. Eventually routing algorithm moves to 4852936, which is a problem.

**Comment by Karry** [comment]
It sounds like Import tool merge these two paths and throw information (osm id) about merged ways...

**Comment by rinigus** [comment]
Good morning!

I guess its OK to merge the ways if all restrictions are still in place. There is a restriction in the libosmscout database on a turn - question is which way was that tiny-tiny way merged to... Maybe it was merged with the part that was arriving to the crossing from below? 

I wonder, do we have any option to skip merging the ways? Maybe I can try then to make a version of the import without merging them and see if the problem would go away?

Best wishes,

rinigus

**Comment by rinigus** [comment]
I tested now the import where the ways were not merged non split (commented out sections in GenWayWayDat and the routing was correct. So, something in merging/splitting manages to alter restrictions.

**Comment by Framstag** [comment]
Merging ways is now to my to create such conflicts, thus I was sure that this was handled (e.g. by reading the turn restrictions and blacklist ways that are part of such relations) but obviously it is not. I hope to be able to take a look at this at the weekend. Thanks for the analysis, which helps me to concentrate on the actual fix.

**Comment by Framstag** [comment]
I have now added some (local) debugging code:

```
===> Merging ways 168407119 and 274340126
===> Updating turn restriction on way 168407119 to way 274340126
===> Way 129871206 is restricted for node 1432105289
===> Merging ways 274340126 and 4852936
===> Updating turn restriction on way 274340126 to way 4852936
```

So, yes, if you look at https://www.openstreetmap.org/node/1432105289#map=19/59.43272/24.74584, the "Pärnu mnt" above and below the routing node have been merged (and possibly further merges have happened afterwards).

See also the result of:
```
src/DumpData ../maps/estonia -rn 1432105289  -w 129871206 -w 168407120 -wo 9939905
```

So the exclusion seems to be OK. It now means, if you come from the left, you must not drive left (north) or right (south). Nevertheless it does. HAve to look now at the debugging output of the router...

**Comment by Framstag** [comment]
The router does not see the turning restriction:

```
Analysing follower of node 7857516 (Way 9940346[3793310953046338817]) 0.0026948 
  Skipping route to 7857265 (Way 9939905) => Cannot be used
  Inserting route to 7863374 (Way 9939905) 0.0028892 0.00342749 0.00631669 37933
  Skipping route to 7857668 (Way 9940346) => back to the last node visited
  Inserting route to 7857996 (Way 9940570) 0.0028264 0.00353243 0.00635883 37933
```
It blocks the way to the south, because the profile claims, it cannot be used (very likely because it is a oneway!), but the way north is not blocked. Hmmm.....

**Comment by Framstag** [comment]
OK, I have now pushed a change to the github repository that should fix the problem. At least now the router chooses a different (more complex) way.

Cause: The router checks if there is an exclusion for source to destination. However comparison was done by comparing index into a lookup array. The index was not equal, but since the way was in the array two times, this was not enough. Comparing actual objects fixed the problem (the question for me is though, why the object was in the array twice...).

**Comment by Framstag** [comment]
...looks like the code was just wrong.

**Comment by rinigus** [comment]
Hi! I tried with the new import and new lib version. Now, the path is different and this left turn is not taken. So, I guess original issue is gone :)

Unfortunately, not is all fine in the proposed path. Namely, it routes through  http://www.openstreetmap.org/way/219653484 and ways nearby that correspond to the tunnel under a shopping center that can be used by bus only. In OMS, its marked using property access (its set to "no"). I wonder whether this property is imported correctly? Do you want to have it open as a separate issue?

**Comment by Framstag** [comment]
if you look at the dump, it seems like the access=no is not correctly detected/handled:

```
src/DumpData ../maps/estonia -w 219653484
Way {
  OSM id: 219653484
  fileOffset: 9947085
  type: highway_service
  boundingBox: [59,43552 N 24,75631 E - 59,43585 N 24,75684 E]
  center: 59,43568 N 24,75657 E
  cell level: 19

  Layer: -1
  Bridge: false
  Tunnel: true
  Roundabout: false
  Access {
    oneway: forward
    car: forward
  }

  node[0] { serial: 1 id: 3793310987667685633 lat: 59.43553 lon: 24.75684 }
  node[1] { lat: 59.43552 lon: 24.75670 }
  node[2] { lat: 59.43554 lon: 24.75663 }
  node[3] { lat: 59.43563 lon: 24.75644 }
  node[4] { lat: 59.43571 lon: 24.75633 }
  node[5] { serial: 1 id: 3793310991944842241 lat: 59.43585 lon: 24.75631 }
}
```

I'll take a look, what is happening. We can stay in this issue...

**Comment by Framstag** [comment]
Libosmscout uses two `TypeFeature` for handling access. `AccessFeature` itself, gives information, if access is in principle allowed for a given vehicle. Since `motor_vehicle=private` is set for the object, this is interpreted as "yes, access allowed". `AccessRestrictedFeature` tells, if the access is somehow "restricted". Restricted areas can be entered during routing, but must not be left again. This way, if you target a restricted way/area, you are allowed to do so and will get a route. But restricted areas/ways are not used to route you "somewhere else".

So in this case because of `motor_vehicle=private` it would be expected, that the way has an `AccessRestrictedFeature`.

If you look however at the code of the `AccessRestrictedFeature::Parse()` you see, that only "delivery" and "destination" result in such flagging. I have now extended the code to also evaluate "private". It is likely that more has to follow (and we should change the code to check against a hashset of strings...)

**Comment by rinigus** [comment]
That seems to work and libosmscout finds a legal way, as far as I remember. Thank you for the fixes!

**Comment by Framstag** [comment]
Can the issue get closed?

**Comment by rinigus** [comment]
Sorry, yes, it can.
