### ISSUE TITLE
Eurasia flooded in basemap

### ISSUE THREAD

**Issue by vvyskocil** [Framstag/libosmscout#1425]
I imported the world basemap from coastlines with the recent version with the following command : 

BasemapImport  --destinationDirectory world --coastlines data/coastlines-split-4326/lines.shp --maxIndexLevel 11

At low level zoom it is ok : 

![IMG_7765](https://user-images.githubusercontent.com/125963119/236698218-127b3833-8325-4122-8754-3224602e3ff1.PNG)

but on the next zoom level the whole Eurasian continent is flooded : 

![IMG_7766](https://user-images.githubusercontent.com/125963119/236698285-da3a3572-aceb-43d1-917e-d1ee7dd7beec.PNG)
![IMG_7767](https://user-images.githubusercontent.com/125963119/236698289-960162f2-c5ba-4866-85ba-57fae46cf982.PNG)
![IMG_7768](https://user-images.githubusercontent.com/125963119/236698291-80e99e22-fb68-4e49-a4a2-9494f116c014.PNG)
![IMG_7769](https://user-images.githubusercontent.com/125963119/236698293-e9a47199-6842-4315-8e33-dbc84fa15751.PNG)

**Comment by vvyskocil** [comment]
My bad ! I downloaded the latest coastlines-split-4326 files and rebuilt the basemap and it's all right now !
Closing the issue...

**Comment by Karry** [comment]
Coastline data are broken sometimes and our importer code is pretty sensitive to it...
