### ISSUE TITLE
Import tool broken?

### ISSUE THREAD

**Issue by MBF-VR** [Framstag/libosmscout#143]
Please accept my apologies for any (technical or social) mistakes here: no techy and totally new to GitHub.

I am trying to save some maps for an upcoming trip. I downloaded the OSM Scout app for Jolla phone, and followed the instructions here: https://pod.geraspora.de/posts/d10a3e0059c1013420224860008dbc6c
I followed the instructions and had (almost) no problem till the moment of the ./build.sh script. I get:

**$ ./build.sh shanghai_china.osm 
Mapping File:
 shanghai_china.osm
Creating target directory shanghai_china...
Target directory:
 shanghai_china
Outputfile:
 shanghai_china.txt
Options:
 
Call:
 ../Import/src/Import  --typefile ../stylesheets/map.ost --destinationDirectory shanghai_china shanghai_china.osm
./build.sh: line 63: ../Import/src/Import: No such file or directory**

I checked and believing that the file is actually Import.cpp, I modified ./build.sh by adding .cpp to the file's name; but either it was not that, or there is some other issue too, because then I got:

**$ ./build.sh shanghai_china.osm 
Mapping File:
 shanghai_china.osm
Target directory:
 shanghai_china
Outputfile:
 shanghai_china.txt
Options:
 
Call:
 ../Import/src/Import  --typefile ../stylesheets/map.ost --destinationDirectory shanghai_china shanghai_china.osm
../Import/src/Import: line 1: /bin: Is a directory
../Import/src/Import: line 2: TravelJinni: command not found
../Import/src/Import: line 3: syntax error near unexpected token `C'
../Import/src/Import: line 3: `  Copyright (C) 2009  Tim Teulings'**

So, first, I hope this helps; second, if possible please let me know if I am doing something wrong.
Thank you.

**Comment by Karry** [comment]
Hi. You need to compile Import tool first if you want to prepare maps yourself... Was compilation successful? 

Or you can use prepared maps. If you want maps for China, download this archive https://osmscout.karry.cz/asia/china-10-20161009.tar and unpack it to `Documents/Maps` directory on your phone...

**Comment by MBF-VR** [comment]
Ok. My mistake; I thought that I had to run only that script.

I have not tried to compile Import. Right now, as you may understand I am leaving. I will try to use this tool soon, though.

In any case, thank you very much: for the prompt answer and for the maps link.
