### ISSUE TITLE
BoundingBox of imported database too big

### ISSUE THREAD

**Issue by vyskocil** [Framstag/libosmscout#1449]
I imported france.osm.pbf and great-britain.osm.pbf from geofabrik using their bounding polygon with command line like the following : 

```Import --destinationDirectory . --textIndexVariant both --bounding-polygon ../france.poly ../france.osm.pbf```

Then in my code I wanted to check the bounding box of the database against another bounding box with the following code : 

```
       GeoBox boundingBox(GeoCoord(latTop,lonLeft),
                           GeoCoord(latBottom,lonRight));

        GeoBox mapBoundingBox;
        for(int i=0; i<maps.size(); i++){
            lookupDatabases[i]->GetBoundingBox(mapBoundingBox);
            std::cout << "- Map " << i << " (" << maps[i] << ") bounding box: " <<  mapBoundingBox.GetDisplayText() << std::endl;
            if (boundingBox.Intersects(mapBoundingBox)) {
                ...
```

This code display the following output : 

```
- Search area: [43.44070 N 6.62031 E - 43.79226 N 7.32343 E]
- Map 0 (France.osmscout) bounding box: [31.21000 N 20.03320 W - 58.18455 N 29.91000 E]
- Searching in map 0 for 'amenity_restaurant' as node area
- Searching in map 0 for 'amenity_restaurant_building' as area
- Map 1 (GreatBritain.osmscout) bounding box: [35.50040 N 74.01882 W - 76.46420 N 16.58294 E]
- Searching in map 1 for 'amenity_restaurant' as node area
- Searching in map 1 for 'amenity_restaurant_building' as area
```

The search boundingBox always intersect the map bounding boxes because they seems way too big !

Here is the great-britain.poly file : 

```
none
1
   9.326076E-01   5.057032E+01
   2.578056E-01   5.021031E+01
   -7.068725E+00   4.952300E+01
   -5.002163E+00   5.351157E+01
   -4.159730E+00   5.434817E+01
   -4.339602E+00   5.445887E+01
   -5.009768E+00   5.433575E+01
   -6.208707E+00   5.533747E+01
   -6.604158E+00   5.543057E+01
   -7.148041E+00   5.566455E+01
   -1.486751E+01   5.746894E+01
   -1.499070E+01   5.768017E+01
   -1.208287E+01   5.853333E+01
   -1.637515E+00   6.113564E+01
   -2.404508E-01   6.110237E+01
   1.423935E-01   5.993252E+01
   9.781600E-02   5.942198E+01
   7.998970E-01   5.579959E+01
   2.133265E+00   5.384908E+01
   2.513672E+00   5.268668E+01
   1.951517E+00   5.118620E+01
   9.326076E-01   5.057032E+01
END
END

```

**Comment by Framstag** [comment]
(Dumping some facts)

The Database BoundingBox has its origin in the BoundingBox Datafile. Its contents are written in the preprocess step. The bonding box calculated there is based on the coordinates of the read nodes (Preprocess.cpp, line 765).

The polygon is loaded in the Preprocess step, too. It is there identified and is handled as raw data polygon (in coastline format) and store in that datafile. It is later on read by the GenWaterIndex step to synthesize coastlines (@Karry know the details). I assume the trick will be, that not water will be generated beyond the bounding box of the map?

Nevertheless, the bounding box of the database and the bounding box passed to the importer have different purpose. The bounding box passed does not influence the database bounding box.

From history I know that country datafiles contain all areas owned by Great britain. This might include some island somewhere in the atlantic ocean, thus increasing the bounding box beyond expected area (possibly the same for france). Or it might contain polygon that ar ebigger than the artual area and which are not clipped.

I suggest to add some debug code to the Preproces lines, where the boundig box is calculated, add a check for nodes beyond the expected bonding box and dump the nod id of the nodes "outside". Thiswill help use to indentify the cause...

**Comment by Karry** [comment]
You are right, @Framstag . Bounding box polygon just crop coastline (water index) data. Database bounding box contains all database objects. Geofabric extracts contains all objects in OSM relations. It usually contains ferry ways going far beyond bounding polygon...

**Comment by Framstag** [comment]
@vyskocil : So how can we help?

**Comment by vyskocil** [comment]
@Framstag as suggested I add the following code in Preprocess.cpp, line 765 to check latitude below the min of the geofabrik great-britain.poly : 
```
        if (entry.coord.GetLat() < 49.523) {
            progress.Info(std::string("*** node: ")+std::to_string(entry.id)+std::string("  lat: ")+std::to_string(entry.coord.GetLat())+std::string("  lon: ")+std::to_string(entry.coord.GetLon()));
        }
```
It displayed many nodes, then I checked one and @Karry was right, it belongs to a ferry route...
This mostly defeat the optimization I tried when searching for POI when there are several databases and when looking in the local area...

**Comment by Karry** [comment]
In Qt search module, I sort databases by distance (bounding box center I believe) and searching in nearest databases first. With this optimisation, nearest results are available first...

**Comment by vyskocil** [comment]
Thank you @Framstag and @Karry for the explanations and suggestions, so this is not a bug per se and I will close the issue.
