### ISSUE TITLE
What about make Qt 6 the default in CMakelists.txt?

### ISSUE THREAD

**Issue by playgithub** [Framstag/libosmscout#1455]

**Comment by vyskocil** [comment]
Due to license changes, it seems there is no "free"  license for Qt 6 vs Qt 5, then I think it's not a good idea to make it the default

**Comment by vyskocil** [comment]
The last version I installed was Qt 5.9.1 and still use it only for testing. Now I couldn't find were to download current binary version, there are warning pages about the license en then I could only find source release...

**Comment by playgithub** [comment]
Add-ons available under Commercial Licenses, or GNU General Public License v3
others are under LPGL3

#### Qt5

From https://doc.qt.io/qt-5/qtmodules.html

* Qt Charts
* Qt Data Visualization
* Qt Lottie Animation
* Qt Network Authorization
* Qt Virtual Keyboard
* Qt Wayland Compositor
* Qt for WebAssembly
* Qt Quick 3D
* Qt Quick WebGL

#### Qt6

From https://doc.qt.io/qt-6/qtmodules.html

* Qt Charts
* Qt CoAP
* Qt Data Visualization
* Qt Lottie Animation
* Qt MQTT
* Qt Network Authorization
* Qt Quick 3D
* Qt Quick 3D Physics
* Qt Quick Timeline
* Qt Wayland Compositor

**Comment by Karry** [comment]
It would be great to support both major versions in CMake. I don't care what is the default, if both versions will be supported. As I'm developing application for Sailfish OS, I need to support even old Qt 5.6 in library. With Qt6, the last thing that is not supported is navigation voice instructions, if I remember it correctly. But I don't test Qt6 build yet, just compile it in docker container. So, more things may be broken...
