### ISSUE TITLE
check_include_file_cxx absent in Sailfish

### ISSUE THREAD

**Issue by rinigus** [Framstag/libosmscout#146]
This is my bad - I should have checked earlier. Sorry for that.

cmake in SFOS is 2.8.11.2 and it seem to miss check_include_file_cxx . So, the following line breaks the compilation:

https://github.com/Framstag/libosmscout/blob/master/cmake/features.cmake#L59

I am not sure you should fix it in the upstream. Maybe we with @Karry should just patch the version that we compile. Eventually, we can hope, SFOS cmake will catch up...

**Comment by Framstag** [comment]
Is there a known workaround?

**Comment by rinigus** [comment]
I replaced it with check_include_file() which failed for obvious reasons - not sure that this is what we want :)

**Comment by Framstag** [comment]
I used that first, it look like in this case it only checks in "C" mode and the header is not found. The only workaround would be to check the version of cmake and skip the test in a way that is equal to "header not found". Not nice, but if there is no workaround...

**Comment by rinigus** [comment]
Alternatively, we could add an option to cmake that can specify whether this header exists or not. If the option is given in the command line, the check is skipped. That would allow those who use older cmake avoid the problem and, eventually, it should go away

**Comment by Karry** [comment]
Or we can add `CheckIncludeFileCXX.cmake` file to our macro set (cmake subdirectory). It should work...

**Comment by Framstag** [comment]
No problem for me, if this does not result in problems for newer cmake version (order of macro search path?).

**Comment by Framstag** [comment]
Can this issue get closed?

**Comment by rinigus** [comment]
yes, you could close it. I don't have any problems with compilation on SFOS anymore and, as far as I could see, the sailfish branch that I use for compilation has no corresponding differences with your tree.
