### ISSUE TITLE
Bounding box and Speed

### ISSUE THREAD

**Issue by DerKleinePunk** [Framstag/libosmscout#1472]
Bounding box hit rate for file nodes.dat is only 0% (1/116)
What can I do to remove this Warning ?

https://github.com/DerKleinePunk/SDL2GuiHelper/blob/master/src/gui/GUIMapview.cpp

I use the Cario Renderer in my SDL2 Gui Project.
I works bust the Rendering is not so smooth i will using it on Raspberrry

**Comment by Framstag** [comment]
H @DerKleinePunk. I was in holiday, so sorry for the late answer.

The warning comes from DataFIle.h.

```
  bool DataFile<N>::GetByOffset(IteratorIn begin, IteratorIn end,
                                size_t size,
                                const GeoBox& boundingBox,
                                std::vector<ValueType>& data) const
```
it is called by

```
  bool Database::GetNodesByOffset(const std::vector<FileOffset>& offsets,
                                  const GeoBox& boundingBox,
                                  std::vector<NodeRef>& nodes) const
```

which again it is called by

```
  bool MapService::GetNodes(const AreaSearchParameter& parameter,
                            const TypeInfoSet& nodeTypes,
                            const GeoBox& boundingBox,
                            bool prefill,
                            const TileRef& tile) const
```

The method gets a number of file offset from the index together with a bounding box (which is likely the visible map area). The warning means that most of the offsets returned by the index are actually not in the given area. This means that the index is too unspecific. It finds objects that are later on filtered out. This may be a performance penalty if IO is slow and CPU is fast. It is a hint that for this special area, the index should have possibly been generated with other parameters. If the warning comes only sporadically I would ignore it, if it often happens you can play with the parameters, but you have to measure if the new parameters are actually better (e.g. index with different parameters might require more memory or more IO during index lookup).

The AreaNodeIndex Generator has the following parameters:

```
  MagnificationLevel           areaNodeGridMag;          //<! Magnification level for the index grid
  uint16_t                     areaNodeSimpleListLimit;  //<! If a type has less entries, we just store them plain
  uint16_t                     areaNodeTileListLimit;    //<! If a type has less entries in a tile, we store it as list
  uint16_t                     areaNodeTileListCoordLimit;//<! If a type has less entries we store the coord in tile lists
  MagnificationLevel           areaNodeBitmapMaxMag;      //<! Maximum Magnification level for bitmap index
  uint16_t                     areaNodeBitmapLimit;       //<! All cells must have less entries for a given zoom level
```

with the following default values:

```
      areaNodeGridMag(14),
      areaNodeSimpleListLimit(500),
      areaNodeTileListLimit(100),
      areaNodeTileListCoordLimit(1000),
      areaNodeBitmapMaxMag(20),
      areaNodeBitmapLimit(20),
```

I would either start with increasing the GridMag to 15 or decrease the list limits by factor 2? I assume that the index file size will increase.

**Comment by DerKleinePunk** [comment]
I hope you Holiday are good.
Thanks I will Test it and Report.

**Comment by Framstag** [comment]
I'm closing the issue. A possible solution was provided.
