### ISSUE TITLE
Rendering way of type "_route" is masked by bridges

### ISSUE THREAD

**Issue by vvyskocil** [Framstag/libosmscout#1478]
I don't know if it is a error in the usage of the library on my side or a issue in the lib ?

![Screenshot 2023-08-06 at 11 43 11](https://github.com/Framstag/libosmscout/assets/125963119/ca254f50-7864-4e5e-bacb-a2d90e1a6893)

**Comment by Framstag** [comment]
Strange:

In the standard configuration (standard.oss) in include/route.oss you can find:

```
OSS

CONST
  COLOR routeColor = #ff000088;

STYLE
  [MAG world-] {
    [TYPE _route] WAY {color: @routeColor; displayWidth: 1.5mm; width: 6m; priority: 100; }
  }

END
```

Important is the `priority: 100`. This sets WayData.priority. See also OSS.atg/WAYGROUP where Waydata.wayPriority is set.

See also `MapPainter::WayData::operator<`

Which should result in the route being the last entry in the way render list, thus rendering on top of everything else. Looking at the code however it seems like the way needs to have a "high" layer value for this, too, to be rendered after "lower" layers like bridges.

In the Qt code the initialisation for the route is done in OverlayObject.cpp/OverlayWay::toWay (and functions called from there).

In the header you see that Overlay objects have

```
  int8_t                              layer{std::numeric_limits<int8_t>::max()};
```

:-)

I assume some of these internal "tricks" are missing in your code?

**Comment by Framstag** [comment]
@Karry : Right?

We also have zIndex. I do not remember the purpose of this one. Karry, can you help? We should also document it ;-)

**Comment by Karry** [comment]
Just see ["Section ORDER WAYS" in our documentation](https://libosmscout.sourceforge.net/documentation/stylesheet/)

> This section defines in which order ways are rendered. It defines a number groups which contains ways types. Ways types in the same group have the same rendering priority. Groups further down the style sheet are rendered below ways further up in the GROUP list. Rendering order is only relevant if ways of different types cross each other. Note that ways are first ordered by layer, then within a layer by rendering priority. So a bridge will always be rendered on top a “bridged” way, a tunnel always below a “tunneled” ways.

And yes, in Qt, I just setup layer to maximum for "overlay" objects.

Regarding zIndex, it is really missing in documentation. Looking to stylesheets, it seems to me that it is used just for way decorations - to render outlines first. With that, I would guess that zIndex is used as last property for sorting (just order individual lines for the same way), but looking to the code, sorting order is: layer, zIndex, style priority, style sheet priority (ORDER WAYS). Should we change it?

**Comment by vyskocil** [comment]
Thank you @Framstag and @Karry for the hints, I checked all this in my code, tried to use the standard.oss stylesheet from the distribution but the rendering is still the same...
Maybe the issue is in the code I use to inject the  `_route` path ? 

```
       std::vector<RenderSteps> renderSteps {
            FirstStep, DrawAreas, DrawWays, DrawHillShading, DrawLabels, LastStep
        };
        
        unsigned long lastMapIndex = ctx->mapServices.size() - 1;
        
        for (int step = 0; step < renderSteps.size()/2; step++) {
            
            RenderSteps startRenderStep = renderSteps[step*2];
            RenderSteps endRenderStep = renderSteps[step*2 + 1];
            
            // render the active maps
            for(int i = 0; i <= lastMapIndex; i++){
...
                // Append the routeWay data in the last rendered database to paint it on top
                if (i == lastMapIndex && step == 0 && routeWay) {
                    TypeInfoRef type=ctx->databases[i]->GetTypeConfig()->GetTypeInfo("_route");
                                        
                    osmscout::FeatureValueBuffer features;
                    size_t featureIndex;
                    features.SetType(type);
                    if (type->GetFeature(osmscout::LayerFeature::NAME,
                                         featureIndex)) {
                        auto* value=dynamic_cast<osmscout::LayerFeatureValue*>(features.AllocateValue(featureIndex));
                        assert(value);
                        value->SetLayer(std::numeric_limits<int8_t>::max());
                    }
                    
                    if (type){
                        if(routeWay){
                            if (!routeWay->GetType()) {
                                routeWay->SetType(type);
                            }
                            ctx->datas[i].ways.push_back(routeWay);
                        }
                      }
...
```

**Comment by Karry** [comment]
I am missing `routeWay->SetFeatures(features);` in your snippet

**Comment by vyskocil** [comment]
Thank you @Karry, this is the solution !
