### ISSUE TITLE
Question regarding RoutingDatabase::GetRouteNodes()

### ISSUE THREAD

**Issue by frank-aurich** [Framstag/libosmscout#1502]
Hi,

I have a question regarding the function `RoutingDatabase::GetRouteNodes()`.
The function expects a start and end iterator for node IDs, a size value stating the number of nodes, and a `vector` (or `unordered_map`) for the results.

I wanted to use the function to determine *all* RouteNodes of a way, by passing the proper iterators `way->nodes.cbegin()`/`way->nodes.cend()`.
But I discovered, that the function returns as soon as there's a node that is not a `RouteNote`:
https://github.com/Framstag/libosmscout/blob/master/libosmscout/include/osmscout/routing/RouteNodeDataFile.h#L121

I'd like to know: Is that behavior by design? What purpose are the passing of iterators, if one won't be able to query all RouteNodes of the input list?

**Comment by Framstag** [comment]
See implementation in RouteNodeDataFile.h The code expect the ids to get resolved sucessfully, else loop will stop. So your analysis is correct. This method is (indirectly) called from the routing engine, where we are safe that the routing graph only contains correct routing ids (See RouteNode, which besides other attributes has a list of paths that end in a new route node). These are optimized mass operations. If you want to check, if a node is a route node you have to call GetRouteNode and check the result. See for example bool AbstractRoutingService<RoutingState>::GetWayStartNodes(...)

**Comment by frank-aurich** [comment]
Thanks for the explanation. Using `GetRouteNode()` on single nodes will suffice.
