### ISSUE TITLE
Limit max. cost of routing calculation

### ISSUE THREAD

**Issue by Framstag** [Framstag/libosmscout#157]
If there is no route between the start and the target, the router does not limit the length fo the resulting route effectively searching for a very long time for alternative routes (in fcat as long as new route nodes can be found, which can take *very* long to finish). We should allow to limit the length of the route to drop certain nodes early.

It makes sense to not pass a length but a factor ("do not try to find a rout that is longer than 5x the direct distance").

**Comment by rinigus** [comment]
That would create problems in cases where you want to go from Sweden Helsingborg to Helsingør by bridge (not the most clever thing to do, but there might be cases where there is just no bridge or ferry). If we have a river with no bridges nearby, 5x distance can be easily surpassed. 

See http://www.openstreetmap.org/node/26804505#map=10/55.7974/13.0367

I guess, we may have to take into account how many roads are in between the points nearby... i.e. whether we can treat the problem as 2D or its effectively has been reduced by some major obstacle, such as a river. Have to think about it and maybe we could find some correction of 5x for these cases.

**Comment by Framstag** [comment]
I will not hard code a factor of 5, but will allow the app to pass a value ;-) This way, if the routing fails, the user can either be ask "Should I try harder?" or "Do you want to correct your route definition".

**Comment by Framstag** [comment]
I have now added costLimitFactor to the routing profile. The Routing demo application will output the minimum cost (profile.GetCosts(distance)), the actual cost and the maximum costs. Currently the factor is 5.0. I have no problem to increase or decrease the factor based on experience. The factor should though not include all corner cases but a reasonable default for the 98% cases. If we set the factor too high it will result in the router searching for ever for a route that does not exist.

Note that I also did some API improvements. So you have to fix your code.

**Comment by rinigus** [comment]
I hope that you get notifications for closed issues as well.

While sleeping on it, I suggest to add one more parameter: costLimitOffset. That parameter would correspond to minimal distance that we don't care about. For example, it could be set 10-50 km, i.e. distance that does not impact performance too much. However, that would help us to resolve the issue of crossing a river. While distance across the river could be just few meters, distance to the bridge maybe few km. At present, I would have to set CostLimitFactor to x100 or more. By just having an offset, we avoid this problem.

So, instead of proportional we would make the relationship 

```
costLimit=overallCost*profile.GetCostLimitFactor();
```

into linear:

```
costLimit=overallCost*profile.GetCostLimitFactor() + profile.GetCosts(costLimitOffset);
```

What do you think?

**Comment by Framstag** [comment]
I would suggest - if you do not mind - that you simply test it. It sounds reasonable, but I do not have enough actual data to make a final judgment. If it works out OK, I do not have a problem integrating it.

**Comment by rinigus** [comment]
Sure! I'll look into it.

**Comment by rinigus** [comment]
Its too easy to find the cases that don't work (see attached screenshot). The corresponding command for routing in Estonia is:

```
Demos/Routing --car ../../map/estonia 58.36709 26.747487 58.356263 26.750416
```

By adding an offset corresponding to 10km already solves the problem:

```
costLimit=overallCost*profile.GetCostLimitFactor() + profile.GetCosts(10);
```

So, I guess we should add an offset and relate it to the maximal distance between bridges. I think we should try to estimate what's the distance that will not affect the calculations too much, but would allow to avoid breakage in calculations. For me, 100 km radius was never a problem in calculations - they were rather fast. So, having offset of 100km would not be an issue in terms of hanging calculations.

I am planning to expose the offset together with the costFactor in the server as settings. Just would be great to have agreed on API before implementing it.

![screenshot-16-11-14-09-19-08](https://cloud.githubusercontent.com/assets/15706605/20256405/0946ba1c-aa4c-11e6-9310-0cebb1d80248.png)

**Comment by Framstag** [comment]
I have now added a SetCostLimitDistance() method and attribute.

**Comment by rinigus** [comment]
Thank you very much! I looked through the patch, and it seems that you used in one place "Offset" instead of the Distance. I'd suggest to make it all either offset or distance.

Offset is used through `virtual double GetCostLimitOffset()` . Distance is used as variable `costLimitDistance` and function `SetCostLimitDistance` name.

**Comment by Framstag** [comment]
Fixed.

**Comment by rinigus** [comment]
Thank you! I'll expose these settings in server through URL and default configuration values. Then, I believe, large fraction of routing problematic cases are fixed in a very sensible way.

Thank you again,

rinigus
