### ISSUE TITLE
Move to Catch2 V3

### ISSUE THREAD

**Issue by Framstag** [Framstag/libosmscout#1608]
See https://github.com/catchorg/Catch2?tab=readme-ov-file#catch2-v3-has-been-released and https://github.com/catchorg/Catch2/blob/devel/docs/migrate-v2-to-v3.md#top

V3 promises decreased compile times, which IMHO is the main paint point of Catch2 (and possible a minor reason why we do not have much more tests ;-)).

IMHO the easiest way would be to assume that Catch V3 exists as an external library, installed by some package.

This is alt least true for
* Arch Linuxc, see https://archlinux.org/packages/extra/x86_64/catch2/
* Ubuntu noble: https://packages.ubuntu.com/noble/catch2 (but not the older version)
* MinGW/MSys2: https://packages.msys2.org/packages/mingw-w64-x86_64-catch?repo=mingw64
* Brew: https://formulae.brew.sh/formula/catch2#default
* vcpkg: https://vcpkg.io/en/package/catch2

That would suggest to check for the library during builds, and drop building tests, if the library is not available

Alternative would be to build the library itself locally during compilation...

@Karry @janbar  I suggest the first approach, any comments?

**Comment by janbar** [comment]
No comments, the first approach is the most portable.

**Comment by Karry** [comment]
Catch2 is header only (version that we are using) and we are [distributing](https://github.com/Framstag/libosmscout/blob/master/Tests/include/catch.hpp) it now, right? Looking to recent version, it is not header only anymore...?

So I would rather use packages from the system and sacrifice tests on older distributions...

**Comment by Framstag** [comment]
Right. I already started working on this. Compile time is a huge difference (much faster). I'll likely will do further cleanup, too. Stay tuned...
