### ISSUE TITLE
build error， error LNK2019: unresolved external symbol

### ISSUE THREAD

**Issue by ChenmyBBQ** [Framstag/libosmscout#1624]
When I use cmake, I get the following error:
12>InstalledVoicesModel.cpp
12>   Creating library F:/libosmscout/build/libosmscout-client-qt/Debug/osmscout_client_qtd.lib and object F:/libosmscout/build/libosmscout-client-qt/Debug/osmscout_client_qtd.exp
12>LocationInfoModel.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: class osmscout::ObjectFileRef __cdecl osmscout::Place::GetObjectW(void)const " (__imp_?GetObjectW@Place@osmscout@@QEBA?AVObjectFileRef@2@XZ) referenced in function "private: void __cdecl osmscout::LocationInfoModel::addToModel(class QString,class std::shared_ptr<class osmscout::LocationAtPlaceDescription>,class QList<class std::shared_ptr<struct osmscout::AdminRegionInfo> >)" (?addToModel@LocationInfoModel@osmscout@@AEAAXVQString@@V?$shared_ptr@VLocationAtPlaceDescription@osmscout@@@std@@V?$QList@V?$shared_ptr@UAdminRegionInfo@osmscout@@@std@@@@@Z)
12>F:\libosmscout\build\libosmscout-client-qt\Debug\osmscout_client_qtd.dll : fatal error LNK1120: 1 unresolved externals
12>Done building project "OSMScoutClientQt.vcxproj" -- FAILED.

I opened the source code of the software and located the cause of the problem, but I don't know why, how to solve it:
<img width="1280" alt="Snipaste_2024-11-16_22-39-44" src="https://github.com/user-attachments/assets/f1ec360e-1527-45d9-82dd-ad314db43be2">

 Here's my cmake file，I only added the qt6 environment inside the cmake file。
[CMakeLists.txt](https://github.com/user-attachments/files/17786730/CMakeLists.txt)

For other dependencies, I'm using vcpkg for installation：
{
  "name": "libosmscout",
  "version-string": "1.1.0",
  "builtin-baseline": "f6a5d4e8eb7476b8d7fc12a56dff300c1c986131",
  "dependencies": [
    "catch2",
    "zlib",
    "libiconv",
    "libxml2",
    "protobuf",
    "cairo",
    "pango",
    "opengl",
    "freeglut",
    "glm",
    "glew",
    "glfw3"
  ]
}

**Comment by Framstag** [comment]
Somehow in the code a Windows include sneeks in. Windows defines an alias for GetObject using the C++ preprocessor. This converts the GetObject into an GetObjectW method, which in turn is not found and thus cannot be linked.

Please test https://github.com/Framstag/libosmscout/pull/1626

**Comment by Framstag** [comment]
@ChenmyBBQ, can you check and comment?

**Comment by ChenmyBBQ** [comment]
> @ChenmyBBQ, can you check and comment?

Yes, I checked it, and the compilation passed, thank you very much。
I want to run a demo written in qt, but the form never pops up. Do the project being studied.
