### ISSUE TITLE
libosmscout-gpx CMake typo

### ISSUE THREAD

**Issue by Dizzy55** [Framstag/libosmscout#1627]
In [this commit](https://github.com/Framstag/libosmscout/commit/9e3503360b20cf04f853249f409582380fa7c179) you replace osmscout include name with the correct one

Looks like you forgot to do this for libosmscout-gpx/CMakeLists.txt file. [This line](https://github.com/Framstag/libosmscout/blob/01c7a2b4e0440ce27e61f9259dccdcccf72f8b32/libosmscout-gpx/CMakeLists.txt#L68)

**Comment by Dizzy55** [comment]
Sure. Can I close issue?

**Comment by Framstag** [comment]
I'll close for you, thanks for creating the issue!
