### ISSUE TITLE
Copy-paste error in the main CMakeLists.txt

### ISSUE THREAD

**Issue by Dizzy55** [Framstag/libosmscout#1628]
Hi,

There are two if with the same condition. Looks like a copy error
```
if(OSMSCOUT_BUILD_MAP_QT)
  if(OSMSCOUT_BUILD_MAP_QT)
    add_subdirectory(libosmscout-map-qt)
  endif()
endif()
```
[This line](https://github.com/Framstag/libosmscout/blob/fced8df0d8012ba696e4a83f3c51716e08c7a154/CMakeLists.txt#L348)

**Comment by Dizzy55** [comment]
The fix looks good))) Can I close the issue?

**Comment by Framstag** [comment]
I'll close for you, thanks for creating the issue!
