### ISSUE TITLE
Importing large files is not working (Windows)

### ISSUE THREAD

**Issue by OgreTransporter** [Framstag/libosmscout#168]
I tried to import germany-latest.osm.pbf (2.85 GB) but the import tool always claimed that this file does not exist. When debugging, it has come out that under Windows the function stat (osmscout :: ExistsInFilesystem) does not work with such large files.

**Comment by OgreTransporter** [comment]
#169

**Comment by Framstag** [comment]
As this is solved, I'm closing it.
