### ISSUE TITLE
iOS build error

### ISSUE THREAD

**Issue by mstar0125** [Framstag/libosmscout#18]
Hi, Thanks for your great project.

I am going to test your demo project in iOS but have lots of issues that I couldn't solve myself.
After I manually install dependent libraries on Mac OSX, I tried to open and build OSMScoutiOS Xcode project.
I notice that there are two missing files  marisa.h and TypeSet.h, but can solve this by copying files.

The critical issues are happening in OSMScout.mm

mapPainter = new osmscout::MapPainterIOS(styleConfig);

This line says the `no matching constructor for initialisation` and show 9 errors. 

Can you help me to solve this issue?

Or if you have any iOS building guide, it would be helpful.

Thanks in Advance

**Comment by Framstag** [comment]
I cannot directly help, since I do not have a Mac. I though contacted the original author of the code for help.

**Comment by mstar0125** [comment]
Thanks anyway, Tim

How can I contact iOS developer?

**Comment by Karry** [comment]
Hi. I don't have access to Mac too. But it would be great to have possibility 
to compile iOS library on Linux (or other free platform). It is possible 
to prepare virtual machine or Docker image that includes requiered tools and 
libraries? (Foundation, Cocoa, AppKit, CoreData, ...?)

Author of iOS renderer is Vladimir Vyskocil <vladimir.vyskocil@gmail.com>

https://github.com/Framstag/libosmscout/blob/master/libosmscout-map-iOSX/
AUTHORS

Lukas

Dne čtvrtek 9. června 2016 0:11:33 CEST MStar napsal(a):
> Thanks anyway, Tim
> 
> How can I contact iOS developer?
>

**Comment by mstar0125** [comment]
Thanks, Lukas

I think it needs Mac OSX Guide because it's targeting iOS and OSX. 
I hope Vladimir can help me to figure out this issue.

And do you have any idea why marisa.h and TypeSet.h files are missing in the last commit?

**Comment by mstar0125** [comment]
I can finally build libosmscout library in my iOS simulator
![screen shot 2016-06-10 at 11 22 20 am](https://cloud.githubusercontent.com/assets/5414823/15953632/ab4a783a-2eff-11e6-9a01-a49d006d0885.png)

**Comment by Framstag** [comment]
Thanks also to Vladimir! I will close the bug in result.

Regarding the marisa.h. This header is part of the marisa library. It should be supplied by a marisa installation itself. The path to the header however should be part of the compiler search path for includes.
Under Linux:

```
[tim:~] $ locate marisa.h
/usr/include/marisa.h
```

**Comment by ayeteng** [comment]
Hi mstar0125,

Would you have any record on how you build the application for iOS? I try to build from source but encounter many issues.
