### ISSUE TITLE
Building libosmscout-map-directx failed with cmake vs2015 on windows 7

### ISSUE THREAD

**Issue by DerKleinePunk** [Framstag/libosmscout#184]
"D:\Mine\OpenSource\libosmscout-own\build\ALL_BUILD.vcxproj" (Standardziel) (1)
 ->
"D:\Mine\OpenSource\libosmscout-own\build\Demos\DrawMapDirectX.vcxproj" (Standa
rdziel) (7) ->
"D:\Mine\OpenSource\libosmscout-own\build\libosmscout-map-directx\osmscout_map_
directx.vcxproj" (Standardziel) (9) ->
(ClCompile Ziel) ->
  C:\Program Files (x86)\Windows Kits\10\Include\10.0.10586.0\um\Wincodec.h(813
0): error C2061: syntax error: identifier 'DXGI_JPEG_AC_HUFFMAN_TABLE' [D:\Mine
\OpenSource\libosmscout-own\build\libosmscout-map-directx\osmscout_map_directx.
vcxproj]

**Comment by DerKleinePunk** [comment]
when i change targetplattfrom in the solution it builds. I don't is this an isscue aon my machine or an ms problem. The problem is when the target plattform is set to 8.1 (default) the compiler mix header between 8.1 and 10

**Comment by OgreTransporter** [comment]
Yes, it is also possible to get linking errors when libs and headers are from different SDKs. If you use multiple SDKs check the CMake variables Direct2D_D2D1_LIBRARY, Direct2D_DWRITE_LIBRARY and Direct2D_INCLUDE_DIRS to be part of the same SDK.

In your case:
Direct2D_D2D1_LIBRARY:FILEPATH=C:\Program Files (x86)\Windows Kits\10\Lib\10.0.10586.0\um\x86\d2d1.lib
Direct2D_DWRITE_LIBRARY:FILEPATH=C:\Program Files (x86)\Windows Kits\10\Lib\10.0.10586.0\um\x86\dwrite.lib
Direct2D_INCLUDE_DIRS:PATH=C:\Program Files (x86)\Windows Kits\10\Include\10.0.10586.0\um

**Comment by Framstag** [comment]
OK. So, is there something we need to change/fix or can the issue be closed?

**Comment by OgreTransporter** [comment]
It should be possible to fix it by updating FindDirect2D.cmake. Depending on Direct2D_INCLUDE_DIRS the variable Direct2D_LIBRARY_PATHS has to be set. I have to think about it.

**Comment by Framstag** [comment]
Sorry to ask, but what is the status?

**Comment by DerKleinePunk** [comment]
https://cmake.org/Bug/view.php?id=15670
cmake -G "Visual Studio 14 2015" -DCMAKE_SYSTEM_VERSION=10.0.##### ..
use the lastes plattform target and i can complier without error. but lot of warnings.
i not Tested the output and the moment because i don't found an test app for DirectX renderer

**Comment by Framstag** [comment]
Most warnings come from not exactly matching datatypes and thus resulting implicit conversions. This should be fixed step by step over time but is no sign of "is broken" IMHO. There are some more interesting warnings that require a closer look because e.g. there is a conversion from integral to double or vice versa. Of course I accept patches - as long as they do not introduce warnings under other platforms ;-)

There is DrawMapDirectX.cpp under demos. Have not tested it though.

**Comment by Framstag** [comment]
The cmake build work in the central builds and the VisualStudio 2017 build using directly the project files also worked. Is this still an issue?

**Comment by DerKleinePunk** [comment]
mkdir build
cd build
cmake .. -G "Visual Studio 14 2015" -DCMAKE_SYSTEM_VERSION=10.0.10586.0 -DCMAKE_INSTALL_PREFIX=D:\Mine\OpenSource\osmlib
cmake --build . --config Release --target install

Make start able installation on D:\Mine\OpenSource\osmlib

It is possible to write this Information on http://libosmscout.sourceforge.net/documentation/source/ ?

Build the found thinks with no error but lot of warnings. I thing it is an problem on my machine with more that one Visual Studio on it, MS mixes the SDK Libaries. The 2017 Solution can't test on my machine.

At the moment i have no Windows importer and no database on this machine to test more.
on my fork in brach build_with_vs2015 i try to build other dependencies of this library but i am not ready jet. I need the cairo render for my project but at moment the raspberrry PI version of my project is more important for me.

**Comment by Framstag** [comment]
Pushed small addition to the online documentation as suggested.
