### ISSUE TITLE
Allow a vertical offset for line labels

### ISSUE THREAD

**Issue by vyskocil** [Framstag/libosmscout#193]
In some cases the map would be prettier if we could use a vertical offset for some thin line labels for example the name of a maritime route, a water stream,... We should offset these labels to be drawn above or under the lines instead of overlapping them.

**Comment by vyskocil** [comment]
Here is a sample of the actual rendering 

![img_0440](https://cloud.githubusercontent.com/assets/452704/21609653/ce6aded8-d1aa-11e6-8a41-7c4a900184d5.JPG)

**Comment by Karry** [comment]
It is possible already. See `displayOffset`, it is used for steps in `standard.oss` for example:

```
   [TYPE highway_steps,
         highway_via_ferrata_easy,
         highway_via_ferrata_moderate,
         highway_via_ferrata_difficult,
         highway_via_ferrata_extreme] WAY.TEXT { displayOffset: 2mm;}
```

**Comment by Framstag** [comment]
Please test. If this works for you, please close the bug :-)

**Comment by Karry** [comment]
...and create pull request for standard stylesheet :-)

**Comment by vyskocil** [comment]
I tested it and it works. I missed the point that displayOffset could also be applied to WAY.TEXT
The only drawback I found is that the offset sign (above or below the line) depend of the line orientation but I've no idea yet how to fix that point.

**Comment by vyskocil** [comment]
This could be closed
