### ISSUE TITLE
Qt: contour labels with bi-directional text are rendered incorrectly

### ISSUE THREAD

**Issue by Karry** [Framstag/libosmscout#196]
This example is right-to-left (Hebrew?) label, it should be fixed by https://github.com/Framstag/libosmscout/pull/194 Top part is osmscout, bottom is Mapnik... (somewhere in Israel) Can be labels in OSM bi-directional?

![bad-right-to-left-labels](https://cloud.githubusercontent.com/assets/309458/21628631/317f99d4-d221-11e6-8c12-71680530ef41.png)

Bidirectional text rules are complicated, we should use some library function for render labels correctly. Node labels should be rendered correctly (QPainter should support it), QPainter source code may provide some hints howto implement it: https://gitlab.com/pteam/korvins-qtbase/blob/a718a99438aaca7d4cd4379726a8e131d3c4bf89/src/gui/painting/qpainter.cpp#L5825

**Comment by Framstag** [comment]
I urge to make sure that the rendering backend text engine (Pango, Qt,...) should handle this. For complex paragraph rendering the text engine must know if a part is left-to-right or right-to-left. If we handle as bounding box to engine should just fo "the right thing". Important for this is that we handle text always a (one line) paragraph and not as a sequence of single characters.

**Comment by Karry** [comment]
Hi Tim. I agree, complexity of non-latin text rendering can be crazy, this is not something that we (at least I) want to solve :-) But when you write that we should not handle it character by character, how do you want to solve contour labels? You certainly know that Qt don't have API for text rendering around curve. I browse Qt documentation and source code and can't found easy way how to do it correctly with public Qt API. `QTextEngine::bidiReorder` is something what we need to use, but `QTextEngine` is private API :-( 

`QTextLayout::glyphRuns` may be used for it, but this note is scary:
> This is an expensive function, and should not be called in a time sensitive context.
Should I create benchmark / test demo code for that?

**Comment by Karry** [comment]
Side question: how many labels in OSM data uses bi-direction text? We are rendering righ-to-left street names incorrectly and noone reported that. I suggest to add simple support for "all righ-to-left" labels and keep this issue open to signalize that we know about this problem...

**Comment by Framstag** [comment]
Regarding your first question: Yes, the Qt backend is already doing it in a way that is likely not handling things correctly. I assumed though that for deciding if I render a contour label I do not need the width of the individual characters. if the text hast a length of 20 pixels and there is a curve for the next 20 pixels I will drop the text at this position completely. That we still do it wrong in the other part should not force us to make it even more broken (see "broken windows effect") ;-) And if it is cheaper so the better.

Side question: I think I read on one of the mailing list that in some countries this is done. I would suggest at belgium where street sign contains names in multiple languages - though in belgium this will not result in bi-directional text ;-) Possibly this is done in other countrries, too.  But we should better aks some internationally working mapper.
