### ISSUE TITLE
Issue while building libosmscout-binding using CMAKE

### ISSUE THREAD

**Issue by kkscwcd** [Framstag/libosmscout#199]
Hi 
I installed all the dependency in Ubuntu 16.04 and using Swig 3.0.11 but getting this below error i tried everything but this error is not resolved

/home/kundan/libosmscout/libosmscout-binding/libosmscout-binding/Java/src/main/java/net/sf/libosmscout/osmscout/libosmscoutJAVA_wrap.cxx:14135:3: error: ‘GeoCoord’ was not declared in this scope
   GeoCoord *arg2 = 0 ;
   ^~~~~~~~
/home/kundan/libosmscout/libosmscout-binding/libosmscout-binding/Java/src/main/java/net/sf/libosmscout/osmscout/libosmscoutJAVA_wrap.cxx:14135:3: note: suggested alternative:
In file included from /home/kundan/libosmscout/libosmscout-binding/libosmscout-binding/Java/src/main/java/net/sf/libosmscout/osmscout/libosmscoutJAVA_wrap.cxx:323:0:
/home/kundan/libosmscout/libosmscout/include/osmscout/GeoCoord.h:63:23: note:   ‘osmscout::GeoCoord’
   struct OSMSCOUT_API GeoCoord CLASS_FINAL
                       ^~~~~~~~
/home/kundan/libosmscout/libosmscout-binding/libosmscout-binding/Java/src/main/java/net/sf/libosmscout/osmscout/libosmscoutJAVA_wrap.cxx:14135:13: error: ‘arg2’ was not declared in this scope
   GeoCoord *arg2 = 0 ;

Please help me in this, any help will appreciated .

Thanks,

**Comment by Framstag** [comment]
I can reproduce this locally and will now take a look. Sorry for this problem. There is no central build for libosmscout-binding so it tends to broken more often than it should.

**Comment by Framstag** [comment]
You have to add

```
#define CLASS_FINAL
```
 to libosmcout.i

I have pushed this change to the github repository. The autoconf based build works for me, the cmake based build should work, too.

**Comment by kkscwcd** [comment]
Thanks Friend , I am testing it and let you know. I will download latest from the github and and let you know

**Comment by kkscwcd** [comment]
Hi,
Still a new issue is coming .

CXX      libosmscoutjava_la-libosmscout.lo
libosmscout.cpp:310:28: fatal error: osmscout/Types.h: No such file or directory
 #include <osmscout/Types.h>
                            ^
compilation terminated.
Makefile:453: recipe for target 'libosmscoutjava_la-libosmscout.lo' failed
make[2]: *** [libosmscoutjava_la-libosmscout.lo] Error 1
make[2]: Leaving directory '/home/kundan/libosmscout/libosmscout-binding/src/java'
Makefile:367: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/kundan/libosmscout/libosmscout-binding/src'
Makefile:398: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

Please check this or it is possible you can share the libosmscount-binding complete project so it's build i have the library and the generated java file so i will use it in my re-search project .

**Comment by Framstag** [comment]
I'm not able to test the cmake based build of libosmsocut-binding. The cmake build file does not enable this part of the project for building :-/

The autoconf based build works on my system.

It starts swig as this:

```
/usr/bin/swig -c++ -java -cppext cpp -I../../../libosmscout/include -package net.sf.libosmscout.osmscout -outdir ../../src/java/net/sf/libosmscout/osmscout -o ../../src/java/libosmscout.cpp osmscout/libosmscout.i
```

It is possible that the cmake build is missing the search path to the ../libosmscout/include for the c++ build of libosmscout.cpp directory?

**Comment by kkscwcd** [comment]
I tried autoconf based build, It is failing too. Let me try this one for swing part. 

can you please share libosmscoutjava dll file so i can load in my Java application. I will try to generate the java wrapper using swig command you suggested .

my email id is- kkscwcd@gmail.com

Thanks,

**Comment by Karry** [comment]
Both are strange. Tim, do you try to enabled java build explicitly? It is possible that you have dirty cmake cache...
`cmake -DOSMSCOUT_BUILD_BINDING_JAVA=ON  ..`

CMake build works fine for me. Docker build in Ubuntu 16.10 image with Java works too.
```
cd ci/docker/
./ubuntu_16.10_gcc_cmake/build.sh
./ubuntu_16.10_gcc_cmake/run.sh https://github.com/Framstag/libosmscout.git master
```
It is ending with: `[100%] Linking CXX shared module libosmscout_binding_java.so`...

Here are builded libraries ([Ubuntu 16.10, x86_64](http://osmscout.karry.cz/tmp/libs.tar.gz)), but I want to know where is the problem.

**Comment by Framstag** [comment]
```
tim:~/projects/OSMScout/build] master(+50/-0,268)+* ± cmake -DOSMSCOUT_BUILD_BINDING_JAVA=ON ..
/usr/bin/ccache: invalid option -- 'd'
Usage:
    ccache [options]
    ccache compiler [compiler options]
    compiler [compiler options]          (via symbolic link)

Options:
    -c, --cleanup         delete old files and recalculate size counters
                          (normally not needed as this is done automatically)
    -C, --clear           clear the cache completely (except configuration)
    -F, --max-files=N     set maximum number of files in cache to N (use 0 for
                          no limit)
    -M, --max-size=SIZE   set maximum size of cache to SIZE (use 0 for no
                          limit); available suffixes: k, M, G, T (decimal) and
                          Ki, Mi, Gi, Ti (binary); default suffix: G
    -o, --set-config=K=V  set configuration key K to value V
    -p, --print-config    print current configuration options
    -s, --show-stats      show statistics summary
    -z, --zero-stats      zero statistics counters

    -h, --help            print this help text
    -V, --version         print version and copyright information

See also <https://ccache.samba.org>.
-- Detected g++ 
-- Enabling GCC visibility flags
Skip DrawMapDirectX demo, libosmscout-map-directx is missing.
CMake Error at libosmscout-binding/CMakeLists.txt:6 (message):
  A JDK is required for java binding


-- libosmscout build configuration:
-- Shared libraries:                        ON
-- core library:                            ON
-- import library:                          ON
-- map drawing interface:                   ON
--  - Agg map drawing backend:              ON
--  - Cairo map drawing backend:            ON
--  - OpenGL map drawing backend:           ON
--  - DirectX map drawing backend:          OFF
--  - Qt map drawing backend:               ON
--  - SVG map drawing backend:              ON
--  - Map drawing backend for iOS and OS X: OFF
-- client libraries:
--  - Qt client library:                    ON
-- tools:
--  - Import:                               ON
--  - DumpData:                             ON
--  - OSMScout2:                            ON
--  - StyleEditor:                          ON
-- tests:                                   ON
-- demos:                                   ON
--  - heap profiler (Gperftools)            ON
-- bindings:
--  - Java binding:                         ON
--  - C# binding:                           OFF
-- external interfaces:
--  - MATLAB mex function:                  OFF
-- documentation:                           ON
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
/home/tim/projects/OSMScout/libosmscout-binding/JAVA_AWT_INCLUDE_PATH
   used as include directory in directory /home/tim/projects/OSMScout/libosmscout-binding
/home/tim/projects/OSMScout/libosmscout-binding/JAVA_INCLUDE_PATH
   used as include directory in directory /home/tim/projects/OSMScout/libosmscout-binding
   used as include directory in directory /home/tim/projects/OSMScout/libosmscout-binding
/home/tim/projects/OSMScout/libosmscout-binding/JAVA_INCLUDE_PATH2
   used as include directory in directory /home/tim/projects/OSMScout/libosmscout-binding
JAVA_AWT_LIBRARY (ADVANCED)
    linked by target "osmscout_binding_java" in directory /home/tim/projects/OSMScout/libosmscout-binding
    linked by target "osmscout_binding_java" in directory /home/tim/projects/OSMScout/libosmscout-binding
JAVA_JVM_LIBRARY (ADVANCED)
    linked by target "osmscout_binding_java" in directory /home/tim/projects/OSMScout/libosmscout-binding
    linked by target "osmscout_binding_java" in directory /home/tim/projects/OSMScout/libosmscout-binding

-- Configuring incomplete, errors occurred!
See also "/home/tim/projects/OSMScout/build/CMakeFiles/CMakeOutput.log".
See also "/home/tim/projects/OSMScout/build/CMakeFiles/CMakeError.log".
```

```
[tim:~/projects/OSMScout/build] master(+50/-0,268)+* 1 ± java -version
openjdk version "1.8.0_112"
OpenJDK Runtime Environment (build 1.8.0_112-b15)
OpenJDK 64-Bit Server VM (build 25.112-b15, mixed mode)
```
```
[tim:~/projects/OSMScout/build] master(+50/-0,268)+* ± echo $JAVA_HOME

```
How is Java detected? Is simply JAVA_HOME evaluated?

**Comment by Framstag** [comment]
Yes, setting JAVA_HOME enables the build of the libosmscout-binding.

**Comment by Framstag** [comment]
@kkscwcd: Are you sure you are using the github repository? The sourceforge repository holds an older version of the sources. It is possible that this fails. If not, both Lukas nor me can reproduce the problem. So we need further information:
* Which OS?
* Which distribution?
* Which compiler?
* Anything else, which might influence the build?

**Comment by kkscwcd** [comment]
Hi Guys,
Thanks for your awesome support. I completed the build successfully using cmake .

Thanks a lot. 

Cheers.

**Comment by kkscwcd** [comment]
Friend, 
I got in another issue now. How i will get the library for windows . I need the .dll file of library .

Please share if you have the library for windows. I need the dll for windows please share .

Thanks,

**Comment by Framstag** [comment]
Do you need a dll for libosmscout in general (that means, all of the libraries?) or especially libosmscout-binding?

You should be able to build a VisualStudio project file from the CMake project and then build the DLL from the VisualStudio project. I did however never tried this and it is possible that the CMake file has to be tweak for this to work. I see though that there is a check for MSVC so it should be work a try.

**Comment by kundankumar2294** [comment]
Ok So i have to prepare a windows environment and install visual studio and then it will generate the .dll 

Thanks for reply i will try and let you know if i got success .
