### ISSUE TITLE
Evaluate is_in tag in administrative_boundaries for building region hierachy

### ISSUE THREAD

**Issue by Framstag** [Framstag/libosmscout#202]
We currently use strict geometric "is in" evaluation for building the region tree. A child region belongs to a parent region simply because it is (mainly) contained by the parent. This is OK for simple regions with one area but does sometimes not work for more complex regions that consist of multiple areas which are also not close. See #191 for an concrete example.

To improve the region hierarchy we should also evaluate the ´is_in` attribute on administrative_boundaries and similar regions. For an example see https://www.openstreetmap.org/node/25293125. This example also shows that the content of this tag possibly has to get preprocessed and further validated for optimal use. In this case the complete region path is contained.

**Comment by Framstag** [comment]
Information is now available in Region class. GenLocationIndex currently does check the is_in tag value against real name of parent region and throws a warning of they do not match.

Findings:
* is_in is not much used in my test area
* In some cases the parent name is not correctly spelled or has some pre/postfix that results in a mismatch. These are IMHO mapping errors. This is rather rare.
* is_in parent is not the direct parent as detected by evaluation geometric containment. I'm unsure if these are mapping errors or if this shows that building the tree based solely on containment is wrong. We have to further look at the actual data :-/ POssibly this is only solvable by also evaluating issue #203.

**Comment by rinigus** [comment]
I will test it. So far, I have not seen any anomalies anymore after the commit related to https://github.com/Framstag/libosmscout/issues/191 . I had a question that I raised in that issue regarding rounding errors in the comparison. Should we treat all floating point comparisons as a source for errors and define some tolerance?

**Comment by rinigus** [comment]
I do get quite a few warnings in Estonia. Actually, we are having a reform where several counties are joining and that would probably make is_in very error-prone in Estonia.

To check few errors further, it would be great to get OSM ID, in addition to the libosmscout ID. Maybe we should at least keep OSM ID for testing purposes somewhere? Or is it there already?

**Comment by Framstag** [comment]
The code (besides the refactoring) doe snot change the generation of the index (yet). I added just additional checks against is_in spitting out warnings.

Regarding comparison of coordinates: I think there is no clear questions, it depends on what you want to archive. In cases where you want to compare coordinates for identity (have the same node as origin) you should compare serial and coordinate for exactness. In other cases a "softer" comparison might make more sense (containment,...). Note that libosmscout already strips some precision during import!

There are some debug indexes that allow to convert an libosmscout id back to an OSM id. The GenLocationIndex doe snot have the OSM id, but see ImportErrorReporter::FinishedImport() how this could get retrieved during report output.

**Comment by Framstag** [comment]
The question is, now that we see, that the is_in data is not perfect and possibly not accurate...(how) dow we use it? One way to reduce warnings: Instead of checking if the direct parent is identical with is_in, we could see if any parent up the hierarchy tree has the given is_in name. This however will not improve the index quality, it will just reduce the warnings.

**Comment by rinigus** [comment]
I would try to look into the warnings that I am getting in Estonia'n import tonight. So far, I haven't seen any errors and maybe we should try not to use is_in. Have you seen any case where it was advantageous recently, i.e. after the patch that you merged as a part of estonian village issue?

**Comment by Framstag** [comment]
No, I did not see an obvious advantage. It is just that is_in is authoritative as seen by the mapper, the "region hierarchy build by containment" is not based directly on mapping information it is "just" a guess.

For nordrhein-westfalen I see some situations, where libosmscout claimed the hierachy was

*A
** B
*** C
*** D

where the is_in information suggested that it could be

* A
** B
** C
** D

I however do not have any local information for that region so it could be that libosmcout is more accurate and the mapper was inexact or the other way round. That was the reason to request some feedback from somebody else that may have better information for "his" region.

**Comment by rinigus** [comment]
With extra comments (namely, region name), I could see that at least few of the import warnings were errors. For example:

 'Marinova küla' parent should be 'Meremäe vald' but is '<root>'

http://www.openstreetmap.org/relation/350749#map=14/57.7381/27.5401&layers=H

As you could see, its a village next to Russia. I guess, some coordinates were over the border. Taking into account that is_in is quite buggy in many other places, I think it could be solved by better "contains" strategy. Maybe we should not compare points on the border, but try to find % of the area that overlaps [or something similar]. Don't know how to do that, though... Some 2D scan on raster?

**Comment by rinigus** [comment]
Just to let you know: I am working on getting better area-in-area test that should help by resolving the area relationships better. If it works, it should allow us to keep is_in as a Warning message and not as a data that we have to parse.

**Comment by Framstag** [comment]
That sounds interesting. Note that I just added #234. Perhaps this is something that is also addressed by your potential pull request?

**Comment by rinigus** [comment]
At present, I am focused on getting it work correctly, optimize later :)

OK, it looks that I have found the way to get these area in area comparisons work. Right now I have a prototype that was tested on Estonia import. 

While looking on few is_in warnings (as the case above with 'Marinova küla'), I noticed that the border of the village was just slightly over the Estonian admin border in one of the nodes. So, I assumed that the errors were induced by imperfections in OSM data. In other words, small error on the border of admin area could through out the comparison and lead to incorrect imports. 

As before, issue is in improving `LocationIndexGenerator::AddRegion`.

To make an algorithm robust, I approached the problem as we see the map - through comparisons of areas. Idea is as follows: 

* for each area, I find "probe" points that are within this area. For that, I take a bounding box of the area subregion, through 10x10 raster on it and record all probe points that are within an area.

* when I test whether area possible_child is contained by possible_parent, I check whether  possible_child probe points are within possible_parent.

Result is - almost perfect import as tested by checking quite a few is_in warnings. Among ~100 warnings the only one which I found strange was from one village that was not in any county, but belonged to Estonia directly. All other warnings were induced by changes in counties and having an old county name in is_in tag. 

On Estonia, performance was quite good - would have to test it on something bigger. 

I will make now a proper implementation and if it all goes well, submit it as PR for further testing. It probably would take couple of nights to do that.

**Comment by rinigus** [comment]
... and the only case where the raster-generation approach failed was fixed by improving the precision of a checking function. So, the prototype managed to generate a perfect import when tested against is_in warnings.

**Comment by Framstag** [comment]
The inaccuracies led me to use a quorum for "in in" detection. If the majority of the area border nodes are in the possible parent region, than this a sign for inclusion. It looks like you further optimized this approach by not checking all points on the area border but only a few control points (make sure that this in principle will work for sand hour shaped areas and similar strange areas). The advantage of your approach is, that however big the area is, you still seem to a have a fix number of points!? This could result in major improvements for big areas.

This will however only work for "area in area" checks. The GenLocationIndex also needs to make use of "way in area" and "node in area" checks. Your approach will also not work for general "area shape in area shape" tests - but that is OK based on the fact that normally boundary region do not overlap.

I'm waiting for your code and first measurements :-)

**Comment by rinigus** [comment]
Morning!

Yes, this approach is going to work on area in area checks only. Don't count on major speed improvement (yet), my priority is first to get the location relationships right. And for that, is_in tag is perfect as it is - giving us warnings allowing to test and tune the algorithms.

As for performance: I still need to generate the raster points. This means that, for each area, the points have to be tested against its boundary leading to a set of "probe points". When testing for inclusion, I am testing whether the probe points of a proposed child are within the boundary of proposed parent. So, the bigger areas with big borders would still have to be tested with the probe points within these borders.

But I think that there are ways to optimize the speed significantly. Let's just make the data right first.

**Comment by rinigus** [comment]
I suggest to close this. Is_in is good for warnings, but current in area implementation should lead to better results.

**Comment by Framstag** [comment]
I see it similar
