### ISSUE TITLE
cmake FindCairo behaviour on msys2

### ISSUE THREAD

**Issue by aquiles2k** [Framstag/libosmscout#219]
Using cmake on win with msys2 to build libosmscout i run into a problem in the FindCairo.cmake script.

See http://stackoverflow.com/questions/41470256/cmake-file-command-prepends-other-path-to-provided-file-path

I replaced the script with the following version and cmake runs correctly. Perhaps we can replace it?

New Script:
http://code.metager.de/source/xref/freedesktop/poppler/cmake/modules/FindCairo.cmake

**Comment by Karry** [comment]
Hi, it seems that `FILE(READ ...)` is broken in cmake if it is working on unix filesystems only... New KDE variant use pkg-config for library lookup, it is prefered way, we should use it.

**Comment by Karry** [comment]
Please test current master branch if you are able to build it with msys2.

**Comment by aquiles2k** [comment]
Works, thanks :)
