### ISSUE TITLE
cmake debug postfix macos

### ISSUE THREAD

**Issue by aquiles2k** [Framstag/libosmscout#230]
Hi,
i believe general concensus for debug postfix on macos is "_debug". E.g. the qt libs do this.

Is it possible to change the CMakeLists.txt entry from

```
if(NOT APPLE)
  set(CMAKE_DEBUG_POSTFIX "d")
endif ()
```

to

```
if(NOT CMAKE_DEBUG_POSTFIX)
    if(APPLE)
        set(CMAKE_DEBUG_POSTFIX _debug)
    else()
        set(CMAKE_DEBUG_POSTFIX d)
    endif()
endif()
```

That way one can install both lib versions on the mac.

**Comment by Karry** [comment]
Hi. I have no problem with it :-)

**Comment by Framstag** [comment]
Pushed change.

**Comment by aquiles2k** [comment]
Thanks!
