### ISSUE TITLE
Performance degration after recent big area/way support

### ISSUE THREAD

**Issue by Framstag** [Framstag/libosmscout#234]
I see performance degrations after the recent change to support ways and areas with size >19 bit.

There are two likely reasons for this:
* The new read/write code is (much) slower then the older one
* We now load bigger boundaries and thus steps that make use of "area in area" or "point in area" comparisons are now slower since they have to compare against very big boundaries

The changes to the geofabrik exports - now making sure that relations are "complete" - may also result in more boundary relations required to compare against.

1.Verify what the real cause is (I assume option 2)
2. Find a way to compensate the performance loss

**Comment by Karry** [comment]
It is interesting. I don't see any degradation with Czech. What country are you trying, Germany?

**Comment by Karry** [comment]
Ah, I see. I am running France import right now. Step 21 is running 6 hours already. Here is few lines from `perf top`:
```
  42,23%  libosmscout_importd.so  [.] _ZNK8osmscout8GeoCoord6GetLatEv
  36,40%  libosmscout_importd.so  [.] _ZN8osmscout24GetRelationOfPointToAreaINS_8GeoCoordES1_EEiRKT_RKSt6vectorIT0_SaIS6_EE
  16,66%  libosmscout_importd.so  [.] _ZNKSt6vectorIN8osmscout8GeoCoordESaIS1_EEixEm
   4,59%  libosmscout_importd.so  [.] _ZNKSt6vectorIN8osmscout8GeoCoordESaIS1_EE4sizeEv
   0,03%  libosmscout_importd.so  [.] _ZN8osmscout21IsAreaSubOfAreaOrSameINS_8GeoCoordES1_EEbRKSt6vectorIT_SaIS3_EERKS2_IT0_SaIS8_EE
```

**Comment by Karry** [comment]
I think that second reason is correct. When I connect gdb to this process, it spends majority of its time in `LocationIndexGenerator::AddRegion`. I will wait for @rinigus , it seems that he already has some idea how to optimise it :-) I just try fast area box checking: https://github.com/karry-space-with-my-second-forks/libosmscout/commit/17e5a979eaa66124b25eb69c7903c258f4367419 I will see how much it will helps.

**Comment by rinigus** [comment]
Yes, please wait a little bit with optimizing the import. I have a feeling that the approach that I used gives excellent results (https://github.com/Framstag/libosmscout/issues/202) and, if needed, would require different ways to optimize the performance. 1-2 days and we can test it all on PR :)

**Comment by rinigus** [comment]
Should we close this as well?

**Comment by Framstag** [comment]
Yes
