### ISSUE TITLE
cmake largefile support

### ISSUE THREAD

**Issue by aquiles2k** [Framstag/libosmscout#242]
When building the Importer with cmake i get file errors on Importing larger maps. This also happens with 64bit binaries. Using the pkg-config toolchain the Importer works without any error.

So, since it has to do with files and we talked about it in the mailing list some time ago, i checked for the large file support and in cmake there seems to be none configured in contrast to pgk-config, which uses the 'AC_SYS_LARGEFILE' config option to set it.

I searched the net and found not to much information about it, but here is some example largefile cmake scripts, which might be adapted for us to help with the issue.

https://github.com/Benjamin-Dobell/Heimdall/blob/master/cmake/LargeFiles.cmake
https://github.com/uclouvain/openjpeg/blob/master/cmake/TestLargeFiles.cmake

**Comment by Framstag** [comment]
Te suggestion sounds reasonable. Could you offer a patch? It is strange that the other users are not reporting such problem, though they are using the cmake build, too. Do you have a special configuration (Windows,...)?

**Comment by aquiles2k** [comment]
Im on msys2 mingw cmake toolchain. I yet have to check if this helps with my problem since i got a working importer with the pkg-build and hadnt anymore time for more research. I just stumbled upon it and think it might be a good general addition.

I'll see if i can make PR ready, when i got some spare time.

**Comment by aquiles2k** [comment]
Pr https://github.com/Framstag/libosmscout/pull/251 is up
