### ISSUE TITLE
cmake add win32 large-address-aware

### ISSUE THREAD

**Issue by aquiles2k** [Framstag/libosmscout#243]
Since 32bit built libraries tends to crash sometimes when map usage gets to heavy i suggest to add the large-address-aware linker flag to circumvent the issue to some degree. 

I am almost certain this is because the memory usage exceeds the 2GB limit of 32-bit programs. However, 32-bit programs running in 64-bit windows can access 4GB of space if linked with --large-address-aware flag

The following is for cmake mingw builds only as i have no clue how to do it for MSVC or in pkg-config
```
if (MINGW)
      set(CMAKE_EXE_LINKER_FLAGS "-Wl,--large-address-aware")
endif ()
```

If running in a 32-bit windows that has the "4GB tuning option" (4GT) enabled, then the 32-bit build linked the --large-address-aware will be able to access 3GB, instead of 2GB, according to https://msdn.microsoft.com/en-us/library/aa366778%28v=vs.85%29.aspx

According to https://msdn.microsoft.com/en-us/library/bb613473%28v=vs.85%29.aspx "Setting this flag and then running the application on a system that does not have 4GT support should not affect the application", so there should not be any negative effects of setting this flag.

**Comment by Framstag** [comment]
I have no problem with patches that fixes problems only for a subset of platforms. What happens if I build under a 64bit compiler with this option set? Do we need to check for a 32 bit compiler in the cmake file first, before activating the option? How?

Problem: All central build environments (travis, appveyor) currently use a 64 bit build environment. I could add a 32bit build. But for me it is enough to be sure that above lines helps for 32 bit builds and does not break the 64 builds. Can you help in this regard?

**Comment by aquiles2k** [comment]
32bit compiler doesnt need to be checked in cmake. On a 64bit build it also increases various memory pool sizes. See the link i provided above for a table with all the different behaviours.

**Comment by aquiles2k** [comment]
Lets see if CI builds it :)

**Comment by aquiles2k** [comment]
Thats a strange one. 
```
Linking CXX executable LookupPOI.exe
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/6.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: unrecognized option '--large-address-aware'
```
The Importer has no problem with that option.

**Comment by aquiles2k** [comment]
```
adrian@n00b MINGW32 ~
$ ld --large-address-aware
D:\Dev\Compiler\msys64\mingw32\bin\ld.exe: no input files
```
```
adrian@n00b MINGW64 ~
$ ld --large-address-aware
D:\Dev\Compiler\msys64\mingw64\bin\ld.exe: unrecognized option '--large-address-aware'
D:\Dev\Compiler\msys64\mingw64\bin\ld.exe: use the --help option for usage information
```

Ok seems msys2 64bit has this explicitly disabled on 64bit.

**Comment by aquiles2k** [comment]
Ok, builds pass now, but to be on the safe side it would be good to have a 32bit ci build.

**Comment by Framstag** [comment]
I'll try to setup a msys2, 32 bit, cmake build at appveyor.
