### ISSUE TITLE
Bad multipolygon type detected for "Apennine Peninsula" (Italy)

### ISSUE THREAD

**Issue by Karry** [Framstag/libosmscout#250]
Hi, regarding to discussion on mailing list, where Italy is covered by `leisure_marina` area, I found that it is caused by this multipolygon:
http://www.openstreetmap.org/relation/4056532#map=7/42.674/12.579

It is Apennine Peninsula, that is composed from some polygons and many, many ways. Some of them are  `leisure_marina`, some `natural_cliff`... First type wins and Italy is blue :-) I seems to me that this OSM  relation is correct, and it is osmscout bug...

```
   Autodetecting type of multipolygon relation 4056532 as leisure_marina
   WW Relation 4056532 - Conflicting types for outer ring (leisure_marina vs. natural_cliff)
   WW Relation 4056532 - Conflicting types for outer ring (leisure_marina vs. natural_cliff)
   WW Relation 4056532 - Conflicting types for outer ring (leisure_marina vs. natural_cliff)
   WW Relation 4056532 - Conflicting types for outer ring (leisure_marina vs. natural_cliff)
```

**Comment by Framstag** [comment]
The relation building rules are (from memory):
* If the relation itself does not have a type, it inherits the type from the outer ring.
* In this case all outer rings should have the same type
* If the relation itself has a type, the ring building ways should not have one

place_peninsula would be the type, but this type is not defined in the map.ost. So for libosmscout it must autodetect the type from the outer ring objects. The relation will then choose the first type detected. If the following objects have a different type, a warning is thrown - but the relation and the type is kept.

The relevant code:
```c++
    if (masterRing.GetType()==typeConfig.typeInfoIgnore) {
      for (auto& ring : parts) {
        if (ring.role.IsOuterRing() &&
            ring.IsArea() &&
            ring.role.GetType()!=typeConfig.typeInfoIgnore) {
          if (masterRing.GetType()==typeConfig.typeInfoIgnore) {
            if (progress.OutputDebug()) {
              progress.Debug("Autodetecting type of multipolygon relation "+
                             NumberToString(rawRelation.GetId())+" as "+
                             ring.role.GetType()->GetName());
            }

            masterRing.SetFeatures(ring.role.GetFeatureValueBuffer());
          }
          else if (masterRing.GetType()!=ring.role.GetType()) {
            parameter.GetErrorReporter()->ReportRelation(rawRelation.GetId(),
                                                         rawRelation.GetType(),
                                                         "Conflicting types for outer ring ("+
                                                         masterRing.GetType()->GetName()+
                                                         " vs. "+ring.ways.front()->GetType()->GetName()+")");
          }
        }
      }
    }
```
I do not see an obvious error in the code. If there is an error, it is in the map.ost, that misses this type. The question though is, if there is a type, how will it be rendered? Should it be rendered at all?

The relation autodetection code could of course be changed. We could take the type, that is most often used. Or we could drop such relations at all.

Opinions?

**Comment by Framstag** [comment]
I'll tend to improve the existing code by choosing the most used type. This should fix the problem with italy - but likely will have impact on other data that is handled by the autodetect algorithm.

**Comment by Framstag** [comment]
I have made some changes to the relation parsing algorithm but the hotel wlan is too slow to download italy, so I have to wait for home to test it (and make some fixes to the map.ost file, too).

**Comment by Karry** [comment]
I am on vacation this week,I will be able to check it next week ;-) I guess that we should drop such polygons unless there is no style for it...

**Comment by Framstag** [comment]
I now pushed the following changes:
* Added new type place_peninsula and marked it as "IGNORE". This would in effect get the problematic relation dropped.
* Improved the handling of the relation type in case of different outer ring types. Also improve handling of tag values in such cases. And finally improve the "drop master ring" optimization.

I hope that especially the second changes do not make relation handling worse.

Please test!

**Comment by Karry** [comment]
Thank you. It seems that this peninsula object is filtered out with latest import and I don't see any new problems with your changes. Thank you!
