### ISSUE TITLE
if there have any working example for iOS develope

### ISSUE THREAD

**Issue by BoshiLee** [Framstag/libosmscout#252]
how to apply this library to new iOS project?

**Comment by vyskocil** [comment]
There is a sample XCode projet to build a application for iOS and Mac OSX : 

Apple/OSMScoutOSX/OSMScoutOSX.xcodeproj

**Comment by Framstag** [comment]
No answer from issuer. Question was answered. Closing the issue. For further questions please ask on the mailing list.
