### ISSUE TITLE
add additional libosmscout tests to cmake build

### ISSUE THREAD

**Issue by aquiles2k** [Framstag/libosmscout#261]
I recently learned that there are some additional tests in the libosmscout/tests subfolder (AccessParse, BitsAndBytesNeeded EncodeNumber, FileScannerWriter, GeoCoordParse, NumberSet, ScanConversion, WStringStringConversion).

It would be nice to have them included to the cmake build as well.

Perhaps it would also make sense to move them to the toplevel Tests dir.

**Comment by Karry** [comment]
Hi. I think that we can close it ;-) Tests are on one place (in "Tests" directory) and both builds (cmake and autoconf) will fail when some test is broken. See this build: https://travis-ci.org/Framstag/libosmscout/builds/216654537 

Note that some interactive tests are not checked as part of the build.
