### ISSUE TITLE
Building with Debian Jessi

### ISSUE THREAD

**Issue by DerKleinePunk** [Framstag/libosmscout#268]
Please delete moc QT files with make clean -> Build error when change the qt version

add hint to install qt5-default paket for debian to set qt to  default 5

**Comment by Karry** [comment]
Hi. You are using autoconf or cmake build? You are right that we should delete `moc` files in clean step, I never test it ;-)

**Comment by DerKleinePunk** [comment]
at moment i use autconf i dream from cmake to add libosmscout as external to my gui/carpc project.

https://cmake.org/cmake/help/v3.0/module/ExternalProject.html

https://bitbucket.org/numberfive/sdl2guitests/overview

but is very complex to build my idea

**Comment by Framstag** [comment]
Just a technical correction/question: There is no autoconf build for the OSMScout2 demo (it either uses qmake or cmake), so I assume you mean the libosmscout-client-qt library? It should be rather simple to add removal of the moc files on "make clean" in this case.

**Comment by DerKleinePunk** [comment]
@Framstag you are right

**Comment by Karry** [comment]
Hi. I tried it in Docker image, after `make clean` I found just a few `*moc*` files:
```
$ find . -name *moc*
./libosmscout-client-qt/src/osmscout/.deps/moc_DBThread.Plo
./libosmscout-client-qt/src/osmscout/.deps/moc_MapWidget.Plo
./libosmscout-client-qt/src/osmscout/.deps/moc_RoutingModel.Plo
./libosmscout-client-qt/src/osmscout/.deps/moc_SearchLocationModel.Plo
```
It seems that these files may cause troubles, it contains list of includes (with Qt). `moc_*.cpp` files are cleaned properly. In [this StackOverflow thread](http://stackoverflow.com/questions/11378496/make-clean-doesnt-clean-dependencies-with-automake) is suggestion to use `make distclean` for cleaning `.deps` directories. It really works
```
$ make distclean
$ find . -name *moc*
```
...nothing is there. Question is, what is difference between `clean` and `distclean`? Should we clean `.deps` directories on `clean` target?

**Comment by Framstag** [comment]
See https://www.gnu.org/software/automake/manual/html_node/Clean.html. I now added some more moc*.cpp files to MOSTLYCLEANFILES (before CLESNFILES was used).

Pushed this change. Is this enough? The .deps directory should not be a problem?

What about "add hint to install qt5-default paket for debian to set qt to default 5". Where should I add such hint? Build documentation?

**Comment by Karry** [comment]
I don't know the purpose of `*.Plo` files, but it contains full paths to include headers - it may cause problems when you upgrade Qt version...?
> Build error when change the qt version

**Comment by DerKleinePunk** [comment]
Yes i mean the Build Documentation

**Comment by Framstag** [comment]
The *.plo files contain dependency information. They should be updated (via Makefile dependencies) if a file was changed. If you use modern gcc or similar the autoconf system creates them automatically by asking the compiler. 

Since none of them gets deleted I assume that they are not specific to the problem mentioned by @DerKleinePunk.

I updated the build documentation regarding Qt5 vs. Qt4. The webpage should get updated once the central build for my change finished.

@DerKleinePunk: If the issue was done, please close the issue. If not, please tell us what is left to do :-)

**Comment by Framstag** [comment]
@DerKleinePunk: Can we close the issue?
