### ISSUE TITLE
Location index return duplicate objects

### ISSUE THREAD

**Issue by Karry** [Framstag/libosmscout#269]
When location index contains more (nested) administrative areas with single name, like:
 - "Praha" (Prague - town)
 - "okres Hlavní město Praha" (district Prague capital)
 - "Hlavní město Praha" (region Prague)

it may return duplicate results for simple query: "POI name, location". In this case: "Florenc, Praha". Solving this issue may even improve search performance.

Additional discussion and usecase: https://github.com/Framstag/libosmscout/issues/266 I am creating new issue for that problem, because original issue is feature request for merging near miscellaneous objects with same name and type...

**Comment by Framstag** [comment]
@Karry: I pushed a fix seconds before, please test if the behaviour in above case was improved.

**Comment by Karry** [comment]
Hi Tim. I review this commit and it should works... But it breaks cmake build, because it is configured for c++11 standard :-(
```
/home/karry/data/tmp/libosmscout/libosmscout/src/osmscout/LocationService.cpp: In member function ‘bool osmscout::LocationService::SearchForLocations(const osmscout::LocationSearch&, osmscout::LocationSearchResult&) const’:
/home/karry/data/tmp/libosmscout/libosmscout/src/osmscout/LocationService.cpp:1009:48: error: use of ‘auto’ in lambda parameter declaration only available with -std=c++14 or -std=gnu++14
       adminRegionVisitor.results.sort([](const auto& a, const auto& b) {
                                                ^~~~
```
c++14 is supported from gcc 6.2, that is not problem for me on Ubuntu, but in Sailfish OS SDK is available gcc version 4.8.3... It should not be problem to compile new one, but I suggest to avoid `auto` in lambdas :-)

**Comment by Framstag** [comment]
Replaced auto with real type

**Comment by Karry** [comment]
Thank you! It fixes this problem :-)
```
$ ./Demos/LocationLookup czech-map "Florenc, Praha" | grep -B 2 highway_bus_stop
= POI (Florenc) = Praha
   * Praha/Česko
   - Node 43298431 highway_bus_stop
--
= POI (Florenc) = Praha
   * Praha/Česko
   - Node 43296875 highway_bus_stop
```
