### ISSUE TITLE
Add explicit download timeout to Qt network api

### ISSUE THREAD

**Issue by Karry** [Framstag/libosmscout#276]
Qt don't support to configure download timeout. System default (about one hour) is used! This cause problems when you start map download (or online map tile) and go away from wifi signal... Downloading stucks then. Lost tcp connection is detected (by app) after hour and downloading is restarted. It is toooo late!

All tutorials for Qt networking api suggest to add custom download timeout and reset it when some data arrives (signal `QNetworkReply::downloadProgress`).

**Comment by rinigus** [comment]
I will work on it by merging FileDownloader into the upstream. Timeouts are incorporated there already , together with resumption of downloads .

**Comment by Framstag** [comment]
Since the pul request was merged...can we close this issue?

**Comment by Karry** [comment]
I have sad news. File downloader cant recover from network transition - I started downloading on wifi, then go outside. Dowloading continue after few seconds and it seems that it was finished. But target directory contains just few (3) files. System log contains threse errors:

**Comment by rinigus** [comment]
@Karry, I wonder if you propagated the error message by the downloader to GUI? Its possible that it didn't manage to download any data for a freshly started file and stopped with "network unreachable" error during transition. Note that the downloader is not bullet proof, but I found that it gives a reasonable result. 

Now, when I use the mapmanager in the OSM Scout Server, only files that are missing on the disk. That way, user can continue downloading dataset for the missing files only. That mechanism is probably missing in current implementation of the manager in libosmscout.

As for  this issue, I guess we are not talking about timeouts anymore?

**Comment by Karry** [comment]
I handle error messages in QML here: https://github.com/Karry/osmscout-sailfish/blob/master/qml/pages/Map.qml#L21

It seems that it timeout correctly, but retry after timeout don't work... Should I create new issue for that?

**Comment by Karry** [comment]
...downloading fails even with stable connection. If I understand it correctly, you reset `m_download_last_read_time` on download start and in `FileDownloader::onProcessRead` method. But this method is called only when you write data to the "unpack" pipe... When you use `Plain` mode, and download of one file will take longer than 60 seconds, downloading fails every time... You should reset time in `FileDownloader::onBytesWritten` too...

**Comment by rinigus** [comment]
@Karry, I haven't tested it that much in Plain mode. Its reset in onnetworkread method, which is the same as onprocessread for Plain mode. So, it should be sufficient. Do you have an error message with which it fails?

**Comment by Karry** [comment]
Just "timeout" :-)

**Comment by rinigus** [comment]
@Karry, I am sorry for patchy replies - I would be able to look in more details when I am back home on the weekend. But maybe we can figure out what's going on even earlier. Try to uncomment 

https://github.com/Framstag/libosmscout/blob/master/libosmscout-client-qt/src/osmscout/FileDownloader.cpp#L327

and see what happens. Timeout is triggered only if restartDownload fails (timeouts expired multiple times without download, for example). Device sleep could also interfere, potentially. You could see what would happen if you put the phone on charging, if its on SFOS.

**Comment by rinigus** [comment]
Lukas, have you managed to look a bit further by recompiling with the debug messages included?

**Comment by Karry** [comment]
Yes, I will look at it. Be patient, I was focused to clastlines previous days :-)
