### ISSUE TITLE
TransPolygon may create complex polygon/way (not simple)

### ISSUE THREAD

**Issue by Karry** [Framstag/libosmscout#282]
Hi. When I debugging one issue with coastline (water on left side of coastline), I found that it is caused by `TransPolygon` used from `WaterIndexGenerator::GetCoastlineData`. It simplify one way and from simple coastline creates complex one (line intersects itself). It cause problems in cell intersection detection and following computation steps that expect that coastlines are simple...

It would be great to have option in `TransPolygon` that avoids creating such problems :-)

![bad-optimised-way](https://cloud.githubusercontent.com/assets/309458/24239561/b153946a-0fae-11e7-9344-52e28e6855ff.png)

**Comment by Framstag** [comment]
There are two optimization variants for TransPolygon. Does the problem occur for both of them?

**Comment by Karry** [comment]
Yes, this problem occurs with both variants, `OptimizeMethod::fast` and `OptimizeMethod::quality`. Be concrete, this problem occurs on [this Italy coast line](http://www.openstreetmap.org/way/47913421#map=17/43.90862/8.08878), on zoom level 12 and it cause this error:

![italy-intersecting-coastline](https://cloud.githubusercontent.com/assets/309458/24317377/bbea2594-10f6-11e7-9972-75a36cb185bd.png)

I can look at it after weekend if you want to focus on something else or you don't have time for it...

**Comment by Framstag** [comment]
It would be nice if you can take a look. I likely would not have the time neither do I have an idea for a quick fix.
