### ISSUE TITLE
Allow multiple different views/renders of offline map database at the same time [$50]

### ISSUE THREAD

**Issue by aquiles2k** [Framstag/libosmscout#284]
The most common usage of the current map view (qt) is one central map and the current implementation is based on this. 

For some other usage scenarios it would be nice to also have the ability to have multiple views e.g. side by side, overlayed (think overview map in a corner) or on different widgets in a desktop app.

For this i think the implementation has to be extendended so that its clear which view is requesting updates and which cache data has to be kept etc.

Some initial discussion https://sourceforge.net/p/libosmscout/mailman/message/35588323/

**Comment by Framstag** [comment]
Can you give an example, where such feature would be helpful? Perhaps we can add it to the OSMScout demo and then have a new feature and a reproducer at hand. Else I would have do build a simple test application to reproduce the problem.

**Comment by Karry** [comment]
It would be usefull in styleeditor for example. When it will have multiple map views, you can preview how your changes looks like on different zoom levels or even different places...

It is possible already with tiled db thread. But it is not possible with plane...

I would like to refactor db thread (split database management, search, rendering... to separate classes/threads) and allow such usage. But it is low on my todo list.

**Comment by Framstag** [comment]
@aquiles2k: Are you using the existing libosmscout-client-qt and have thus the problem mentioned by @Karry, that the current DBThread implementation doe snot support this?

@Karry: I assume that the rendering code would have to move into the MapWidget while the data acquisition code could stay in in the DBThread?

**Comment by aquiles2k** [comment]
The only test i did back then was putting two Map Items in qml side by side. This resulted in heavy flickering on the maps once i started dragging one of the maps and i came to the conclusion its because of all things said like heavy coupling of the rendering code with the database without differentiating which view gets which updates and which cache gets deleted etc.. 

Yes we use the client-qt-lib but avoided these problems by removing the singleton and simply have each widget have its own bundle of mapview and associated database. I think i mentioned this once on the list. 

Anyway i know this is kind of overkill and thats why i created this issue but for the time being it solved our problem :)

**Comment by Karry** [comment]
*Plane* DBThread don't support it, but there is no such problem with *Tile* rendering...

Well, I am thinking about refactoring of Qt API long time. DBThread instance now contains *everything* (rendering, object lookup, searching...) and some API methods accessible from UI thread are blocking! I would like to add another layer (renderer) between MapWidget and database management... I am thinking about something like this:

![libosmscout-qt-api-proposal](https://cloud.githubusercontent.com/assets/309458/25217767/6ea06278-25a8-11e7-98ef-73e637602165.png)

**Comment by Framstag** [comment]
Looks like you follow the modelling in the base libraries (XXXService). That makes sense. Also moving the rendering code out of DBThread into something else was suggested by me, too. So: Go on :-)

The initial design was choosen, because it was simpler and was enough to get the demo working. At that time there was also no multi threading locking code in Database and using Services so this was easiest to implement at central location. Now we have learned from the initial test design and have better locking (or can easily add it because we are now C++11 and have free access to multi threading functionality) the design can and should be improved as suggested.

**Comment by aquiles2k** [comment]
Wow, thats some dedicated API structuring! Do you have any time frame on this and would something like the bounties i proposed on the mailing list increase the likelihood of it getting some attention? :)

**Comment by Framstag** [comment]
I could help with some parts (though I'm working on other parts of the code currently) but it makes sense, if @Karry at least works on the actual rendering code. He already did some improvements and changes and I would have to did deeper into his current code to get started.
The old code however (and possibly the new, too) has some tricky side effects regarding signal handling and multi threading and slight changes were able to break the rendering pipeline. @Karry: Have you already detected them or are aware or them or even improved the situation?

**Comment by Karry** [comment]
@aquiles2k: I will try to do refactoring this way. I want to have non-blocking `RoutingModel` and this refactoring is pre-requisite... Don't worry, I am interested in it.

@Framstag: Yes, I probably know what you mean - plane rendering is using asynchronous data loading with callback and timer to postpone rendering... It is simple to break it. I don't improve it much...

**Comment by aquiles2k** [comment]
So while having a first look into the rendering "pipeline", i think it all starts (for example by the DragHandler) with a MapWidget::redraw() which calls QQuickItem::update() which eventually will trigger MapWidget::paint() which finally calls PlaneDBThread::RenderMap().

Its this last call i think which needs to provide an additional indicator to PlaneDBThread which MapWidget is requesting the render. Perhaps just the this pointer itself or through extension of the RenderMapRequest. This can then be saved within PlanDBThread in a hash or something.

This way when the pendingRenderingTimer::timeout finally triggers drawing through PlaneDbThread::DrawMap it can emit Redraw(), also with an additional parameter like the orignally requesting MapWidget pointer. This way we are now back in the MapWidget and can decide if the Redraw() signal we just received is meant for us by e.g. comparing the MapWidget pointer to ourselve.

This is just a first quick run though, i guess theres additional logic needed inside PlaneDBThread when requesting tiles etc. so to differentiate among different render request from different views.

**Comment by aquiles2k** [comment]
Im testing it atm with OSMScout2 and a germany map using qt5.6.2 on mingw based win build. No crashes so far. The only think im getting from time to time at startup is:

```
QObject::moveToThread: Current thread (0x62e4790) is not the object's thread (0x5d601b0).
Cannot move to target thread (0x1406260)

QObject::moveToThread: Current thread (0x5d601b0) is not the object's thread (0x62e4790).
Cannot move to target thread (0x1406260)
```
For testing i've added a second Map below the original one in main.qml and a button to spawn a new Window like so:

```
MapButton {
  label: "n"
  onClicked: {
    var component = Qt.createComponent("main.qml")
    var window    = component.createObject(mainWindow)
    window.show()
  }
}
```

**Comment by aquiles2k** [comment]
I'll test it some more within our application. Could you assign Karry in the meanwhile to this issue?

**Comment by Framstag** [comment]
Looks like I cannot assign an issue to somebody else. Interesting. @Karry, can you *take* the issue?

**Comment by aquiles2k** [comment]
Perhaps you have to add him as a collaborator?
See here:
https://help.github.com/articles/assigning-issues-and-pull-requests-to-other-github-users/
and here:
https://help.github.com/articles/inviting-collaborators-to-a-personal-repository/

**Comment by Framstag** [comment]
Invited him (and others) as collaborator, but he has to accept first, before I can assign issues to him.

**Comment by aquiles2k** [comment]
Looking good for me and is working inside our desktop app. Any objections on closing this?

**Comment by Framstag** [comment]
OK for me, though I did not do any actual checks.

@Karry: To receive the bounty you have to search for the issue URL at https://www.bountysource.com/. You can then claim the bounty.

**Comment by aquiles2k** [comment]
is working and succesfully tested the last weeks

**Comment by aquiles2k** [comment]
Please claim the bounty
