### ISSUE TITLE
importer hangs at Canada/Nunavut extract

### ISSUE THREAD

**Issue by rinigus** [Framstag/libosmscout#288]
For some reason, Importer hangs on importing Canada/Nunavut region:

```
+ Step #11 - OptimizeAreaWayIdsGenerator...
   Module description: Optimize ids for areas and ways
   Module requires file 'areas2.tmp'
   Module requires file 'wayway.tmp'
   Module provides temporary file 'areas3.tmp'
   Module provides temporary file 'ways.tmp'
 - Optimize ids for areas and ways...
 - Scanning ids from 'areas2.tmp'...
   319212 areas, 463 ids found
 - Scanning ids from 'wayway.tmp'...
   198370 ways, 50706 ids, 0 circular ways found
   Found 46642 relevant nodes, 4157 of it at least used twice
 - Copy data from 'areas2.tmp' to 'areas3.tmp'...
   % 2.35 (7493/319212)
   % 2.35 (7494/319212)
   % 2.35 (7504/319212)
```

This issue can be overcame if `complete_ways` extraction strategy is used by osmium, instead of `smart`, as used by Geofabrik. The corresponding osmium command that leads to PBF which is OK for libosmscout import is below

```
osmium/install/bin/osmium extract --overwrite -p hierarchy/north-america/canada/nunavut/poly.poly -s complete_ways splitted/north-america-canada.pbf -o splitted/north-america-canada-nunavut.pbf
```

What's failing in case of `smart` strategy, hard to say. When I tested last time with extract provided at http://download.geofabrik.de/north-america/canada/nunavut.html, the issue was present as well (not surprising, since the same osmium is used over there). The rest of the World imports without any visible issues.

**Comment by Framstag** [comment]
Strange importer step to get into an endless loop. I'll take a look though. Plan is to start the importer from the gdb debugger, break at the time it gets into an endless loop, analyse the call stack, add further logging, find the bug and fix it.

Sounds easy, doesn't it;-)?

**Comment by Framstag** [comment]
Oh boy, the import already close to hangs for a longer time in step #6. It looks like there are some huge relations in the import :-/

**Comment by Framstag** [comment]
Looks like https://www.openstreetmap.org/relation/3957497#map=5/68.648/-75.686 is at least part of the problem. 

I now added some static constants regarding maximum size of relations to step #6 (GenRelAreaData):

```
  static const uint64_t MAX_WAYS=1000;
  static const uint64_t MAX_COORDS=100000;
```

This now drops two relations based on above limits, one of it being the mentioned island. Possibly we can increase the MAX_WAYS limit, but the MAX_COORDS limit seams reasonable. After that "fix" I get at least to step #11 in reasonable time. Step #11 now works like a charm, so I assume it is a problem with too big relations (somehow).

If the hard limit is not acceptable, we can make it an option in the parameters. But it looks like there must be a limit somehow...

Why is step #11 slow? It is possible that the

```
        data.Write(typeConfig,
                   writer);
```

method call does have a bug for rings that are too big Some problem in storing long areas/ways?

**Comment by Framstag** [comment]
Is the current solution acceptable for you or should/must we look deeper? My problem is, that without the patch I do bot get up to the point in the import process, where the problem occurs.

**Comment by rinigus** [comment]
Sorry, I thought its resolved. The import looks similar to the import I made using different PBF. So, I think we can close the issue.

**Comment by Framstag** [comment]
There will be errors now during the import for dropped relations. In my import two relation have been dropped.
