### ISSUE TITLE
Optimise TransPolygon::FindIntersection

### ISSUE THREAD

**Issue by Karry** [Framstag/libosmscout#292]
Currently, `TransPolygon::FindIntersection` has almost `n^2` complexity (n is path length): https://github.com/Framstag/libosmscout/blob/master/libosmscout/src/osmscout/util/Transformation.cpp#L352

It led to slow computation with long paths (thousands of nodes), this method can be optimised by splitting path to shorter segments, and skip complete segment when intersection is not possible (bounding boxes don't intersects). Such method was used here: https://github.com/karry-space-with-my-second-forks/libosmscout/blob/0e978dfa299dbbf8f65c971d00a718458cb4d412/libosmscout/include/osmscout/util/Geometry.h#L1051 But this method work with two different pahts, it can't be used in TransPolygon now...

**Comment by Karry** [comment]
It is optimised in this commit: https://github.com/Framstag/libosmscout/pull/190/commits/a153b0d7a16e96a957dde92c8ab27e0605005123 

I thing that it is not necessary to create separate MR for that...

**Comment by Karry** [comment]
...new coastline computation is only place using that. Computation of Finland coastlines tooks 52 minutes without it and 98 second with this optimisation :-)

**Comment by Framstag** [comment]
The relevant pull request is close to merge, I'm closing this.
