### ISSUE TITLE
building with qt

### ISSUE THREAD

**Issue by marcovc** [Framstag/libosmscout#298]
Hi,

Thanks for the great work.

I'm trying to build the software by importing each project inside QT creator. I'm thus trying to follow the
  
> Autogen + qmake for Qt libraries + make

path as stated in the documentation.

However, after running Autogen, there are still some *.in and *.cmake files (for example ClientQtFeatures.h.in)  inside the "include" directories, and qmake doesn't know what to do with them:

> WARNING: Failure to find: include/osmscout/ClientQtFeatures.h

I'm probably misunderstanding something. Could you help?

Thanks!
Marco

**Comment by Framstag** [comment]
I'm building everything but OSMScout2 8and StyleEditor) using autoconf. Only the Qt GUI applications I build using qmake. See the top level Makefile for this variant of build. This is also what the central Travis and Appveyor builds (partly - since we also have cmake based builds, too) do.

See https://travis-ci.org/Framstag/libosmscout and https://ci.appveyor.com/project/Framstag/libosmscout

Build the qt based *libraries* should also work, but is not covered by the actual central builds so might have silently broke over time.

On which OS are you building on? Which compiler are you using? I will delegate your question to the mailing list to see, if there is somebody that actively uses your build combination.

**Comment by marcovc** [comment]
Thanks for the quick reply. I'm using g++ 4.9.2 on Debian Linux (kernel 3.16-amd64).

My idea was to build qt apps using qt creator since I found out that you're shipping the *.pro qt project files, and qt can handle native compilation and cross-compiling (e.g to android) from the IDE. I guess I could instead go the autoconf route like in the travis build you've referenced, but I was just trying to make everything inside of qt. 

Thanks!
Marco

**Comment by Framstag** [comment]
There are not qmake project files for all required libraries. So you will need to use autoconf or cmake builds anyway. I'm not an expert in qmake files (I'm sure it was a 3rd party patch :-)) but it looks like the file is not complete. I assume it was created to use qt creator for projects - but based on a completed and run autoconf build.

So I suggest to either use autoconf or cmake or enhance the qmake file (but I assume that you will need *.pro files for libosmscout, libosmscout-map, too, n this case).

Patches are always welcome, so if you enhance/add *.pro files, just make a pull request :-) It would be of course very cool, if you could offer a qmake based travis/appveyor build. This would assure, that the file would not break again so easily.

**Comment by Framstag** [comment]
@marcovc: Are the answers OK for you and I can close the issue? If you want to create a more concrete issue regarding the qmake support you are of course free to do so.

**Comment by marcovc** [comment]
@Framstag : Yes, you can close it. I'm still undecided if I'm going with libosmscout or not, so I'll look into it later. Thanks for your help!

**Comment by Framstag** [comment]
OK, no problem.

Last question: Why are you undecided? Are there important features missing? Too complex? Not enough documentation? We are of course very convinced of what we do, but feedback from somebody with some more objective perspective can be a big help to improve the product - even if he decided not to use it m:-)

**Comment by marcovc** [comment]
@Framstag: 

I'm afraid I don't know about this kind of technology enough to be helpful, but here's my use case:

I'm building an app with Qt to run on vehicles (for logistics) and found libosmscout when  seeking mainly for a way to have offline maps, but also to assess how feasible it is in the current days to develop a bare minimal GPS navigator.  

I'm still not sure even if libosmscout is a possible way to do this. Since I posted this question I learned that Qt 5.9 will support the mapbox opengl extension, which also looks like a possible candidate (unfortunately it comes with a cost).
  
Maybe one way to improve the documentation is to have a kind of "how libosmscout compares with..." section.

I hope this helps. Really appreciated your interest. Thanks!
Marco

**Comment by Framstag** [comment]
@marcovc:
Thanks for your feedback!

You have found http://libosmscout.sourceforge.net/, which already should give you a lot of information, haven't you?

Nevertheless, it looks like we should bring more clear facts to the point onto the starting page ;-)

Here is my test, if we could make things more clear ;-)

Yes, libosmscout is a collection of libraries and tools, to offer good to excellent implementations for a lot of problems you have to solve while writing a navigation application - like Google Maps or Osmand.

The problems it solves:
* Transform OSM data (*osm or *.osm.pbf files) into some internal database, which is the base for all offline functionality.
* Be able to influence what data in the database and thus how big the database will be and which area it will cover.
* Render offline vector maps based on the data in the database
* Use a style sheet to manipulate the look of the map
* Route based on data in the database. Routing is based on different profiles (for car, bike, foot for example)
* Create a description and extendable description of the route
* Make various lookups based on the database, especially search for geo locations based on addresses are create descriptive descriptions based on geo location.

For a GPS navigation still missing would be:
* GUI code (but we already have some code for Qt based applications, too)
* GPS handling and interaction with the map
* Server infrastructure for generation and distribution of maps (and we have scripts and experience in that already, too)
* and similar...

I have seen applications based on libosmscout for Sailfish OS, Ubuntu Phone, iOS and Android

Mapbox is of course a much bigger fish and has certainly more to offer. But we have a much better price/feature ratio and IMHO the better license ;-)

**Comment by marcovc** [comment]
@Framstag : Thanks for the enlightment, things are clearer now. By the way, is libosmscout related in any way with skobbler scout (https://developer.skobbler.com/) ?
