### ISSUE TITLE
Unable to find documention on how to use it with Qt code

### ISSUE THREAD

**Issue by gurpartap007** [Framstag/libosmscout#299]
I successfully build libosmscout with Qt Support but there is no documentation on how to start writing application with Qt.Please help me sir.

**Comment by Karry** [comment]
Hi. Part of this project is library `libosmscout-client-qt`. It contains some basic Qt models and `MapWidget` that may be used when you are creating UI in QML. Probably the best starting point is OSMScout2 demo application: https://github.com/Framstag/libosmscout/blob/master/OSMScout2/src/OSMScout.cpp 

For your first application that is using osmscout library, you just need to register required QML types, setup `DBThread` and open QML scene in C++. Everything else can be written in QML (unles you don't need to extend existing models or create new one)... https://github.com/Framstag/libosmscout/blob/master/OSMScout2/qml/main.qml#L111

**Comment by Framstag** [comment]
If this answers your initial questions, please close the issue. You can of course get further more detailed support on the mailing list.

**Comment by Karry** [comment]
Another question is, what do you want to create? We can show you some example...

**Comment by Framstag** [comment]
Closing the issue. Help was given, no response yet :-/
