### ISSUE TITLE
Allow adding labels to types in *.ost file

### ISSUE THREAD

**Issue by Framstag** [Framstag/libosmscout#304]
Allow adding a language specific textual description for a type to a type definition in a *.ost file. Possible syntax:

```
TYPE highway_motorway
  = WAY ("highway"=="motorway")
    {Name, NameAlt, Ref, Destination}
    PATH[CAR] LOCATION OPTIMIZE_LOW_ZOOM PIN_WAY
    DESC
      de: "Autobahn"
      en: "Motorway"
```
The given text could then later be used by applications to provide locale specific descriptions of the object type.

**Comment by Karry** [comment]
Hi. I don't think that adding localisation to library itself is a good idea. I am using Qt API for localisation, even for database types (https://github.com/Karry/osmscout-sailfish/blob/master/qml/l10n.qml). I guess that other frontend libraries/frameworks provide similar api, by adding localisation API to library will make usage more complicated...

**Comment by Framstag** [comment]
I do not plan to integrate localisation features for all in everything into libosmscout. I agree that the UI library should offer such features.

But I (currently ,-)) see some places were it might make things simpler, to have translations of some special things at hand.
* Name of features
* Name of types
* Generation of route description (possibly can solved differently)
* Possibly later some one to handle localized error messages

In the first cases placing translations into the OST allows a central management as part of the database generation. The user (each and every) of the database does not need to do his mapping on its own. Especially he does not handle additions or removals to the central map.ost file.

I find having translations at hand nice, so that I can generate a type based search for POIs without much hassle ("Look for restaurant"....).

**Comment by Framstag** [comment]
Is my intention clear? Is this still a bad idea?

**Comment by Karry** [comment]
Ok, some your points makes more or less sence :-) Localised route description + route commands is the most challenging, I think. And it will be great to provide it in library...

**Comment by Framstag** [comment]
This was implemented as suggested.

**Comment by rinigus** [comment]
@Karry - not directly related to this issue, but to localized routing messages. You may want to take a look at OSM Scout Server implementation of the routing messages (https://github.com/rinigus/osmscout-server/blob/master/src/routingforhuman.cpp called at https://github.com/rinigus/osmscout-server/blob/master/src/dbmaster_route.cpp ). Translations are managed at https://www.transifex.com/rinigus/osm-scout-server/languages/ . These should give a decent starting position for localized routing messages.
