### ISSUE TITLE
source releases for build lib with other projects and cmake

### ISSUE THREAD

**Issue by DerKleinePunk** [Framstag/libosmscout#323]
for using CMake an the Dependency Project Function we need source code releases as tar.gz file an hash value. I will use the lib on Raspberry 2

Sample for SDL2:

if(CMAKE_CROSSCOMPILING)
    MESSAGE(STATUS "Try get and build sdl2 ${SDL2_VER}")
    # SDL library
    ExternalProject_Add(sdl2_project
        URL http://www.libsdl.org/release/SDL2-${SDL2_VER}.tar.gz
        URL_HASH SHA256=442038cf55965969f2ff06d976031813de643af9c9edc9e331bd761c242e8785
        DOWNLOAD_DIR ${EXECUTABLE_OUTPUT_PATH}/download
        PREFIX ${EXECUTABLE_OUTPUT_PATH}/sdl2

**Comment by Framstag** [comment]
I now did some initial release just to give you a change to test of the result pleases you :-) Sorry, that it took so long :-/

Please test and close the issue if it fits your needs. I will try to do more releases if appropriate but you still can demand a release on the list anyway!
