### ISSUE TITLE
Support >2GB files for MSVC based builds

### ISSUE THREAD

**Issue by Framstag** [Framstag/libosmscout#324]
There are some build warnings that hint, that we only use 31 bit file size aware file operations. We should check for _fseeki64 to support bigger files, too.

See https://msdn.microsoft.com/de-de/library/75yw9bf3.aspx?f=255&MSPPError=-2147217396.

**Comment by aquiles2k** [comment]
Actually i already added this check back then:
https://github.com/Framstag/libosmscout/blob/master/cmake/TestWindowsFSeek.c

It seems its more a cmake misconfiguration.

**Comment by Framstag** [comment]
That would be good. If the tests and it usage is correct I should be able to trigger special code by using a coresponding define. Note, that currently there is simple no code in libosmsocut that uses _fseeki64. So even if there a tests, it will not work. But the relevant code should be easy to add.

**Comment by Framstag** [comment]
I have now pu sh some changes to support this using autoconf. I also changed the cmake tests to (at least it looks like) get it to work, too.

I did however not test, if now access for >2GB actually works. It would be nice if somebody else could and close the issue in case it works.

**Comment by aquiles2k** [comment]
Cmake did say it found the function

Checking for 64-bit off_t
Checking for 64-bit off_t - not present
Checking for _fseeki64/_ftelli64
Checking for _fseeki64/_ftelli64 - present
Checking for fseeko/ftello
Checking for fseeko/ftello - not found
Large File support - not found

Even though it still says large file support not found but i guess thats just the visuals.

It also compiles but i havent tested it with large files yet.

**Comment by Framstag** [comment]
@aquiles2k: Have you already done some tests?

**Comment by Framstag** [comment]
Closing this.
