### ISSUE TITLE
Dedicated option for Importer to specify POLY file

### ISSUE THREAD

**Issue by rinigus** [Framstag/libosmscout#332]
As discussed in the mailing list:

* At present, POLY file should be added as a last argument in the Importer. It should be a file with the extension ".poly"

* Would be great to specify POLY file using a special argument. Tim suggested `--clipregion` , Osmosis uses `--bounding-polygon`

It looks to me that, right now, POLY file is added as a map in Importer and later detected as a POLY file in https://github.com/Framstag/libosmscout/blob/master/libosmscout-import/src/osmscout/import/Preprocess.cpp#L937

**Comment by Framstag** [comment]
Pushed change. New option is named --bounding-polygon as suggested. build.sh automatically detects a bounding polygon if it has the same basename as the import and ends in *.poly.

**Comment by Framstag** [comment]
Build OK. Closing.

**Comment by rinigus** [comment]
@Framstag:

Tim, thank you very much! It looks like you still require that the polygon file uses `*.poly` naming convention. Is this check required?

**Comment by Framstag** [comment]
@rinigus 
Yes, files must end in *.poly. I did this because I assumed that this was a common convention.

As the polygon parser from Lukas seems to be reasonable robust, we can drop this, if you have polygon files that do not end in *poly. If there are only two postfixes though in the world for polygon files I can simply add the second one to the check, too.

**Comment by rinigus** [comment]
Morning! I am using file named just `poly` in the World imports. So, based on earlier scripts from modRana, import from GeoFabrik, and work by one of the user from Russia, we made the whole hierarchy of territories that are used to split the planet and, eventually, provide users with the datasets (example of poly file at https://github.com/rinigus/osmscout-server/tree/master/scripts/import/hierarchy/europe/germany/niedersachsen). Would be great not to rename 200+ files or use workarounds with making temporary *.poly files.

**Comment by Framstag** [comment]
So I allow any file name (but would keep *.poly as guide in the command line help)?

**Comment by rinigus** [comment]
I think this sounds very reasonable and should be clear for the users as well.
