### ISSUE TITLE
MapPainterCairo: wrong path filled

### ISSUE THREAD

**Issue by lkuoza** [Framstag/libosmscout#339]
Hello,

I tried to use OSMScout and came across one problem. I used Cairo as renderer and data from OpenStreetMap. I found out, that Method MapPainterCairo::DrawSymbol doesn't clear cairo path, which leads to presentation bug. See attachment (to compare, this is the following tile in OSM: http://a.tile.openstreetmap.org/15/17034/11015.png).

![wrong_vs_right](https://cloud.githubusercontent.com/assets/29039279/26547225/34540e28-446e-11e7-9504-8b441393070c.png)

Following patch fixes the problem. It would be nice if someone would commit this patch in master branch. Thank you.

<pre>
diff --git a/libosmscout-map-cairo/src/osmscout/MapPainterCairo.cpp b/libosmscou
index d1d5761..c15b552 100644
--- a/libosmscout-map-cairo/src/osmscout/MapPainterCairo.cpp
+++ b/libosmscout-map-cairo/src/osmscout/MapPainterCairo.cpp
@@ -1191,6 +1191,8 @@ namespace osmscout {
       FillStyleRef   fillStyle=primitive->GetFillStyle();
       BorderStyleRef borderStyle=primitive->GetBorderStyle();

+      cairo_new_path(draw);
+
       DrawPrimitivePath(projection,
                         parameter,
                         primitive,
</pre>

**Comment by Framstag** [comment]
Pushed change. Thanks for the hint and the bug fix!
