### ISSUE TITLE
MapPainterCairo: Text alignment for shield labels

### ISSUE THREAD

**Issue by lkuoza** [Framstag/libosmscout#340]
Hi, I came across another issue with cairo renderer.

I use cairo, without pango under Windows. I've used font size of 3.0 (drawParameter.SetFontSize(3.0)). There is a problem with vertical allignment of text in shield labels (One can see it also for default font size, but is not so obviously in this case).

![text_allignment_in_shield_label](https://cloud.githubusercontent.com/assets/29039279/26556121/fed07f22-4498-11e7-8233-a65f30ed4b42.png)

I was able to correct it with the following change:

<pre>
--- a/libosmscout-map-cairo/src/osmscout/MapPainterCairo.cpp
+++ b/libosmscout-map-cairo/src/osmscout/MapPainterCairo.cpp
@@ -947,7 +947,7 @@ namespace osmscout {

       cairo_move_to(draw,
                     label.x,
-                    label.y+fontExtents.ascent);
+                    label.y + (label.by2-label.by1-fontExtents.height) / 2);

       cairo_show_text(draw,label.text.c_str());
       cairo_stroke(draw);
</pre>

**Comment by Framstag** [comment]
Thanks again. Pushed fix.
