### ISSUE TITLE
OSMScout2: Correctly handle drawing of map at mercator projection range limits

### ISSUE THREAD

**Issue by Framstag** [Framstag/libosmscout#356]
There are a number of situation where OSMScout2 stops rendering a map. Reason for this is:
* Mercator projection does have smaller limits than the planet (poles cannot be rendered)
* On low zoom map may not fit the screen, so there will be areas, where no map can be drawn, since the region has invalid coordinates on earth.
* Moving the map could result in moving around the poles (lat < -90 or > 90) or moving over lon -180/180.
* Resizing the windows may make invalid regions visible, without actually moving or zooming.

I tried to fix this by changing MercatorProjection so that is only allows valid values. However I'm not sure, that this enough. I assume that we have to change or enhance the Projection API to allow the client to act better.

@Karry: Please look at the current situation and your qt-client code. Let us then discuss how a proper solution could look like.

**Comment by aquiles2k** [comment]
After some experimentation:
* I like the current restriction when going north but it still sometimes behaves a bit "choppy/laggy". 
* Also when going south i can go beyond antarctica until the restriction starts which looks strange. 
* I personally dont like that when zooming far out with base map active you often get black screens as if no map db is within view coords.

**Comment by Framstag** [comment]
IMHO balck borders (or something similar) cannot be avoided. Under mercator projection (and any other projection of course, too) the world has some certain aspect ratio. If your application windows has another aspect ratio (on the desktop it can even change dynamically, while on mobile there will always be only two) than the world has, you have to find a solution to visualize this. Horizontally you could just wrap around (see issue #29) but vertically - at least for mercator projection - this does not make sense.

But that was exactly my intent. First clarify what we want to show and then take a look which information the applications needs from the projection, to get this solved.

Mercator projection (via the general Projection base class) could for example offer:
* Suggested aspect ratio
* Range limits for lat and lon
* Calculate "on range in bounds view point" in case where requested ranges are "invalid"

**Comment by aquiles2k** [comment]
I dont meant black borders but the complete view goes black at certain positions, most likely because of the database in bounds check.

**Comment by Framstag** [comment]
Ah, OK. It is also possible that the internal mercator projection or some other internal state regarding view point instance got into an invalid state. I tried to fix that but event processing and handling of the new view point in result were not obvious. The projection should not get invalid anymore but at least other parts of the state seems to assume that changing the view point of the projection always succeed. That is something @Karry should look into. I might break more than I heal.

**Comment by aquiles2k** [comment]
Just for some visuals a gif :)

![mapbehaviour](https://user-images.githubusercontent.com/6095108/26877609-b4e971b8-4b8a-11e7-9034-b4dd522269a3.gif)

**Comment by Karry** [comment]
I am working on that... It is almost finish, I will send MR at night or tomorrow.

**Comment by Karry** [comment]
Hi @aquiles2k can you test my changes please? Behaviour of input handlers is still brute when you touch projection corners (It would be great to have some fluent animation in such case), but rendering should be fine...

**Comment by aquiles2k** [comment]
I will but im currently away until mid next week.

**Comment by Framstag** [comment]
Since an MR was issued and we had invested some effort in corner case rendering correctness in context of other issues recently, I close this one.
