### ISSUE TITLE
Importer: error while reading POLY file [russia/far-eastern-fed-district/chukotka]

### ISSUE THREAD

**Issue by rinigus** [Framstag/libosmscout#357]
I stumbled on a bug in POLY reader. Or, alternatively, used POLY file is buggy. The POLY file corresponds to one of the regions of Russia and works when I use it for creating PBF. Error is:

```
  - Parsing *.poly file 'tmp_poly/B57O2LkGL9ZlYvFdmmi2Nr1oOR6hFVjg.poly'...
   WW Way 309089722 - Should be area but is way
   WW Way 309089723 - Should be area but is way
   WW Way 309089724 - Should be area but is way
   WW Way 309089725 - Should be area but is way
   WW Way 309089726 - Should be area but is way
   WW Way 309089727 - Should be area but is way
   WW Way 309098640 - Should be area but is way
   WW Way 309098644 - Should be area but is way
   WW Datapolygon is not simple!
   !! File 'tmp_poly/B57O2LkGL9ZlYvFdmmi2Nr1oOR6hFVjg.poly' - Invalid section on line 3219
   Waiting for block processor...
   Waiting for block processor done.
```

Corresponding line in POLY is https://github.com/rinigus/osmscout-server/blob/master/scripts/import/hierarchy/russia/far-eastern-fed-district/chukotka/poly#L3219

Probably, the corresponding PBF should be http://data.gis-lab.info/osm_dump/dump/latest/RU-CHU.osm.pbf . But I am not 100% sure since I use my own PBFs derived from planet.pbf

**Comment by Framstag** [comment]
Lukas did the polygon parser, but looking the code this is not a problem of the parser but a problem of the data parsed:

The parser calls AreaIsSimple() to make sure that the polygon is OK for a bounding area. Seems like it is not?

```
   * \ingroup Geometry
   * Returns true, if the handed polygon is simple (aka not complex).
   *
   * Currently the following checks are done:
   * + Polygon has at least 3 points
   * + Assure that the line segments that make up the polygon
   *   only meet at their end points.
   */
  template<typename N>
  bool AreaIsSimple(std::vector<N> points)
```

**Comment by rinigus** [comment]
That's true - its not a simple polygon, unfortunately. Maybe we should just live with this limitation then.

**Comment by Karry** [comment]
Long story short, your Chukotka .poly file contains some duplicate coordinates:
 
 - on line 595 and 596: "162.47964 69.680839" 
 - on line 976 and 977: "179.237834 62.274264"
 
And one intersection at least (near 162.850005 69.670639).
As a result, `AreaIsSimple` method returns false...

You have two options now
 - remove duplicate coordinates and remove few lines to make it simple manually
 - create some method that will simplify polygon after preprocessing...

Water index generator rely on the fact that coastlines and clipping polygons are simple...

**Comment by rinigus** [comment]
@Karry, thank you very much for taking time and looking into it! It is embarrassing to send buggy POLY files - never though it was since it has been used for cutting regions before, sorry for that. 

I think it is fair to assume that POLY files should pass `AreaIsSimple` test. I will fix POLY file. I suggest to close this issue.

**Comment by Framstag** [comment]
Closing the issue
