### ISSUE TITLE
OpenGL renderer crash with large database (Czech Republic, Datch...)

### ISSUE THREAD

**Issue by Karry** [Framstag/libosmscout#379]
Hi. 

OpenGL renderer crash with large database (complete Czech Republic for example) on null pointer dereference inside `poly2tri` code ([full stacktrace](https://gist.github.com/Karry/94792ed08e971db3d39d04b10292ec68)).

When I test just region of Prague city, it renders polygons correctly :-)

**Comment by Framstag** [comment]
See also my comments to #377. Possibly similar causes?

**Comment by Framstag** [comment]
Not seen for a while, thus closing it.
