### ISSUE TITLE
Build Failed on Debian Jessi with Cmake

### ISSUE THREAD

**Issue by DerKleinePunk** [Framstag/libosmscout#381]
[  0%] Building CXX object libosmscout/CMakeFiles/osmscout.dir/src/osmscout/util/String.cpp.o
In file included from /home/punky/develop/libosmscout-code/libosmscout/src/osmscout/util/String.cpp:31:0:
/home/punky/develop/libosmscout-code/libosmscout/include/osmscout/private/Config.h:203:0: warning: "OSMSCOUT_HAVE_LIB_MARISA" redefined
 #define OSMSCOUT_HAVE_LIB_MARISA 1
 ^
In file included from /home/punky/develop/libosmscout-code/libosmscout/include/osmscout/util/String.h:27:0,
                 from /home/punky/develop/libosmscout-code/libosmscout/src/osmscout/util/String.cpp:20:
/home/punky/develop/libosmscout-code/build/include/osmscout/CoreFeatures.h:11:0: note: this is the location of the previous definition
 #define OSMSCOUT_HAVE_LIB_MARISA
 ^
/home/punky/develop/libosmscout-code/libosmscout/src/osmscout/util/String.cpp:451:4: error: #error "Missing implementation for std::wstring UTF8StringToWString(const std::string& text)"
   #error "Missing implementation for std::wstring UTF8StringToWString(const std::string& text)"
    ^
/home/punky/develop/libosmscout-code/libosmscout/src/osmscout/util/String.cpp:498:4: error: #error "Missing implementation for std::string WStringToUTF8String(const std::wstring& text)"
   #error "Missing implementation for std::string WStringToUTF8String(const std::wstring& text)"
    ^
libosmscout/CMakeFiles/osmscout.dir/build.make:583: recipe for target 'libosmscout/CMakeFiles/osmscout.dir/src/osmscout/util/String.cpp.o' failed
make[2]: *** [libosmscout/CMakeFiles/osmscout.dir/src/osmscout/util/String.cpp.o] Error 1
CMakeFiles/Makefile2:75: recipe for target 'libosmscout/CMakeFiles/osmscout.dir/all' failed
make[1]: *** [libosmscout/CMakeFiles/osmscout.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by DerKleinePunk** [comment]
[  0%] Building CXX object libosmscout/CMakeFiles/osmscout.dir/src/osmscout/util/String.cpp.o
In file included from /home/punky/develop/libosmscout-code/libosmscout/src/osmscout/util/String.cpp:31:0:
/home/punky/develop/libosmscout-code/libosmscout/include/osmscout/private/Config.h:203:0: warning: "OSMSCOUT_HAVE_LIB_MARISA" redefined
 #define OSMSCOUT_HAVE_LIB_MARISA 1
 ^
In file included from /home/punky/develop/libosmscout-code/libosmscout/include/osmscout/util/String.h:27:0,
                 from /home/punky/develop/libosmscout-code/libosmscout/src/osmscout/util/String.cpp:20:
/home/punky/develop/libosmscout-code/build/include/osmscout/CoreFeatures.h:11:0: note: this is the location of the previous definition
 #define OSMSCOUT_HAVE_LIB_MARISA
 ^
/home/punky/develop/libosmscout-code/libosmscout/src/osmscout/util/String.cpp:451:4: error: #error "Missing implementation for std::wstring UTF8StringToWString(const std::string& text)"
   #error "Missing implementation for std::wstring UTF8StringToWString(const std::string& text)"
    ^
/home/punky/develop/libosmscout-code/libosmscout/src/osmscout/util/String.cpp:498:4: error: #error "Missing implementation for std::string WStringToUTF8String(const std::wstring& text)"
   #error "Missing implementation for std::string WStringToUTF8String(const std::wstring& text)"
    ^
libosmscout/CMakeFiles/osmscout.dir/build.make:583: recipe for target 'libosmscout/CMakeFiles/osmscout.dir/src/osmscout/util/String.cpp.o' failed
make[2]: *** [libosmscout/CMakeFiles/osmscout.dir/src/osmscout/util/String.cpp.o] Error 1
CMakeFiles/Makefile2:75: recipe for target 'libosmscout/CMakeFiles/osmscout.dir/all' failed
make[1]: *** [libosmscout/CMakeFiles/osmscout.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by Framstag** [comment]
That should not happen. For a WStringToUTF8String implementation you either need compiler support for <codecvt> or iconv support. Since jessie is rather current both should be available. So I assume it is a problem with the feature check in CMake. I will test this locally using the jessie docker image to see if I can reproduce it.

**Comment by Framstag** [comment]
Works for me:

attached is the cmake output for the initial check. Do you have different output? Where?

```
-- The C compiler identification is GNU 4.9.2
-- The CXX compiler identification is GNU 4.9.2
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check size of void*
-- Check size of void* - done
-- Checking for 64-bit off_t
-- Checking for 64-bit off_t - present
-- Checking for _fseeki64/_ftelli64
-- Checking for _fseeki64/_ftelli64 - not found
-- Checking for fseeko/ftello
-- Checking for fseeko/ftello - present
-- Large File support - found
-- Performing Test OSMSCOUT_GCC_VISIBILITY
-- Performing Test OSMSCOUT_GCC_VISIBILITY - Success
-- Detected g++ 4.9.2

-- Enabling GCC visibility flags
-- Performing Test HAVE_ALTIVEC
-- Performing Test HAVE_ALTIVEC - Failed
-- Performing Test HAVE_AVX
-- Performing Test HAVE_AVX - Success
-- Performing Test HAVE_MMX
-- Performing Test HAVE_MMX - Success
-- Performing Test HAVE_VISIBILITY
-- Performing Test HAVE_VISIBILITY - Success
-- Looking for dlfcn.h
-- Looking for dlfcn.h - found
-- Looking for fcntl.h
-- Looking for fcntl.h - found
-- Looking for inttypes.h
-- Looking for inttypes.h - found
-- Looking for memory.h
-- Looking for memory.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stdlib.h
-- Looking for stdlib.h - found
-- Looking for strings.h
-- Looking for strings.h - found
-- Looking for string.h
-- Looking for string.h - found
-- Looking for sys/stat.h
-- Looking for sys/stat.h - found
-- Looking for sys/time.h
-- Looking for sys/time.h - found
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for unistd.h
-- Looking for unistd.h - found
-- Looking for C++ include codecvt
-- Looking for C++ include codecvt - not found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of int16_t
-- Check size of int16_t - done
-- Check size of int32_t
-- Check size of int32_t - done
-- Check size of int64_t
-- Check size of int64_t - done
-- Check size of int8_t
-- Check size of int8_t - done
-- Check size of long long
-- Check size of long long - done
-- Check size of uint16_t
-- Check size of uint16_t - done
-- Check size of uint32_t
-- Check size of uint32_t - done
-- Check size of uint64_t
-- Check size of uint64_t - done
-- Check size of uint8_t
-- Check size of uint8_t - done
-- Check size of unsigned long long
-- Check size of unsigned long long - done
-- Check size of wchar_t
-- Check size of wchar_t - done
-- Looking for mmap
-- Looking for mmap - found
-- Looking for posix_fadvise
-- Looking for posix_fadvise - found
-- Looking for posix_madvise
-- Looking for posix_madvise - found
-- Looking for mallinfo
-- Looking for mallinfo - found
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.28") 
-- Found MARISA: /usr/include  
-- Found LibXml2: /usr/lib/x86_64-linux-gnu/libxml2.so (found version "2.9.1") 
-- Looking for include file pthread.h
-- Looking for include file pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found PROTOBUF: /usr/lib/x86_64-linux-gnu/libprotobuf.so  
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.8") 
-- Performing Test ICONV_HAVE_WERROR
-- Performing Test ICONV_HAVE_WERROR - Success
-- Performing Test ICONV_SECOND_ARGUMENT_IS_CONST
-- Performing Test ICONV_SECOND_ARGUMENT_IS_CONST - Failed
-- Found ICONV: /usr/include  
-- Could NOT find LIBLZMA (missing:  LIBLZMA_INCLUDE_DIRS LIBLZMA_LIBRARIES) 
-- checking for module 'cairo'
--   found cairo, version 1.14.0
-- Found Cairo: /usr/lib/x86_64-linux-gnu/libcairo.so  
-- Found LIBAGG: /usr/include  
-- Found Freetype: /usr/lib/x86_64-linux-gnu/libfreetype.so (found version "2.5.2") 
-- Found Pango: /usr/include/pango-1.0  
-- Found Glib2: /usr/include/glib-2.0;/usr/lib/x86_64-linux-gnu/glib-2.0/include  
-- Found Gobject: /usr/include/glib-2.0;/usr/lib/x86_64-linux-gnu/glib-2.0/include  
-- Found Pangocairo: /usr/include/pango-1.0  
-- checking for module 'fontconfig'
--   found fontconfig, version 2.11.0
-- Found Fontconfig: /usr/lib/x86_64-linux-gnu/libfontconfig.so  
-- Found Pangoft2: /usr/include/pango-1.0;/usr/include/glib-2.0;/usr/lib/x86_64-linux-gnu/glib-2.0/include;/usr/include/glib-2.0;/usr/lib/x86_64-linux-gnu/glib-2.0/include;/usr/include/pango-1.0;/usr/include/pango-1.0;/usr/include/freetype2;/usr/include  
-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so
-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for connect
-- Looking for connect - found
-- Looking for remove
-- Looking for remove - found
-- Looking for shmat
-- Looking for shmat - found
-- Looking for IceConnectionNumber in ICE
-- Looking for IceConnectionNumber in ICE - found
-- Found X11: /usr/lib/x86_64-linux-gnu/libX11.so
-- Xrandr library not found - required for GLFW
-- Xcursor library not found - required for GLFW
-- Xinerama library not found - required for GLFW
-- Xi library not found - required for GLFW
-- Try OpenMP C flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Try OpenMP CXX flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Could NOT find GPERFTOOLS (missing:  GPERFTOOLS_INCLUDE_DIRS GPERFTOOLS_LIBRARIES) 
Skip DrawMapDirectX demo, libosmscout-map-directx is missing.
-- libosmscout build configuration:
-- Shared libraries:                        ON
-- core library:                            ON
-- import library:                          ON
-- map drawing interface:                   ON
--  - Agg map drawing backend:              ON
--  - Cairo map drawing backend:            ON
--  - OpenGL map drawing backend:           OFF
--  - DirectX map drawing backend:          OFF
--  - Qt map drawing backend:               ON
--  - SVG map drawing backend:              ON
--  - Map drawing backend for iOS and OS X: OFF
-- client libraries:
--  - Qt client library:                    ON
-- tools:
--  - Import/BasemapImport:                 ON
--  - DumpData:                             ON
--  - OSMScout2:                            ON
--  - OSMScoutOpenGL:                       OFF
--  - StyleEditor:                          ON
-- tests:                                   ON
-- demos:                                   ON
--  - heap profiler (Gperftools)            OFF
-- bindings:
--  - Java binding:                         OFF
--  - C# binding:                           OFF
-- external interfaces:
--  - MATLAB mex function:                  OFF
-- documentation:                           OFF
-- Configuring done
-- Generating done
```

**Comment by Framstag** [comment]
@DerKleinePunk: Have you been able to take a look if there is a difference in CMake output on your system?

**Comment by DerKleinePunk** [comment]
punky@VirtualBoxSam:~/develop/libosmscout-code/build$ cmake ..
-- The C compiler identification is GNU 4.9.2
-- The CXX compiler identification is GNU 4.9.2
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check size of void*
-- Check size of void* - done
-- Checking for 64-bit off_t
-- Checking for 64-bit off_t - present with _FILE_OFFSET_BITS=64
-- Checking for _fseeki64/_ftelli64
-- Checking for _fseeki64/_ftelli64 - not found
-- Checking for fseeko/ftello
-- Checking for fseeko/ftello - present
-- Large File support - found
-- Performing Test OSMSCOUT_GCC_VISIBILITY
-- Performing Test OSMSCOUT_GCC_VISIBILITY - Success
-- Detected g++ 4.9.2

-- Enabling GCC visibility flags
-- Performing Test HAVE_ALTIVEC
-- Performing Test HAVE_ALTIVEC - Failed
-- Performing Test HAVE_AVX
-- Performing Test HAVE_AVX - Success
-- Performing Test HAVE_MMX
-- Performing Test HAVE_MMX - Success
-- Performing Test HAVE_VISIBILITY
-- Performing Test HAVE_VISIBILITY - Success
-- Looking for dlfcn.h
-- Looking for dlfcn.h - found
-- Looking for fcntl.h
-- Looking for fcntl.h - found
-- Looking for inttypes.h
-- Looking for inttypes.h - found
-- Looking for memory.h
-- Looking for memory.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stdlib.h
-- Looking for stdlib.h - found
-- Looking for strings.h
-- Looking for strings.h - found
-- Looking for string.h
-- Looking for string.h - found
-- Looking for sys/stat.h
-- Looking for sys/stat.h - found
-- Looking for sys/time.h
-- Looking for sys/time.h - found
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for unistd.h
-- Looking for unistd.h - found
-- Looking for C++ include codecvt
-- Looking for C++ include codecvt - not found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of int16_t
-- Check size of int16_t - done
-- Check size of int32_t
-- Check size of int32_t - done
-- Check size of int64_t
-- Check size of int64_t - done
-- Check size of int8_t
-- Check size of int8_t - done
-- Check size of long long
-- Check size of long long - done
-- Check size of uint16_t
-- Check size of uint16_t - done
-- Check size of uint32_t
-- Check size of uint32_t - done
-- Check size of uint64_t
-- Check size of uint64_t - done
-- Check size of uint8_t
-- Check size of uint8_t - done
-- Check size of unsigned long long
-- Check size of unsigned long long - done
-- Check size of wchar_t
-- Check size of wchar_t - done
-- Looking for mmap
-- Looking for mmap - found
-- Looking for posix_fadvise
-- Looking for posix_fadvise - found
-- Looking for posix_madvise
-- Looking for posix_madvise - found
-- Looking for mallinfo
-- Looking for mallinfo - found
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.28") 
-- Found MARISA: /usr/include  
-- Looking for include file pthread.h
-- Looking for include file pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found PROTOBUF: /usr/lib/i386-linux-gnu/libprotobuf.so  
-- Performing Test ICONV_HAVE_WERROR
-- Performing Test ICONV_HAVE_WERROR - Success
-- Performing Test ICONV_SECOND_ARGUMENT_IS_CONST
-- Performing Test ICONV_SECOND_ARGUMENT_IS_CONST - Failed
-- Found ICONV: /usr/include  
-- Found LIBLZMA: /usr/include  
-- checking for module 'cairo'
--   found cairo, version 1.14.0
-- Found LIBAGG: /usr/include  
-- Found Pango: /usr/include/pango-1.0  
-- Found Pangocairo: /usr/include/pango-1.0  
-- Found Freetype: /usr/lib/i386-linux-gnu/libfreetype.so (found version "2.5.2") 
-- Found Pangoft2: /usr/include/pango-1.0  
-- Found Glib2: /usr/include/glib-2.0;/usr/lib/i386-linux-gnu/glib-2.0/include  
-- Found Gobject: /usr/include/glib-2.0;/usr/lib/i386-linux-gnu/glib-2.0/include  
-- Looking for XOpenDisplay in /usr/lib/i386-linux-gnu/libX11.so;/usr/lib/i386-linux-gnu/libXext.so
-- Looking for XOpenDisplay in /usr/lib/i386-linux-gnu/libX11.so;/usr/lib/i386-linux-gnu/libXext.so - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for connect
-- Looking for connect - found
-- Looking for remove
-- Looking for remove - found
-- Looking for shmat
-- Looking for shmat - found
-- Looking for IceConnectionNumber in ICE
-- Looking for IceConnectionNumber in ICE - found
-- Found X11: /usr/lib/i386-linux-gnu/libX11.so
-- Try OpenMP C flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Try OpenMP CXX flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Found GPERFTOOLS: /usr/include  
Skip DrawMapDirectX demo, libosmscout-map-directx is missing.
-- libosmscout build configuration:
-- Shared libraries:                        ON
-- core library:                            ON
-- import library:                          ON
-- map drawing interface:                   ON
--  - Agg map drawing backend:              ON
--  - Cairo map drawing backend:            ON
--  - OpenGL map drawing backend:           ON
--  - DirectX map drawing backend:          OFF
--  - Qt map drawing backend:               ON
--  - SVG map drawing backend:              ON
--  - Map drawing backend for iOS and OS X: OFF
-- client libraries:
--  - Qt client library:                    ON
-- tools:
--  - Import:                               ON
--  - DumpData:                             ON
--  - OSMScout2:                            ON
--  - StyleEditor:                          ON
-- tests:                                   ON
-- demos:                                   ON
--  - heap profiler (Gperftools)            ON
-- bindings:
--  - Java binding:                         OFF
--  - C# binding:                           OFF
-- external interfaces:
--  - MATLAB mex function:                  OFF
-- documentation:                           ON
-- Configuring done
-- Generating done
-- Build files have been written to: /home/punky/develop/libosmscout-code/build

...

In file included from /home/punky/develop/libosmscout-code/libosmscout-import/src/osmscout/import/PreprocessPoly.cpp:27:0:
/home/punky/develop/libosmscout-code/libosmscout-import/include/osmscout/private/Config.h:64:0: warning: "OSMSCOUT_IMPORT_HAVE_LIB_MARISA" redefined
 #define OSMSCOUT_IMPORT_HAVE_LIB_MARISA 1
 ^
In file included from /home/punky/develop/libosmscout-code/libosmscout-import/include/osmscout/import/Import.h:27:0,
                 from /home/punky/develop/libosmscout-code/libosmscout-import/include/osmscout/import/Preprocessor.h:30,
                 from /home/punky/develop/libosmscout-code/libosmscout-import/include/osmscout/import/PreprocessPoly.h:27,
                 from /home/punky/develop/libosmscout-code/libosmscout-import/src/osmscout/import/PreprocessPoly.cpp:25:
/home/punky/develop/libosmscout-code/build/include/osmscout/ImportFeatures.h:6:0: note: this is the location of the previous definition
 #define OSMSCOUT_IMPORT_HAVE_LIB_MARISA

...

Now is Building i don't it was last big Debian Update or i am to stupid to rebuild now it works.
