### ISSUE TITLE
OpenGL renderer: Added debug ouput to show zoom level

### ISSUE THREAD

**Issue by Framstag** [Framstag/libosmscout#397]
It would be nice if the demo application could have debug output showing the center or the cooridnat ebounding box and the zoom level. Similar to OSMScout2 (a sub set of the output is OK).

**Comment by Framstag** [comment]
I do not see any debug output regarding zoom level? How should it look like?

**Comment by fannymonori** [comment]
I left zooming level out from the debug output, but I'm about to finish some work on zoom (among others) and I will include the output there.
