### ISSUE TITLE
Leave roundabout (0. exit)

### ISSUE THREAD

**Issue by vyskocil** [Framstag/libosmscout#428]
With the provided database (database.zip) compiled from Routing.osm, if I use the Routing demo like this : 

`./Routing  --router routecar ./database  43.616106 6.972507 43.615580 6.972020`

In the route description we could read "Leave roundabout (0. exit)" but in fact the route takes the first exit.

Here is the full output of the command : 

```
No speed for type 'highway_residential_area' defined!
No speed for type 'highway_service_area' defined!
From:                43.61611 N 6.97250 E Way 4833[8 *> 3238131295059865857]
To:                  43.61557 N 6.97199 E Way 4048[3238131286460248577 >* 0]
Time:                0.000
Air-line distance:   0.1km
Minimum cost:        0.0
Actual cost:         0.0
Cost limit:          0.5
Route nodes loaded:  17
Route nodes ignored: 20
Max. OpenList size:  6
Max. ClosedSet size: 17
----------------------------------------------------
     At| After|  Time| After|
----------------------------------------------------
  0.0km         0:00h        Start at 'Start'
                             Drive along highway_service <unknown name>
  0.0km  0.0km  0:00h  0:00h At crossing 'unnamed road'
                             Enter roundabout
  0.0km  0.0km  0:00h  0:00h Leave roundabout (0. exit) into street 'Route de la Roquette (D 409)'
  0.0km  0.0km  0:00h  0:00h Target reached 'Target'
```

[database.zip](https://github.com/Framstag/libosmscout/files/1180262/database.zip)
[Routing.osm.zip](https://github.com/Framstag/libosmscout/files/1180287/Routing.osm.zip)

**Comment by Karry** [comment]
It is funny :-) Navigation for programmers... Is this roundabout special or is this bug general?

**Comment by vyskocil** [comment]
I looked a this roundabout with JOSM editor but found nothing special with it... Here it is : 
<img width="957" alt="screen shot 2017-07-29 at 12 10 04" src="https://user-images.githubusercontent.com/452704/28743968-f1aa3f3e-7456-11e7-9a8b-9717a06c44f5.png">

**Comment by Framstag** [comment]
OK, I can reproduce it. Looks like the start and end are positioned to just lead you trough the roundabout. Strange...

**Comment by Framstag** [comment]
OK, start the highway_service coming from north west into the roundabout. Looks like the calculation regarding the number of exits is wrong. Will dive into this code to see what is happening and why.

**Comment by Framstag** [comment]
Just some infos for my personal debugging:
* The route starts with way 4821 (looks like a merge of https://www.openstreetmap.org/way/21407757, https://www.openstreetmap.org/way/212726216 and https://www.openstreetmap.org/way/212726213)
* The roundabout is way 4292 (https://www.openstreetmap.org/way/4688801)
* The entering crossing is node serial 3238131290776834817 (4821[10]==4292[15])
* The exiting crossing is at node serial 3238131290775653633, which is 4292[0] and 4292[16]!! and 4243[0] (https://www.openstreetmap.org/way/209101833)

**Comment by Framstag** [comment]
I tried to fix the problem. Please check (with a number of roundabouts).

**Comment by vyskocil** [comment]
It's ok for me, It even seems to fix a old problem I saw in a roundabout near my home ! In the old case the roundabout is split with bridges and when entering into it and leaving in the next exit the description wasn't event talking about a roundabout, it was treated as a simple turn.
