### ISSUE TITLE
Error when trying to route for pedestrians

### ISSUE THREAD

**Issue by vyskocil** [Framstag/libosmscout#429]
When I ask for a route for pedestrians libosmscout give me the following error : 

`Assertion failed: (it!=junctionTypes.end()), function LoadJunction, file /Users/vyskocil/Dev/libosmscout/libosmscout/src/osmscout/routing/RoutePostprocessor.cpp, line 1229.`

It appends because when routing for walking (or biking,…) the `std::set<std::string> junctionTypeNames` passed to :

```
postprocessor.PostprocessRouteDescription(description,
                                                       profiles,
                                                       databases,
                                                       postprocessors,
                                                       motorwayTypeNames,
                                                       motorwayLinkTypeNames,
                                                       junctionTypeNames)

```
Is empty but there is no error when routing for cars and `junctionTypeNames = {"highway_motorway_junction”}`

**Comment by vyskocil** [comment]
Initializing the last 3 parameters like this in the client code : 
```
        std::set<std::string> motorwayTypeNames = {""};
        std::set<std::string> motorwayLinkTypeNames = {""};
        std::set<std::string> junctionTypeNames = {""};
```
Seems to fix the bug but it's a kind of hack...

**Comment by Karry** [comment]
Hi Vladimir, it should be possible to omit type names from initialisation of route postprocessing now. But then some description postprocessors will not work properly, like motorway junction...

Can we close it?

**Comment by vyskocil** [comment]
Hi Kerry, it's ok for me, in the case of pedestrian or bike routing we should not have to describe motorway junction precisely because motorway type are not flagged as routable for these kind of vehicles !
