### ISSUE TITLE
Navigation support

### ISSUE THREAD

**Issue by Karry** [Framstag/libosmscout#443]
Hi. When I was thinking about adding support for real time navigation to my app, few things are missing that would be nice to have in library. I imagine some navigation service that:

 - have route way and route description as an input
 - consume current car position periodically, and quess current position on some database way 
 - guess position in tunnel without gps signal
 - trigger re-routing when driver turns to different than computed direction on junction 
 - trigger voice command before junction (roundabout, highway exit...)

**Comment by vyskocil** [comment]
Hi ! 
There is already a simple Navigation class I pushed into libosmscout some years ago, see 
[https://github.com/Framstag/libosmscout/blob/master/libosmscout/include/osmscout/Navigation.h](https://github.com/Framstag/libosmscout/blob/master/libosmscout/include/osmscout/Navigation.h)
It could be extended with these new functionalities.

**Comment by vyskocil** [comment]
I'll add soon a sample application in the Demos directory to explain the usage of the Navigation class

**Comment by Karry** [comment]
Nice :-) I overlook it. Some demo would be great. I will experiment with it when will be back from vacation...

**Comment by vyskocil** [comment]
I just made a pull request for a demo application (tested in Prague where I'm in holidays :-)

**Comment by DerKleinePunk** [comment]
I need this function too

**Comment by Framstag** [comment]
@Karry , @vyskocil: I added a bunch of classes for further navigation support a while ago. AFAIK @Karry has started to use them and signal that the help to further support implemention of navigation support.

Was is still missing to further support navigation support? Thinking of testing, helper functions etc...?

**Comment by Karry** [comment]
There is multiple areas for improvements (voice commands, support for lanes, improve description, testing...). But the scope of original ticket is more or less covered. You can close it I think.
