### ISSUE TITLE
Describe coordinate as location close to a POI

### ISSUE THREAD

**Issue by Framstag** [Framstag/libosmscout#45]
LocationService allows to describe a geo coordinate in relation to objects in the database.

In this case describe a coordinate in relation to a nearby POI.

Example:
"30m meters north top Rewe shop".

**Comment by Framstag** [comment]
How to implement:
* Get all types that have POI set in the map.os file (TypeConfig.getTypes(), TypeInfo.getIndexAsPOI()).
* Load from database all nodes, ways, areas of this type in a given bounding box around the input coordinate
* Find the closest object
* Describe location in relation to this closest POI
* If you like, you can do a reverse lookup in the LocationService for this POI, to get its full adress

**Comment by Karry** [comment]
I think that https://github.com/Framstag/libosmscout/pull/66 already solves this, because all POIs are written to location index a has addresses or not? Exist some POI type that don't have address? 

When I try position near restaurant, I get:

    ./Demos/LocationDescription prague-db 50.0892662 14.4983222
    Coordinate: 50.08927 N 14.49832 E
    0.1m W of address: Mille Miglia Ristorante, Žižkov
        POI:      Mille Miglia Ristorante
        region:   Žižkov

**Comment by Framstag** [comment]
Yes and no. With current functionality you get the closest address what ever this will be (likely just some house where some people live). It will likely not be a POI.

Here you are explicitly for the next POI and its address, this will likely not be the closest address. 

Why making the difference.

If I want to call for police I would just give relative position to the closest address. IF I want to describe my location to somebody that knows the region but not every street name and address and position relative to a POI might be more helpful. Think of trying to meet with somebody via phone in a pedestrian zone in a bigger city. People likely know shops but no streets.

Of course, if you find a POI, it will have an address is most cases :-) But that is not the point here.

**Comment by Framstag** [comment]
Implemented.
