### ISSUE TITLE
SimpleRoutingService::GetClosestRoutableNode() use profile.CanUse(way)

### ISSUE THREAD

**Issue by vyskocil** [Framstag/libosmscout#453]
I found why some ways are discarded as candidate for routing starting node. GetClosestRoutableNode() use the CanUse(way) method from the routing profile : 
```
...
    for (const auto& way : ways) {
      if (!profile.CanUse(*way)) {
        continue;
      }
...
```
But the method CanUse() take into account AccessFeatureValue like one way attribute, for example when vehicle is vehicleCar this call : 
```
    inline bool CanRouteCar() const
    {
      return (access & carForward)!=0 &&
             (access & carBackward)!=0;
    }
```
And for oneway roads this is false, which in consequence drop the road from the selection.
In the case of searching closest routable node for starting or arriving node we should not care of the oneway attribute of the ways or as a evolution we could pass a optional vector with the current car direction and select the road with matching orientation (with delta around the exact orientation) when they are oneway.

**Comment by vyskocil** [comment]
I tried to add a method `CanUseWithoutAccess()` to routing profile and use it instead of `CanUse()`
 in `GetClosestRoutableNode()` and it seems to be ok now : 
```
  bool AbstractRoutingProfile::CanUseWithoutAccess(const Way& way) const
  {
    size_t index=way.GetType()->GetIndex();

    if (index>=speeds.size() || speeds[index]<=0.0) {
      return false;
    }
        
    switch (vehicle) {
      case vehicleFoot:
        return way.GetType()->CanRouteFoot();
          break;
        case vehicleBicycle:
          return way.GetType()->CanRouteBicycle();
          break;
        case vehicleCar:
          return way.GetType()->CanRouteCar();
          break;
        }
      
    return false;
  }
```

What do you think about this ?

**Comment by vyskocil** [comment]
Maybe AccessFeatureValue should still be taken into account but for car modify the `CanRouteCar()` metod using a` ||` between  `(access & carForward)!=0` and `(access & carBackward)!=0` to keep the way if at least one direction is routable ?

**Comment by Framstag** [comment]
The principle analysis looks correct. This might also be the reason why the routing example in the other issue did not work.

Using/Implementing `CanUseWithoutAccess` would be the wrong solution IMHO. This would only tell, if routing by car is allowed solely based on the type of the way. There will however likely be mappings where using a car is not allowed for a *instance* of a type, while in general the type would allow routing. So checking access is required in principle.

IMHO the better solution would be to exchange the `&&` comparison with an `||`, thus returning true (as you suggested afterwards), if you can either route forward or backward. If I take a look at the calls to CanRouteCar(), the only code that will break, is the DumpData code, which could be easily be fixed (by separate calls to `CanRouteForward()` and `CanRouteBackward()`).

**Comment by vyskocil** [comment]
Ok, just made a pull request with the second solution and updating DumpData code

**Comment by vyskocil** [comment]
The pull request has been merged
