### ISSUE TITLE
LICENSE Questions for the iOS AppStore

### ISSUE THREAD

**Issue by larsmango** [Framstag/libosmscout#463]
I have read that the LGPLlicense can sometimes be difficult to apply when uploading an app to the AppStore using a LGPL-licensed framework (lets say libosmscout).

I have seen this interesting aspect on the [LICENSE](https://github.com/Framstag/libosmscout/blob/master/LICENSE) page of this git repository:

> Statically linking the libosmscout libraries into a user application
>    distributed on the Apple App Store or Apple Mac App Store does not make
>    the user application a derived work.

Could someone help me with that? Is it ok to publish apps on the AppStore that use libosmscout?

**Comment by Framstag** [comment]
This was a license clause especially added to make sure and visible, that using libosmsocut on iOS is allowed. There is some unclearness in the LGPL this additional clause wants to make clear.

**Comment by larsmango** [comment]
That makes sense, thanks for clarifying!

Closing this issue now, since this has been resolved.
