### ISSUE TITLE
iOS: Text sometimes overlapping

### ISSUE THREAD

**Issue by larsmango** [Framstag/libosmscout#464]
I noticed that sometimes street names overlap when displaying tiles on iOS. Especially for streets that have two lanes (e.g. highways) it can happen that both sides get an own label that overlap slightly (or completely).

**Comment by Framstag** [comment]
Can you please add an example image for this bug, too?

**Comment by larsmango** [comment]
Here's an example where the text overlays:
![overlay_bug](https://user-images.githubusercontent.com/31371712/29803961-178096e6-8c34-11e7-844c-4a09dc6d29be.PNG)

**Comment by Framstag** [comment]
Wow, that does not look good and is certainly something I have not see before. But I have to admit that we do not have code to actively avoid such situation. Could thus be a corner case. Can you give us geo coords or boundingbox (and *.osm.pbf download, too) so we can reproduce it locally?

**Comment by vyskocil** [comment]
The two labels on each lanes are drawn in the opposite direction ! I remember that there is some code that try to find the good orientation for these labels... Maybe the nodes of theses two lanes are  in opposite directions in OSM.

Ironically in the iOS/OSX rendering code there is a very lame algorithm to try to avoid such overlapping when there is the same label for two lanes but it fails in some cases and this one seems to be one !

**Comment by Framstag** [comment]
We now have much more information in the rendering base class (IMHO initial the base class had no information regarding the bounding box, this information is now available), so it should be possible to move your code into the base class.

**Comment by Framstag** [comment]
This is a duplicate to #287
