### ISSUE TITLE
Create .framework for iOS apps

### ISSUE THREAD

**Issue by larsmango** [Framstag/libosmscout#472]
Do you know if it is possible to create a framework from the libosmscout Xcode project which then can be used in existing Xcode projects?

**Comment by vyskocil** [comment]
It is on my todo list

**Comment by RandyHBH** [comment]
There is somo guide to integrate libosmscout in an iOS app?? Any iOS app example? I could find nothing in the docs.
Thanks in advanced

**Comment by Framstag** [comment]
There is the build guide that mentions also OS X: http://libosmscout.sourceforge.net/documentation/source/

There is also a special demo for OS X (apple/OSMScoutOSX) that show how to to integrate libosmsocut into the apple rendering framework (there was also some recent discussion on the mailing list and some traffic in the issue tracker about this).

If you would like to work more low level the libosmscout-client-qt library gives you very detailed information regarding a Qt integration and there are the more general and low level demos in the Demos directory.

It may make sense to ask/describe on the list how you would like to implement the rendering in to your app to get general feedback, too. We can render tiles but also "full image". You would like to integrate into an existing framework or would like to do things on your own...There are a number of options with advantages and disadvantages each.

**Comment by vyskocil** [comment]
I'm working on the CMake build for iOS and just had a successful compilation ! 
I'll try to add framework generation for iOS and OSX, then it will be easy to build and re-use the libs and the demo app for these platforms.

**Comment by larsmango** [comment]
@vyskocil that sounds amazing. Cant wait to try it out :)

**Comment by vyskocil** [comment]
iOS and OSX Framework creation is now done when using CMake to build
