### ISSUE TITLE
Rotation in Qt

### ISSUE THREAD

**Issue by arpio** [Framstag/libosmscout#478]
The rotation is not working in Qt. I see the comments in the code. Would just like to know if someone is working on it.

I'm not a professional software developer. I'm just playing a little bit with QML, so I don't have the knowledge to fix the issue.

Anybody? Please.

**Comment by Karry** [comment]
As I know, noone is working on it. There is need to add support for rotating into input handlers and map renderers (in qt client library). Any special programming skills are required for this, just geometric transformations and great imagination...

**Comment by Framstag** [comment]
Rotation is in principle working. You can pass an angle to the Projection to get rotated coordinates. The problem as Karry said, is that the new code qt client library does not make use of it. I assume that it was dropped at the time where external tile support was integration, since this does not harmonize well with rotation. But in case where the map rendering comes from libosmscout and you are not rendering tiles but fullscreen this can be support and should be simple. I assume that it is more complicated in the existing code to handle no rotation in tile view ;-)

**Comment by arpio** [comment]
Well, thanks guys. Will see how far I'll get with my skills.

**Comment by Framstag** [comment]
That would be cool, if you have any questions, just ask!

**Comment by arpio** [comment]
So, would need an advise. In the PlaneMapRenderer.cpp at the line 204 the painter draws the image from the source Rect to target Rect. The rectangles dimensions are wrong if the angle is not 0.0

I get the right image and rotation is working if I use the 0.0 angel at lines 148 and 160 to get the right Rectangles for the painter.

But then the movement and zoom are not smooth anymore.

**Comment by Karry** [comment]
Can you publish your fork please? I will try it...

**Comment by arpio** [comment]
https://github.com/arpio/libosmscout

**Comment by arpio** [comment]
I think I've got it. Just gotta clean up the code. Will update my fork soon.

**Comment by arpio** [comment]
Have updated my fork. It works for me now. The zoom is not perfect, some of the roads disappear at high zoom level.
![screenshot_20170926_211315](https://user-images.githubusercontent.com/24844259/30894586-f0034f02-a301-11e7-8e15-9e53602d8690.png)
![screenshot_20170926_211402](https://user-images.githubusercontent.com/24844259/30894587-f004521c-a301-11e7-8075-a221a9f642d9.png)

**Comment by arpio** [comment]
Add animated rotation. Any suggestions to the high zoom level and disappearing of some roads?

**Comment by Karry** [comment]
These roads disappears when angle is 0.0 ? I remember that there is some bug directly in renderer (data loading?) that is causing it when angle is not zero... We may solve this bug later.

**Comment by Karry** [comment]
Hmm, this bug is closed already https://github.com/Framstag/libosmscout/issues/81 . But fix was just for areas. It is possible that similar bug still exists for ways... (Renderer drops too small objects, but dimension computation for rotated objects was wrong) Please give me few days, I take a look at your changes...

**Comment by arpio** [comment]
Yes it looks like the same issue https://github.com/Framstag/libosmscout/issues/81 There is also a part of the highway which disappeared in the last two pictures.

**Comment by Karry** [comment]
Hi Alexander.

It looks good. But zoom and angle animations are not smooth anymore. Take a look to my [smooth-plane-rotation](https://github.com/Karry/libosmscout/tree/smooth-plane-rotation) branch.

I saw few renderer issues when I was playing with it, include some route disappearing :-( As I said, we can fix these issues later. As rotation was not supported in our demo last months, noone really test it.

If you are fine with my update, you can cherry-pick this commit and prepare merge request :-)

**Comment by arpio** [comment]
Cool!!! Works for me. But I'm still not familiar with git. Can you make the pull request then?

**Comment by arpio** [comment]
Can we not just check if the BoundingBox intersects with the Projection https://github.com/arpio/libosmscout/commit/30d35ba8fca6f39bcb162c2a487c0e93bfd8c7c4?

No disappearing of roads or rivers anymore.

**Comment by Framstag** [comment]
I would like to close the issue, since rotation is now implemented? Regarding the possibly wrong clipping you can make a new issue, please?

**Comment by arpio** [comment]
Done
