### ISSUE TITLE
Compiling iOS cannot open file 

### ISSUE THREAD

**Issue by jojonarte** [Framstag/libosmscout#480]
File '/Users/vlad/Desktop/France.osmscout/types.dat' - Cannot open file for reading: No such file or directory
Cannot load 'types.dat'!
Cannot open database
Assertion failed: (isMapPainterConfigured), function drawMap, file /Users/dna/Desktop/development/native/ios/libfork/libosmscout/Apple/OSMScoutOSX/OSMScoutOSX/OSMScout.mm, line 68.

**Comment by vyskocil** [comment]
You have to modify the define that tell where to find the map used for the demo when using the Simulator

**Comment by jojonarte** [comment]
Is the map generated along with the make full? If yes where could I find it.

**Comment by Framstag** [comment]
No, you must first sucessfully build the Import tool together with the libraries required by it. After the build you can then generate a database from a *.osm.pbf or *.osm file.

See http://libosmscout.sourceforge.net/tutorials/importing/ for details

**Comment by jojonarte** [comment]
Okay I got it now, I was able to successfully get off that early error by running the importer tool based on the website documentation but I get a new error after replacing the OSMSCOUTDATA path with the new path.

Error below:

File '/Users/dna/Desktop/development/native/ios/libfork/libosmscout/maps/nordrhein-westfalen/standard.oss' - Opening file: No such file or directory
Cannot open style
Assertion failed: (isMapPainterConfigured), function drawMap, file /Users/dna/Desktop/development/native/ios/libfork/libosmscout/Apple/OSMScoutOSX/OSMScoutOSX/OSMScout.mm, line 68.

**Comment by jojonarte** [comment]
Update:
I was able to make it work by copying the standard.oss from /stylesheets/ folder

**Comment by jojonarte** [comment]
Update: i tried running on an iPad I got a different error
2017-09-20 04:15:14.606787 OSMScoutiOS[229:5907] [GEODBWriter] 21.1 /BuildRoot/Library/Caches/com.apple.xbs/Sources/GeoServices/GeoServices-1228.32.8.29.13/GEODBWriter.mm:613 Could not open database (/var/mobile/Library/Caches/com.apple.geod/MapTiles/MapTiles.sqlitedb): (14) unable to open database file
2017-09-20 04:15:14.609535 OSMScoutiOS[229:5909] [GEODBWriter] 23.1 /BuildRoot/Library/Caches/com.apple.xbs/Sources/GeoServices/GeoServices-1228.32.8.29.13/GEODBWriter.mm:613 Could not open database (/var/mobile/Library/Caches/com.apple.geod/MapTiles/MapTiles.sqlitedb): (14) unable to open database file
2017-09-20 04:15:14.648244 OSMScoutiOS[229:5953] [GEODBWriter] 26.1 /BuildRoot/Library/Caches/com.apple.xbs/Sources/GeoServices/GeoServices-1228.32.8.29.13/GEODBWriter.mm:442 SQL error: (21) out of memory
File '/var/mobile/Containers/Data/Application/3D595F74-1F79-4FE2-8699-777D4CFFDCBB/Documents/types.dat' - Cannot open file for reading: No such file or directory
Cannot load 'types.dat'!
Cannot open database
Assertion failed: (isMapPainterConfigured), function drawMap, file /Users/dna/Desktop/development/native/ios/libfork/libosmscout/Apple/OSMScoutOSX/OSMScoutOSX/OSMScout.mm, line 68.

**Comment by vyskocil** [comment]
When running on a real device, iPhone or iPad, you must copy the map to the device before trying to use it !
The App is looking for the map files in its Documents folder, you should copy them using iTunes.

**Comment by jojonarte** [comment]
oh my bad
