### ISSUE TITLE
Cmake Error

### ISSUE THREAD

**Issue by jojonarte** [Framstag/libosmscout#481]
This is the CmakeError.log

Performing C SOURCE FILE Test HAVE_ALTIVEC failed with the following output:
Change Dir: /Users/dna/Desktop/development/native/ios/libfork/sss/libosmscout-code/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/xcodebuild" "-project" "CMAKE_TRY_COMPILE.xcodeproj" "build" "-target" "cmTC_99d02" "-configuration" "Debug"
=== BUILD TARGET cmTC_99d02 OF PROJECT CMAKE_TRY_COMPILE WITH CONFIGURATION Debug ===

Check dependencies

Write auxiliary files
/bin/mkdir -p /Users/dna/Desktop/development/native/ios/libfork/sss/libosmscout-code/build/CMakeFiles/CMakeTmp/CMAKE_TRY_COMPILE.build/Debug/cmTC_99d02.build/Objects-normal/x86_64
write-file /Users/dna/Desktop/development/native/ios/libfork/sss/libosmscout-code/build/CMakeFiles/CMakeTmp/CMAKE_TRY_COMPILE.build/Debug/cmTC_99d02.build/Objects-normal/x86_64/cmTC_99d02.LinkFileList

CompileC CMAKE_TRY_COMPILE.build/Debug/cmTC_99d02.build/Objects-normal/x86_64/src.o src.c normal x86_64 c com.apple.compilers.llvm.clang.1_0.compiler
    cd /Users/dna/Desktop/development/native/ios/libfork/sss/libosmscout-code/build/CMakeFiles/CMakeTmp
    export LANG=en_US.US-ASCII
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x c -arch x86_64 -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -Wno-trigraphs -fpascal-strings -O0 -Wno-missing-field-initializers -Wno-missing-prototypes -Wno-return-type -Wno-missing-braces -Wparentheses -Wswitch -Wno-unused-function -Wno-unused-label -Wno-unused-parameter -Wno-unused-variable -Wunused-value -Wno-empty-body -Wno-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wno-constant-conversion -Wno-int-conversion -Wno-bool-conversion -Wno-enum-conversion -Wno-shorten-64-to-32 -Wpointer-sign -Wno-newline-eof -DCMAKE_INTDIR=\"Debug\" -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -fasm-blocks -fstrict-aliasing -Wdeprecated-declarations -mmacosx-version-min=10.11 -g -Wno-sign-conversion -Wno-infinite-recursion -I/Users/dna/Desktop/development/native/ios/libfork/sss/libosmscout-code/build/CMakeFiles/CMakeTmp/Debug/include -I/Users/dna/Desktop/development/native/ios/libfork/sss/libosmscout-code/build/CMakeFiles/CMakeTmp/CMAKE_TRY_COMPILE.build/Debug/cmTC_99d02.build/DerivedSources/x86_64 -I/Users/dna/Desktop/development/native/ios/libfork/sss/libosmscout-code/build/CMakeFiles/CMakeTmp/CMAKE_TRY_COMPILE.build/Debug/cmTC_99d02.build/DerivedSources -Wmost -Wno-four-char-constants -Wno-unknown-pragmas -F/Users/dna/Desktop/development/native/ios/libfork/sss/libosmscout-code/build/CMakeFiles/CMakeTmp/Debug -DHAVE_ALTIVEC -faltivec -MMD -MT dependencies -MF /Users/dna/Desktop/development/native/ios/libfork/sss/libosmscout-code/build/CMakeFiles/CMakeTmp/CMAKE_TRY_COMPILE.build/Debug/cmTC_99d02.build/Objects-normal/x86_64/src.d --serialize-diagnostics /Users/dna/Desktop/development/native/ios/libfork/sss/libosmscout-code/build/CMakeFiles/CMakeTmp/CMAKE_TRY_COMPILE.build/Debug/cmTC_99d02.build/Objects-normal/x86_64/src.dia -c /Users/dna/Desktop/development/native/ios/libfork/sss/libosmscout-code/build/CMakeFiles/CMakeTmp/src.c -o /Users/dna/Desktop/development/native/ios/libfork/sss/libosmscout-code/build/CMakeFiles/CMakeTmp/CMAKE_TRY_COMPILE.build/Debug/cmTC_99d02.build/Objects-normal/x86_64/src.o
clang: error: invalid argument '-faltivec' only allowed with 'ppc/ppc64/ppc64le'

** BUILD FAILED **

The following build commands failed:
	CompileC CMAKE_TRY_COMPILE.build/Debug/cmTC_99d02.build/Objects-normal/x86_64/src.o src.c normal x86_64 c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

Source file was:
int main(void) { return 0; }
Determining if the function posix_fadvise exists failed with the following output:
Change Dir: /Users/dna/Desktop/development/native/ios/libfork/sss/libosmscout-code/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/xcodebuild" "-project" "CMAKE_TRY_COMPILE.xcodeproj" "build" "-target" "cmTC_42ec5" "-configuration" "Debug"
=== BUILD TARGET cmTC_42ec5 OF PROJECT CMAKE_TRY_COMPILE WITH CONFIGURATION Debug ===

Check dependencies

Write auxiliary files
/bin/mkdir -p /Users/dna/Desktop/development/native/ios/libfork/sss/libosmscout-code/build/CMakeFiles/CMakeTmp/CMAKE_TRY_COMPILE.build/Debug/cmTC_42ec5.build/Objects-normal/x86_64
write-file /Users/dna/Desktop/development/native/ios/libfork/sss/libosmscout-code/build/CMakeFiles/CMakeTmp/CMAKE_TRY_COMPILE.build/Debug/cmTC_42ec5.build/Objects-normal/x86_64/cmTC_42ec5.LinkFileList

CompileC CMAKE_TRY_COMPILE.build/Debug/cmTC_42ec5.build/Objects-normal/x86_64/CheckFunctionExists.o /usr/local/Cellar/cmake/3.9.2/share/cmake/Modules/CheckFunctionExists.c normal x86_64 c com.apple.compilers.llvm.clang.1_0.compiler
    cd /Users/dna/Desktop/development/native/ios/libfork/sss/libosmscout-code/build/CMakeFiles/CMakeTmp
    export LANG=en_US.US-ASCII
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x c -arch x86_64 -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -Wno-trigraphs -fpascal-strings -O0 -Wno-missing-field-initializers -Wno-missing-prototypes -Wno-return-type -Wno-missing-braces -Wparentheses -Wswitch -Wno-unused-function -Wno-unused-label -Wno-unused-parameter -Wno-unused-variable -Wunused-value -Wno-empty-body -Wno-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wno-constant-conversion -Wno-int-conversion -Wno-bool-conversion -Wno-enum-conversion -Wno-shorten-64-to-32 -Wpointer-sign -Wno-newline-eof -DCMAKE_INTDIR=\"Debug\" -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -fasm-blocks -fstrict-aliasing -Wdeprecated-declarations -mmacosx-version-min=10.11 -g -Wno-sign-conversion -Wno-infinite-recursion -I/Users/dna/Desktop/development/native/ios/libfork/sss/libosmscout-code/build/CMakeFiles/CMakeTmp/Debug/include -I/Users/dna/Desktop/development/native/ios/libfork/sss/libosmscout-code/build/CMakeFiles/CMakeTmp/CMAKE_TRY_COMPILE.build/Debug/cmTC_42ec5.build/DerivedSources/x86_64 -I/Users/dna/Desktop/development/native/ios/libfork/sss/libosmscout-code/build/CMakeFiles/CMakeTmp/CMAKE_TRY_COMPILE.build/Debug/cmTC_42ec5.build/DerivedSources -Wmost -Wno-four-char-constants -Wno-unknown-pragmas -F/Users/dna/Desktop/development/native/ios/libfork/sss/libosmscout-code/build/CMakeFiles/CMakeTmp/Debug -DCHECK_FUNCTION_EXISTS=posix_fadvise -MMD -MT dependencies -MF /Users/dna/Desktop/development/native/ios/libfork/sss/libosmscout-code/build/CMakeFiles/CMakeTmp/CMAKE_TRY_COMPILE.build/Debug/cmTC_42ec5.build/Objects-normal/x86_64/CheckFunctionExists.d --serialize-diagnostics /Users/dna/Desktop/development/native/ios/libfork/sss/libosmscout-code/build/CMakeFiles/CMakeTmp/CMAKE_TRY_COMPILE.build/Debug/cmTC_42ec5.build/Objects-normal/x86_64/CheckFunctionExists.dia -c /usr/local/Cellar/cmake/3.9.2/share/cmake/Modules/CheckFunctionExists.c -o /Users/dna/Desktop/development/native/ios/libfork/sss/libosmscout-code/build/CMakeFiles/CMakeTmp/CMAKE_TRY_COMPILE.build/Debug/cmTC_42ec5.build/Objects-normal/x86_64/CheckFunctionExists.o

Ld Debug/cmTC_42ec5 normal x86_64
    cd /Users/dna/Desktop/development/native/ios/libfork/sss/libosmscout-code/build/CMakeFiles/CMakeTmp
    export MACOSX_DEPLOYMENT_TARGET=10.11
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -L/Users/dna/Desktop/development/native/ios/libfork/sss/libosmscout-code/build/CMakeFiles/CMakeTmp/Debug -F/Users/dna/Desktop/development/native/ios/libfork/sss/libosmscout-code/build/CMakeFiles/CMakeTmp/Debug -filelist /Users/dna/Desktop/development/native/ios/libfork/sss/libosmscout-code/build/CMakeFiles/CMakeTmp/CMAKE_TRY_COMPILE.build/Debug/cmTC_42ec5.build/Objects-normal/x86_64/cmTC_42ec5.LinkFileList -mmacosx-version-min=10.11 -Xlinker -object_path_lto -Xlinker /Users/dna/Desktop/development/native/ios/libfork/sss/libosmscout-code/build/CMakeFiles/CMakeTmp/CMAKE_TRY_COMPILE.build/Debug/cmTC_42ec5.build/Objects-normal/x86_64/cmTC_42ec5_lto.o -Xlinker -no_deduplicate -Wl,-search_paths_first -Wl,-headerpad_max_install_names -Xlinker -dependency_info -Xlinker /Users/dna/Desktop/development/native/ios/libfork/sss/libosmscout-code/build/CMakeFiles/CMakeTmp/CMAKE_TRY_COMPILE.build/Debug/cmTC_42ec5.build/Objects-normal/x86_64/cmTC_42ec5_dependency_info.dat -o /Users/dna/Desktop/development/native/ios/libfork/sss/libosmscout-code/build/CMakeFiles/CMakeTmp/Debug/cmTC_42ec5
Undefined symbols for architecture x86_64:
  "_posix_fadvise", referenced from:
      _main in CheckFunctionExists.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

** BUILD FAILED **

The following build commands failed:
	Ld Debug/cmTC_42ec5 normal x86_64
(1 failure)

Determining if the function mallinfo exists failed with the following output:
Change Dir: /Users/dna/Desktop/development/native/ios/libfork/sss/libosmscout-code/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/xcodebuild" "-project" "CMAKE_TRY_COMPILE.xcodeproj" "build" "-target" "cmTC_1e4b3" "-configuration" "Debug"
=== BUILD TARGET cmTC_1e4b3 OF PROJECT CMAKE_TRY_COMPILE WITH CONFIGURATION Debug ===

Check dependencies

Write auxiliary files
/bin/mkdir -p /Users/dna/Desktop/development/native/ios/libfork/sss/libosmscout-code/build/CMakeFiles/CMakeTmp/CMAKE_TRY_COMPILE.build/Debug/cmTC_1e4b3.build/Objects-normal/x86_64
write-file /Users/dna/Desktop/development/native/ios/libfork/sss/libosmscout-code/build/CMakeFiles/CMakeTmp/CMAKE_TRY_COMPILE.build/Debug/cmTC_1e4b3.build/Objects-normal/x86_64/cmTC_1e4b3.LinkFileList

CompileC CMAKE_TRY_COMPILE.build/Debug/cmTC_1e4b3.build/Objects-normal/x86_64/CheckFunctionExists.o /usr/local/Cellar/cmake/3.9.2/share/cmake/Modules/CheckFunctionExists.c normal x86_64 c com.apple.compilers.llvm.clang.1_0.compiler
    cd /Users/dna/Desktop/development/native/ios/libfork/sss/libosmscout-code/build/CMakeFiles/CMakeTmp
    export LANG=en_US.US-ASCII
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x c -arch x86_64 -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -Wno-trigraphs -fpascal-strings -O0 -Wno-missing-field-initializers -Wno-missing-prototypes -Wno-return-type -Wno-missing-braces -Wparentheses -Wswitch -Wno-unused-function -Wno-unused-label -Wno-unused-parameter -Wno-unused-variable -Wunused-value -Wno-empty-body -Wno-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wno-constant-conversion -Wno-int-conversion -Wno-bool-conversion -Wno-enum-conversion -Wno-shorten-64-to-32 -Wpointer-sign -Wno-newline-eof -DCMAKE_INTDIR=\"Debug\" -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -fasm-blocks -fstrict-aliasing -Wdeprecated-declarations -mmacosx-version-min=10.11 -g -Wno-sign-conversion -Wno-infinite-recursion -I/Users/dna/Desktop/development/native/ios/libfork/sss/libosmscout-code/build/CMakeFiles/CMakeTmp/Debug/include -I/Users/dna/Desktop/development/native/ios/libfork/sss/libosmscout-code/build/CMakeFiles/CMakeTmp/CMAKE_TRY_COMPILE.build/Debug/cmTC_1e4b3.build/DerivedSources/x86_64 -I/Users/dna/Desktop/development/native/ios/libfork/sss/libosmscout-code/build/CMakeFiles/CMakeTmp/CMAKE_TRY_COMPILE.build/Debug/cmTC_1e4b3.build/DerivedSources -Wmost -Wno-four-char-constants -Wno-unknown-pragmas -F/Users/dna/Desktop/development/native/ios/libfork/sss/libosmscout-code/build/CMakeFiles/CMakeTmp/Debug -DCHECK_FUNCTION_EXISTS=mallinfo -MMD -MT dependencies -MF /Users/dna/Desktop/development/native/ios/libfork/sss/libosmscout-code/build/CMakeFiles/CMakeTmp/CMAKE_TRY_COMPILE.build/Debug/cmTC_1e4b3.build/Objects-normal/x86_64/CheckFunctionExists.d --serialize-diagnostics /Users/dna/Desktop/development/native/ios/libfork/sss/libosmscout-code/build/CMakeFiles/CMakeTmp/CMAKE_TRY_COMPILE.build/Debug/cmTC_1e4b3.build/Objects-normal/x86_64/CheckFunctionExists.dia -c /usr/local/Cellar/cmake/3.9.2/share/cmake/Modules/CheckFunctionExists.c -o /Users/dna/Desktop/development/native/ios/libfork/sss/libosmscout-code/build/CMakeFiles/CMakeTmp/CMAKE_TRY_COMPILE.build/Debug/cmTC_1e4b3.build/Objects-normal/x86_64/CheckFunctionExists.o

Ld Debug/cmTC_1e4b3 normal x86_64
    cd /Users/dna/Desktop/development/native/ios/libfork/sss/libosmscout-code/build/CMakeFiles/CMakeTmp
    export MACOSX_DEPLOYMENT_TARGET=10.11
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -L/Users/dna/Desktop/development/native/ios/libfork/sss/libosmscout-code/build/CMakeFiles/CMakeTmp/Debug -F/Users/dna/Desktop/development/native/ios/libfork/sss/libosmscout-code/build/CMakeFiles/CMakeTmp/Debug -filelist /Users/dna/Desktop/development/native/ios/libfork/sss/libosmscout-code/build/CMakeFiles/CMakeTmp/CMAKE_TRY_COMPILE.build/Debug/cmTC_1e4b3.build/Objects-normal/x86_64/cmTC_1e4b3.LinkFileList -mmacosx-version-min=10.11 -Xlinker -object_path_lto -Xlinker /Users/dna/Desktop/development/native/ios/libfork/sss/libosmscout-code/build/CMakeFiles/CMakeTmp/CMAKE_TRY_COMPILE.build/Debug/cmTC_1e4b3.build/Objects-normal/x86_64/cmTC_1e4b3_lto.o -Xlinker -no_deduplicate -Wl,-search_paths_first -Wl,-headerpad_max_install_names -Xlinker -dependency_info -Xlinker /Users/dna/Desktop/development/native/ios/libfork/sss/libosmscout-code/build/CMakeFiles/CMakeTmp/CMAKE_TRY_COMPILE.build/Debug/cmTC_1e4b3.build/Objects-normal/x86_64/cmTC_1e4b3_dependency_info.dat -o /Users/dna/Desktop/development/native/ios/libfork/sss/libosmscout-code/build/CMakeFiles/CMakeTmp/Debug/cmTC_1e4b3
Undefined symbols for architecture x86_64:
  "_mallinfo", referenced from:
      _main in CheckFunctionExists.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

** BUILD FAILED **

The following build commands failed:
	Ld Debug/cmTC_1e4b3 normal x86_64
(1 failure)

Performing C SOURCE FILE Test ICONV_SECOND_ARGUMENT_IS_CONST failed with the following output:
Change Dir: /Users/dna/Desktop/development/native/ios/libfork/sss/libosmscout-code/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/xcodebuild" "-project" "CMAKE_TRY_COMPILE.xcodeproj" "build" "-target" "cmTC_2f7e5" "-configuration" "Debug"
=== BUILD TARGET cmTC_2f7e5 OF PROJECT CMAKE_TRY_COMPILE WITH CONFIGURATION Debug ===

Check dependencies

Write auxiliary files
/bin/mkdir -p /Users/dna/Desktop/development/native/ios/libfork/sss/libosmscout-code/build/CMakeFiles/CMakeTmp/CMAKE_TRY_COMPILE.build/Debug/cmTC_2f7e5.build/Objects-normal/x86_64
write-file /Users/dna/Desktop/development/native/ios/libfork/sss/libosmscout-code/build/CMakeFiles/CMakeTmp/CMAKE_TRY_COMPILE.build/Debug/cmTC_2f7e5.build/Objects-normal/x86_64/cmTC_2f7e5.LinkFileList

CompileC CMAKE_TRY_COMPILE.build/Debug/cmTC_2f7e5.build/Objects-normal/x86_64/src.o src.c normal x86_64 c com.apple.compilers.llvm.clang.1_0.compiler
    cd /Users/dna/Desktop/development/native/ios/libfork/sss/libosmscout-code/build/CMakeFiles/CMakeTmp
    export LANG=en_US.US-ASCII
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x c -arch x86_64 -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -Wno-trigraphs -fpascal-strings -O0 -Wno-missing-field-initializers -Wno-missing-prototypes -Wno-return-type -Wno-missing-braces -Wparentheses -Wswitch -Wno-unused-function -Wno-unused-label -Wno-unused-parameter -Wno-unused-variable -Wunused-value -Wno-empty-body -Wno-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wno-constant-conversion -Wno-int-conversion -Wno-bool-conversion -Wno-enum-conversion -Wno-shorten-64-to-32 -Wpointer-sign -Wno-newline-eof -DCMAKE_INTDIR=\"Debug\" -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -fasm-blocks -fstrict-aliasing -Wdeprecated-declarations -mmacosx-version-min=10.11 -g -Wno-sign-conversion -Wno-infinite-recursion -I/Users/dna/Desktop/development/native/ios/libfork/sss/libosmscout-code/build/CMakeFiles/CMakeTmp/Debug/include -I/Users/dna/Desktop/development/native/ios/libfork/sss/libosmscout-code/build/CMakeFiles/CMakeTmp/CMAKE_TRY_COMPILE.build/Debug/cmTC_2f7e5.build/DerivedSources/x86_64 -I/Users/dna/Desktop/development/native/ios/libfork/sss/libosmscout-code/build/CMakeFiles/CMakeTmp/CMAKE_TRY_COMPILE.build/Debug/cmTC_2f7e5.build/DerivedSources -Wmost -Wno-four-char-constants -Wno-unknown-pragmas -F/Users/dna/Desktop/development/native/ios/libfork/sss/libosmscout-code/build/CMakeFiles/CMakeTmp/Debug -Werror -DICONV_SECOND_ARGUMENT_IS_CONST -MMD -MT dependencies -MF /Users/dna/Desktop/development/native/ios/libfork/sss/libosmscout-code/build/CMakeFiles/CMakeTmp/CMAKE_TRY_COMPILE.build/Debug/cmTC_2f7e5.build/Objects-normal/x86_64/src.d --serialize-diagnostics /Users/dna/Desktop/development/native/ios/libfork/sss/libosmscout-code/build/CMakeFiles/CMakeTmp/CMAKE_TRY_COMPILE.build/Debug/cmTC_2f7e5.build/Objects-normal/x86_64/src.dia -c /Users/dna/Desktop/development/native/ios/libfork/sss/libosmscout-code/build/CMakeFiles/CMakeTmp/src.c -o /Users/dna/Desktop/development/native/ios/libfork/sss/libosmscout-code/build/CMakeFiles/CMakeTmp/CMAKE_TRY_COMPILE.build/Debug/cmTC_2f7e5.build/Objects-normal/x86_64/src.o
/Users/dna/Desktop/development/native/ios/libfork/sss/libosmscout-code/build/CMakeFiles/CMakeTmp/src.c:9:21: error: passing 'const char **' to parameter of type 'char **' discards qualifiers in nested pointer types [-Werror,-Wincompatible-pointer-types-discards-qualifiers]
        iconv(conv, &in, &ilen, &out, &olen);
                    ^~~
In file included from /Users/dna/Desktop/development/native/ios/libfork/sss/libosmscout-code/build/CMakeFiles/CMakeTmp/src.c:2:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include/iconv.h:70:30: note: passing argument to parameter here
        char ** __restrict /*inbuf*/,  size_t * __restrict /*inbytesleft*/,
                                    ^
1 error generated.

** BUILD FAILED **

The following build commands failed:
	CompileC CMAKE_TRY_COMPILE.build/Debug/cmTC_2f7e5.build/Objects-normal/x86_64/src.o src.c normal x86_64 c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

Source file was:

        #include <iconv.h>
        int main(){
        iconv_t conv = 0;
        const char* in = 0;
        size_t ilen = 0;
        char* out = 0;
        size_t olen = 0;
        iconv(conv, &in, &ilen, &out, &olen);
        return 0;
        }

**Comment by Framstag** [comment]
```
Performing C SOURCE FILE Test HAVE_ALTIVEC failed with the following output:
```

CMake (similar to autoconf and meson) does (temporary) create small C/C++ files to test for certain OS and/or compiler features.

Some of this compiles are expected to fail. If you for example check for Win32 library functionality under OS X, such test applications will fail (either on compile or possibly later on run). CMake normally also does not report compilation or errors on these tests during build (for obvious reasons).

At first glance it look like the above snipped only does contain failed compilations of these tests. So I do not see something principle bad in the snipped? What error do you get as part of the normal terminal output during build?

**Comment by Framstag** [comment]
@jojonarte Can you give me any feedback on this? If not, I would close the issue, since I do not see a principle bug in the logs?

**Comment by jojonarte** [comment]
I got it to work even with the build fail log. So I'm gonna close this, thank you bro.
