### ISSUE TITLE
Tutorial to compile .framework for iOS

### ISSUE THREAD

**Issue by larsmango** [Framstag/libosmscout#482]
I've seen that cmake support for the iOS apps has been added recently. Also an export option for .frameworks has been added which is pretty cool. I was wondering if there is any step-by-step tutorial explaining how to compile a .framework with cmake. I am continuously running in build errors when running cmake.

**Comment by Framstag** [comment]
Currently not. @vyskocil is - as far as I understand - still working on it. I can however can easily enhance the build documention if you give me a simple ASCII or markdown description.

**Comment by frogg** [comment]
Hey @larsmango take a look at #475! @vyskocil explains there how to compile it for iOS and macOS.
I was able to follow the steps, but there is still some difficulties with he headers (see our discussion).
After all I think this issue can be closed then, but we might want to track the header issues in a new one.

**Comment by larsmango** [comment]
@frogg oh cool thanks for the hint. Didnt look into the pull request so far. This seems promising. I've seen that there are still some problems with the header files (sorry, I was not able to figure it out myself). Is there any update on that? Could you find something out @frogg @vyskocil?

Thanks and have a nice day!

**Comment by vyskocil** [comment]
Please look to [issue 526](https://github.com/Framstag/libosmscout/issues/526)
