### ISSUE TITLE
Litle mistake ?

### ISSUE THREAD

**Issue by DerKleinePunk** [Framstag/libosmscout#491]
in PlaneMapRenderer.cpp at Line 170 172 finalImgProjection.GetDimensions(finalImgBoundingBox) called Two Times relay need ?

**Comment by Karry** [comment]
Hi. Do you have your branch updated? I cant see it...

**Comment by Karry** [comment]
...yes, it was there few days ago: https://github.com/Framstag/libosmscout/blob/77442a5db73b24882221a55647dc311f8477ddce/libosmscout-client-qt/src/osmscout/PlaneMapRenderer.cpp 
it was removed when map rotation was returned

**Comment by Framstag** [comment]
@DerKleinePunk: Please check again. If the problem is fixed, please close the issue.

**Comment by DerKleinePunk** [comment]
ok ist solved i have an git problem
