### ISSUE TITLE
Improve reverse geocoding result

### ISSUE THREAD

**Issue by aquiles2k** [Framstag/libosmscout#494]
When doing coordinate lookup outside of cities one usally gets very little information.

E.g. doing a lookup for a coordinate on a german motorway one gets
```
$ ./LocationDescription ./dach_map 52.686982 13.330054
* Coordinate: 52.68698 N 13.33005 E
```
It would be great to get at least the streetname and the region in the result.

**Comment by aquiles2k** [comment]
I extended the LocationService by a way description to get the nearest way. This is somehow limited by the fact that im only comparing the distance to the nodes of the way which might be far away even though im directly on the street, but its a start. 

I also left out bearing because it would require some more sophisticated calculations to get the actual position relatiev to the street.

The query above now results in the following and also displays the issue with wide spread thus far away nodes of a street (the given coordinate is actualy ON the street but the nearest node is 90m away):
```
$ ./LocationDescription ./../../r_dev/Demos/dach_171005 52.686982 13.330054
* Coordinate: 52.68698 N 13.33005 E

Nearest way:
  * Your are 90.2m away from way:
  - Nördlicher Berliner Ring,  Hohen Neuendorf Way 593524461

  + feature Name: Nördlicher Berliner Ring
  + feature Ref: A 10
  + feature Grade
  + feature Access

  > region: Hohen Neuendorf
    + feature Name: Hohen Neuendorf
    + feature AdminLevel: 8
  > parent region: Landkreis Oberhavel
    + feature Name: Landkreis Oberhavel
    + feature AdminLevel: 6
  > parent region: Brandenburg
    + feature Name: Brandenburg
    + feature AdminLevel: 4
  > parent region: Deutschland
    + feature Name: Deutschland
    + feature AdminLevel: 2

```

**Comment by Framstag** [comment]
(Btw., patch looks good, waiting for the builds to check it, aslo assigned issue to you, since you already have supplied a patch :-)).

 We recently had a similar problem in the router regarding start and end notes.

See 

```
RoutePosition SimpleRoutingService::GetClosestRoutableNode(const GeoCoord& coord,
                                                           const RoutingProfile& profile,
                                                           double& radius) const
```

The magic is in the use of 
```
double distance=DistanceToSegment(coord.GetLon(),coord.GetLat(),way->nodes[i].GetLon(),way->nodes[i].GetLat(),
                                  way->nodes[i+1].GetLon(),way->nodes[i+1].GetLat(), r, intersectLon, intersectLat);
```

**Comment by aquiles2k** [comment]
That looks pretty much like what is needed :) I'll add it to the PR later this evening!

**Comment by Framstag** [comment]
OK; so I'll wait for that addition and the result build.

**Comment by aquiles2k** [comment]
Yea that looks much better, thanks for the hint!
```
$ ./LocationDescription ./dach_map 52.686982 13.330054
* Coordinate: 52.68698 N 13.33005 E

Nearest way:
  * Your are 0.1m away from way:
  - Nördlicher Berliner Ring,  Hohen Neuendorf Way 593524229
```
