### ISSUE TITLE
CMake Build on Windows (QT Depens)

### ISSUE THREAD

**Issue by DerKleinePunk** [Framstag/libosmscout#499]
In Windows with Installed QT 5. QT is not found.
Setting set QTDIR=D:/Tools/Qt/5.9.2/msvc2015 is not enough  you muss add -DCMAKE_PREFIX_PATH=D:/Tools/Qt/5.9.2/msvc2015/lib/cmake add the cmake command line.

cmake -G "Visual Studio 14 2015" -DCMAKE_SYSTEM_VERSION=10.0.##### .. -DCMAKE_INSTALL_PREFIX=.\output -DOSMSCOUT_BUILD_IMPORT=OFF -DOSMSCOUT_BUILD_DOC_API=OFF -DOSMSCOUT_BUILD_TESTS=OFF -DQTDIR=D:/Tools/Qt/5.9.2/msvc2015 -DCMAKE_PREFIX_PATH=D:/Tools/Qt/5.9.2/msvc2015/lib/cmake

This is an Working Command line.
Please can you add an hint at Documentation ?
An Regestrie value to find the path i have not found this only work with QT4
[HKEY_CURRENT_USER\\Software\\trolltech\\Versions does not exits on my computer

**Comment by Framstag** [comment]
I'll take a look.

**Comment by Framstag** [comment]
Addition to documentation added. Closing the issue. Thanks for pointing at!
