### ISSUE TITLE
Allow colorization by range of numerical feature value

### ISSUE THREAD

**Issue by Framstag** [Framstag/libosmscout#527]
From the Hackerweekend: Make it possible to colorize buildings depending on their creation year. I could image that you either give a value range (1600-2100) and a color range and the actual color is mapped by interpolation of the actual value in relation of the source range onto the color range - or you allow to pose a range limit on a value and the color will only drawn if the value is within the range.

The first solution will generate continuous coloring in the color range while the second solution will allow to assign totally different colors based on a value range.

**Comment by Framstag** [comment]
Hmmm, we could also solve this on the import level by defining different types for buildings in different build year ranges (18. century, 19. century....).

**Comment by Framstag** [comment]
For creation year of builds the tags `year_of_construction` and `start_date` seem to be the relevant ones.

**Comment by Karry** [comment]
Hi Tim. I had an idea to create city transportation map few weeks ago. Such map should prioritize subway, tram and other types related with public transport. And it would be great to display subway lines with its "natural color" that is usually used on [city maps](https://wiki.openstreetmap.org/wiki/File:Prague_metro_plan_2008.svg). IIn general, change object color by its feature...

I tried it, import `colour` feature to osmscout objects is simple, but I ended at the moment when I needed to extend stylesheet definition... cococpp compiled from source segfaults with libosmscout style definition. I don't investigate it deeper.

**Comment by Framstag** [comment]
In my case somebody is mapping construction year to many buildings and is looking for a tool to visualize this. Your case is another interesting view on the problem.

Perhaps it might be easier to allow to inject callbacks for such things into the renderer? It will get the FeatureValueBuffer and the FillStyle for the (area) object and will return a possibly modified color. This way we can implement much more of the mapping, converting logic into code. This is easier (for developers) and much more flexible. 

Hmmm, I'm currently working on the LocationSearch index (mainly cleanup first)....but for marketing reasons I should possibly switchto this thing :-)!? Would be a nice blog post...

**Comment by Framstag** [comment]
Pushed initial code for FillStyle post processing. Added small demo in DrawMapQt. Closing the issue. While we do not have processors for everything yet, it should be obvious how to continue for further styles on demand.
