### ISSUE TITLE
VS 2015 Build Break (Windows)

### ISSUE THREAD

**Issue by DerKleinePunk** [Framstag/libosmscout#530]
F:\Mine\OpenSource\libosmscout-own\libosmscout-gpx\include\osmscout/gpx/Optional.h(68): error C2491: 'osmscout::gpx::Optional<T>::of': definition of dllimport function not allowed [F:\Mine\OpenSource\libosmscout-own\build\Demos\GpxPipe.vcxproj]
  F:\Mine\OpenSource\libosmscout-own\libosmscout-gpx\include\osmscout/gpx/Optional.h(74): error C2491: 'osmscout::gpx::Optional<T>::of': definition of dllimport function not allowed [F:\Mine\OpenSource\libosmscout-own\build\Demos\GpxPipe.vcxproj]
  F:\Mine\OpenSource\libosmscout-own\libosmscout-gpx\include\osmscout/gpx/Optional.h(79): error C2491: 'osmscout::gpx::Optional<T>::hasValue': definition of dllimport function not allowed [F:\Mine\OpenSource\libosmscout-own\build\Demos\GpxPipe.vcxproj]
  F:\Mine\OpenSource\libosmscout-own\libosmscout-gpx\include\osmscout/gpx/Optional.h(85): error C2491: 'osmscout::gpx::Optional<T>::get': definition of dllimport function not allowed [F:\Mine\OpenSource\libosmscout-own\build\Demos\GpxPipe.vcxproj]
  F:\Mine\OpenSource\libosmscout-own\libosmscout-gpx\include\osmscout/gpx/Optional.h(91): error C2491: 'osmscout::gpx::Optional<T>::getOrElse': definition of dllimport function not allowed [F:\Mine\OpenSource\libosmscout-own\build\Demos\GpxPipe.vcxproj]
  F:\Mine\OpenSource\libosmscout-own\libosmscout-gpx\include\osmscout/gpx/Optional.h(97): error C2491: 'osmscout::gpx::Optional<T>::getOrElse': definition of dllimport function not allowed [F:\Mine\OpenSource\libosmscout-own\build\Demos\GpxPipe.vcxproj]

Please add 

if (ICONV_FOUND)
    target_include_directories(${THE_TARGET_NAME} PRIVATE ${ICONV_INCLUDE_DIRS})
    target_link_libraries(${THE_TARGET_NAME} ${ICONV_LIBRARIES})
endif()

in Cmakelist for gpx (LIBXML2 is using it)
and also for the Demo Projekt
see changes in my fork

**Comment by Framstag** [comment]
The error above could be the result of Optional using DLL export macros (OSMSCOUT_GPX_API). Normally templates should not be exported (but template instantiations should). Because of that I push a fix for this.

Regarding ICONV: I do not see that libxml2 is using iconv under Linux, looks like this is a Windows specific build option?

**Comment by Framstag** [comment]
Pushed fixes, please check.

**Comment by DerKleinePunk** [comment]
https://stackoverflow.com/questions/12579368/error-cannot-include-iconv-h-while-building-c-application-to-parse-xml-using-l

https://github.com/GNOME/libxml2/blob/d8083bf77955b7879c1290f0c0a24ab8cc70f7fb/libxml-2.0.pc.in
https://github.com/GNOME/libxml2/blob/d8083bf77955b7879c1290f0c0a24ab8cc70f7fb/INSTALL.libxml2

I don't think iCONV is windows spezific. On Linux the path to the header is always set so you don't sie it.

I have merged the new master to my branch demos now Building with vs2015

**Comment by Framstag** [comment]
@DerKleinePunk: Does it work for you now, so that we can close the issue?
