### ISSUE TITLE
Debian 9 gcc 6 Build Break

### ISSUE THREAD

**Issue by DerKleinePunk** [Framstag/libosmscout#539]
/home/punky/develop/libosmscout-code/libosmscout-client-qt/src/osmscout/InputHandler.cpp: In member function ‘virtual bool MoveHandler::rotateTo(double)’:
/home/punky/develop/libosmscout-code/libosmscout-client-qt/src/osmscout/InputHandler.cpp:405:35: error: call of overloaded ‘abs(double)’ is ambiguous
     if (abs(targetAngle-view.angle)>M_PI){

**Comment by DerKleinePunk** [comment]
/home/punky/develop/libosmscout-code/libosmscout-client-qt/src/osmscout/TiledRenderingHelper.cpp:49:43: error: call of overloaded ‘abs(double)’ is ambiguous
     width=fabs(rw*cosAlpha)+abs(rh*cosBeta);

**Comment by Framstag** [comment]
I'll see if I have some time to fix this. @Karry, if you are faster then me and since it is your code you csn of course fix it, too.

**Comment by Karry** [comment]
Regarding [cppreference.com](http://en.cppreference.com/w/cpp/numeric/math/fabs), there is common issue with resolving overloaded `abs` method. I don't read the details, but it should be fixed in c++17 standard, or full name `std::abs` should be used...

I will send fix in few minutes.
