### ISSUE TITLE
Using -DMARISA_INCLUDE_DIRS=... with CMake don't work anymore 

### ISSUE THREAD

**Issue by vyskocil** [Framstag/libosmscout#545]
The new way of searching marisa installation using pkg-config don't work when cross compiling for iOS. 
Why don't allow using the MARISA_INCLUDE_DIRS variable along the new way ?

**Comment by Framstag** [comment]
@vyskocil: Any feedback on this? Can I close the issue?

**Comment by Framstag** [comment]
Closing the issue, since I believe it should work. Please reopen, if not.
