### ISSUE TITLE
Misleading turn command

### ISSUE THREAD

**Issue by Karry** [Framstag/libosmscout#548]
Hi.

On screenshot below, road junction is entered from the east by the street "Kaplická" and continue (almost) straight on by street "Míru". But route node description contains "turn right". It is little bit confusing, because right direction would be into "5. května"

![obrazek](https://user-images.githubusercontent.com/309458/34976597-939a8ada-fa97-11e7-9e64-47e1375cfa52.png)

You may reproduce this issue with track simulator and [this gpx track](http://osmscout.karry.cz/tests/test-track.gpx):
`OSMScout2 --simulate-track "test-track.gpx" ~/Maps/ stylesheets/standard.oss`

**Comment by Framstag** [comment]
The directions are based on the values returned from the routing postprocessor? In this case the direction is calculated by analysing the angle between the incoming and the outgoing way. Their direction is interpolated by looking at a few notes up until the is a relevasnt distance. This can result in multiple way beeing "turn right" "even more turn right" and "more than the others turn right" ;-)

This might be tricky to solve in corners cases as above. Would have to take a in deep look to see what the actual angles are.

**Comment by Karry** [comment]
I understand that it is tricky :-) Sometimes two people in one car has different opinion what street is on "right turn". I just add this issue for later investigation - when navigation with voice commands will be done...

When I am looking to "panorama" image on [mapy.cz](https://mapy.cz/zakladni?x=14.3123235&y=48.6164043&z=18&pano=1&pid=41543639&yaw=4.740&fov=1.257&pitch=0.083), I am not sure what command is correct in this situation, but "slightly right" would be better tor that... ;-)

![obrazek](https://user-images.githubusercontent.com/309458/35005546-01fd8f5c-faf4-11e7-9d05-2750f62629cc.png)

**Comment by Framstag** [comment]
The is in Route.cpp:

```
  RouteDescription::DirectionDescription::Move RouteDescription::DirectionDescription::ConvertAngleToMove(double angle) const
  {
    if (fabs(angle)<=10.0) {
      return straightOn;
    }
    else if (fabs(angle)<=45.0) {
      return angle<0 ? slightlyLeft : slightlyRight;
    }
    else if (fabs(angle)<=120.0) {
      return angle<0 ? left : right;
    }
    else {
      return angle<0 ? sharpLeft : sharpRight;
    }
```

It should be no problem to change the code by either adding more differentiations or use another categorisation that better fits user expectation than the initial more "mathematical" approach. If this still leaves corner cases one would possible have to take a look at all directions at a crossing to create a more situation based description (if we have turn left 2 times, slightly XXX might have a bigger or smaller range to differentiate from XXX itself).

**Comment by Framstag** [comment]
@Karry: How do we continue with this issue?

**Comment by Karry** [comment]
We may close it now. It is just about tunning thresholds, what is "turn right" and "slightly right". I will postpone such tunnings, until I will collect feedback from real usage...
