### ISSUE TITLE
Backslash missing

### ISSUE THREAD

**Issue by asanoaozora** [Framstag/libosmscout#556]
https://github.com/Framstag/libosmscout/blob/0b7c3ae833e661b4db2d2798ffce43c7362ec192/libosmscout-client-qt/src/Makefile.am#L114

It gives an error because the generated Makefile is wrong (it adds unwanted files after the moc).
When I fixed it, cmake based build passed, except an issue with java:
CMakeFiles/Makefile2:2886: recipe for target 'libosmscout-binding/CMakeFiles/osmscout_binding_java.dir/all' failed
 but maybe something is missing on my side :-)

**Comment by Karry** [comment]
From your comments, it seems that you are generating Makefiles with CMake, but then you was running `Makefile` for autoconf... With Java binding, it is complicated. it is broken right now :-/

I would suggest you build everything except java by these commands:
```
mkdir build
cd build
cmake -DCMAKE_BUILD_TYPE=DEBUG -DOSMSCOUT_BUILD_BINDING_JAVA=OFF ..
make
```

**Comment by Framstag** [comment]
Also, if you can tell us the OS/distribution you are using we might have a central or a docker based build we can show you that builds (or can check against, if it does not).

**Comment by asanoaozora** [comment]
oops, you're right. I get confused between automake and cmake..
I'm using Ubuntu 17.10 with gcc 7.2.0. My goal is to render an OSM map into a Qt widget, to display the vehicle positions (and some other stuff)  I get from driving tests, and also to send it as simulated inputs to navigation software (as you can see in my tagged repositories). 
Qt version is 5.6.0

**Comment by Karry** [comment]
Great! I am closing this issue. If you will have another troubles with the library, feel free ask us.
