### ISSUE TITLE
Linker Error under MSYS2 Win10

### ISSUE THREAD

**Issue by DerKleinePunk** [Framstag/libosmscout#569]
` [ 13%] Linking CXX executable ../../../bin/Windows/sdl2gui.bin.exe
CMakeFiles/sdl2gui.bin.dir/objects.a(osmsoutlogger.cpp.obj): In function `ZN8osmscout6Logger11DestinationC2Ev':
F:/Mine/OpenSource/libosmscout-code/build/MinGW/Debug/include/osmscout/util/Logger.h:65: undefined reference to `_imp___ZTVN8osmscout6Logger11DestinationE'
CMakeFiles/sdl2gui.bin.dir/objects.a(osmsoutlogger.cpp.obj): In function `ZN8osmscout6Logger11DestinationD2Ev':
F:/Mine/OpenSource/libosmscout-code/build/MinGW/Debug/include/osmscout/util/Logger.h:68: undefined reference to `_imp___ZTVN8osmscout6Logger11DestinationE'
collect2.exe: error: ld returned 1 exit status
make[2]: *** [src/SDL2PaintFunctionTest/CMakeFiles/sdl2gui.bin.dir/build.make:1201: ../bin/Windows/sdl2gui.bin.exe] Error 1
make[1]: *** [CMakeFiles/Makefile2:182: src/SDL2PaintFunctionTest/CMakeFiles/sdl2gui.bin.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
====2 errors, 20 warnings, total time: 00:00:21 seconds====`

when i remove OSMSCOUT_API from the Destination Class in Logger.h it works.
After the Lib was Build.

**Comment by Framstag** [comment]
Which compiler are you using?

Looks like the virtual table for the Logger::Destination class is missing. I remember, that the

      virtual ~Destination() = default;

might be the problem. This is a C++11 feature, but it look like Visual Studios has problem with it. Can you change it to 

      virtual ~Destination() {};

locally, rebuild the libosmscout library and check if the build of your application works?

**Comment by Karry** [comment]
@DerKleinePunk did you try to remove `default` keyword from destructor and define it with empty body?

**Comment by DerKleinePunk** [comment]
git pull
change destructor to virtual ~Destination(){}; 
rebuild lib and source 
same message
 Destination(){};
      virtual ~Destination(){};
rebuild all
same message

sorry i don't under stand this

**Comment by Framstag** [comment]
I'll try to reproduce the problem locally, give me some time.

**Comment by Framstag** [comment]
I was not able to reproduce the problem, since I was not able to build your project. Its is trying to download and build ffmpeg, but this fails:

```
[ 12%] Performing configure step for 'ffmpeg'
gcc is unable to create an executable file.
If gcc is a cross-compiler, use the --enable-cross-compile option.
Only do this if you know what cross compiling means.
C compiler test failed.

If you think configure made a mistake, make sure you are using the latest
version from Git.  If the latest version fails, report the problem to the
ffmpeg-user@ffmpeg.org mailing list or IRC #ffmpeg on irc.freenode.net.
Include the log file "config.log" produced by configure as this will help
solve the problem.
make[5]: *** [CMakeFiles/ffmpeg.dir/build.make:106: ffmpeg-prefix/src/ffmpeg-stamp/ffmpeg-configure] Fehler 1
```

I then locally modified the EncodeNumber.cpp (in the Tests directory) test. I added an import (the first import after iostream, so there should be no interference with other libosmscout headers which define special macros etc...):

```
#include <osmscout/util/Logger.h>
```

and made use of the logging infrastructure by adding 

```
  osmscout::log.Info() << "Hello!";
```

right after the int main....

I then rebuild the tests (make EncodeNumber). It build without error and I was able to start it, too (with the expected output). I even checked the compiler options use by CMake but did not find anything surpising. I'm doing a 64bit build (under 64 bit Windows 10). All MinGW packages are up to date.

I'm list, too.

If the importing and exporting of symbols would be broken, you should get an error for all symbols in libosmscout (the whole stuff is triggered under Windows by the compiler defining _WIN32, which is also defined under 64 bit system). the deafult destructor is also something special, but I cannot reproduce the problem with it and removing it make the class not special in any way.

Any ideas anybody?

**Comment by DerKleinePunk** [comment]
Thanks for the Build Error for FFmpeg when FFmpeg libs are found it not Build his own Version. You must install the Libs with pacman. I don't Testing with 64 Bit because Raspberry is 32 bit add Now.

**Comment by DerKleinePunk** [comment]
https://bitbucket.org/numberfive/sdl2-osmscout-msys2 is my Test App the error is there too. But the only SDL2 is need to build.

**Comment by Framstag** [comment]
OK, I have now a reproducer:

```
cd /C/projects/sdl2-osmscout-msys2/build/src/SDL2-OSMScout-MapPainter && /C/msys64/mingw64/bin/g++.exe  -std=c++11 -fexceptions -DELPP_THREAD_SAFE -DELPP_STACKTRACE_ON_CRASH   -static-libstdc++ -static-libgcc -Wl,--whole-archive CMakeFiles/SDL2-OSMScout-MapPainter.dir/objects.a -Wl,--no-whole-archive  -o ../../../bin/SDL2-OSMScout-MapPainter.exe -Wl,--major-image-version,0,--minor-image-version,0 -lmingw32 -mwindows -Wl,-Bstatic -lSDL2main -Wl,-Bdynamic -lSDL2 -lSDL2_net /C/projects/libosmscout/build/libosmscout/libosmscout.dll.a /C/projects/libosmscout/build/libosmscout-map/libosmscout_map.dll.a /C/projects/libosmscout/build/libosmscout-map-cairo/libosmscout_map_cairo.dll.a -lcairo -lkernel32 -luser32 -lgdi32 -lwinspool -lshell32 -lole32 -loleaut32 -luuid -lcomdlg32 -ladvapi32
CMakeFiles/SDL2-OSMScout-MapPainter.dir/objects.a(osmsoutlogger.cpp.obj):osmsoutlogger.cpp:(.text$_ZN8osmscout6Logger11DestinationC2Ev[_ZN8osmscout6Logger11DestinationC2Ev]+0xb): undefined reference to `__imp__ZTVN8osmscout6Logger11DestinationE'
CMakeFiles/SDL2-OSMScout-MapPainter.dir/objects.a(osmsoutlogger.cpp.obj):osmsoutlogger.cpp:(.text$_ZN8osmscout6Logger11DestinationD2Ev[_ZN8osmscout6Logger11DestinationD2Ev]+0xb): undefined reference to `__imp__ZTVN8osmscout6Logger11DestinationE'
collect2.exe: error: ld returned 1 exit status
```

**Comment by Framstag** [comment]
Pushed small change. Please check again.

**Comment by DerKleinePunk** [comment]
you di't it. Thanks
