### ISSUE TITLE
Address Reverse-lookup regression

### ISSUE THREAD

**Issue by laarmen** [Framstag/libosmscout#573]
Hi,

When trying to look up the following coordinates:
https://nominatim.openstreetmap.org/search.php?q=48.85237%2C2.37181

The result used to be accurate (34 Rue du Faubourg Saint-Antoine, https://nominatim.openstreetmap.org/details.php?place_id=16077658 ), but now isn't, pointing at the number 47, about 60m afar ( https://nominatim.openstreetmap.org/details.php?place_id=216799976 ). I'm using the latest Ile-de-France pbf from GeoFabrik.

I tracked the regression down to this commit : https://github.com/Framstag/libosmscout/commit/e0ef46f2305eba9c97320a1dbe44be95c19e1222

Comparing the data, it seems the 34 is missing the postcode tag, as do most of the other buildings in the street, which might help tracking down the issue. I've spent the better part of a loong day trying to understand what the changes pinpointed did, but miserably failed, as I'm not even sure if the problem lies in the import part or the LocationService (now LocationDescriptionService). @Framstag might have more luck with it, as the author of the commit?

Cheers,
Simon

**Comment by Karry** [comment]
Hi. It seems to be a import problem. I am looking to [my latest France import](http://osmscout.karry.cz/europe/france-16-20180218-1244/)

OSM address node [1370205310](https://www.openstreetmap.org/node/1370205310) is there:
```
Node {
  OSM id: 1370205310
  fileOffset: 35120766
  type: address

  Address: 34

  lat: 48.85234
  lon: 2.37185
}
```
but I don't see it in `location_full.txt` dump nor any error report...

**Comment by Framstag** [comment]
The change is already rather old and it was rather big. It introduced support for postal areas. Since the data does not seam to be "special" in this regard, it looks like some side effect.

The missing postal code should not be a principle problem. An unknown postal code should result in an index entry for "" as a postal code (the index has a list of postal areas below a administrative boundary, the empty postal code is an allowed but special one).

I'll try to take a look at it as soon as I have some time...

**Comment by laarmen** [comment]
I was trying to reproduce the bug on a smaller area, and I did it for Mayotte at the following position : -12.78908:45.27466. 
At the blamed commit, I get an address at https://nominatim.openstreetmap.org/details.php?place_id=151294079

whereas the correct answer, gotten previously, is at https://nominatim.openstreetmap.org/details.php?place_id=179681573

Also, I might have screwed up a copy-paste at some point, because the actual "blamed" commit is 5d710b4f3e02a34062083ecbff66f0d4bfa089e9, sorry about that

**Comment by Framstag** [comment]
Looks like there is a bug in the location cleanup code of LocationIndexGenerator::CleanupPostalAreas() (the address cleanup code is OK). I'll see how I can fix it, until then you can comment out the location block (should only make the index bigger).

**Comment by Framstag** [comment]
The problem should now be fixed. Please test again and close the issue in case.

**Comment by laarmen** [comment]
Well, the two test cases posted above seem to work now. Thanks a lot!
