### ISSUE TITLE
Build Error Debug 

### ISSUE THREAD

**Issue by DerKleinePunk** [Framstag/libosmscout#585]
[ 94%] Linking CXX executable LocationLookupTest.exe
CMakeFiles/LocationLookupTest.dir/objects.a(LocationServiceTest.cpp.obj): In function `ZN8osmscout19PreprocessorFactoryD2Ev':
F:/Mine/OpenSource/libosmscout-code/libosmscout-import/include/osmscout/import/Import.h:49: undefined reference to `_imp___ZTVN8osmscout19PreprocessorFactoryE'
CMakeFiles/LocationLookupTest.dir/objects.a(LocationServiceTest.cpp.obj): In function `ZN8osmscout19PreprocessorFactoryC2Ev':
F:/Mine/OpenSource/libosmscout-code/libosmscout-import/include/osmscout/import/Import.h:45: undefined reference to `_imp___ZTVN8osmscout19PreprocessorFactoryE'
collect2.exe: error: ld returned 1 exit status
make[2]: *** [Tests/CMakeFiles/LocationLookupTest.dir/build.make:183: Tests/LocationLookupTest.exe] Fehler 1
make[1]: *** [CMakeFiles/Makefile2:2823: Tests/CMakeFiles/LocationLookupTest.dir/all] Fehler 2
make: *** [Makefile:141: all] Fehler 2

cmake .. -G"MSYS Makefiles" -DCMAKE_INSTALL_PREFIX=/F/Mine/OpenSource/libosmscout-code/build/MinGW/Debug -DOSMSCOUT_ENABLE_SSE=ON -DCMAKE_BUILD_TYPE=Debug

**Comment by Framstag** [comment]
@DerKleinePunk: Please test again

**Comment by DerKleinePunk** [comment]
thanks fixed
