### ISSUE TITLE
Build Error Last Commit on gcc version 6.3.0 20170516 (Debian 6.3.0-18+deb9u1)

### ISSUE THREAD

**Issue by DerKleinePunk** [Framstag/libosmscout#587]
/home/punky/develop/libosmscout-code/libosmscout-import/src/osmscout/import/RawWay.cpp: In member function ‘void osmscout::RawWay::Write(const osmscout::TypeConfig&, osmscout::FileWriter&) const’:
/home/punky/develop/libosmscout-code/libosmscout-import/src/osmscout/import/RawWay.cpp:165:28: error: no matching function for call to ‘min(osmscout::OSMId&, long int&)’
                        node);
                            ^
In file included from /usr/include/c++/6/memory:62:0,
                 from /home/punky/develop/libosmscout-code/libosmscout-import/include/osmscout/import/RawWay.h:23,
                 from /home/punky/develop/libosmscout-code/libosmscout-import/src/osmscout/import/RawWay.cpp:20:
/usr/include/c++/6/bits/stl_algobase.h:195:5: note: candidate: template<class _Tp> const _Tp& std::min(const _Tp&, const _Tp&)
     min(const _Tp& __a, const _Tp& __b)
     ^~~
/usr/include/c++/6/bits/stl_algobase.h:195:5: note:   template argument deduction/substitution failed:
/home/punky/develop/libosmscout-code/libosmscout-import/src/osmscout/import/RawWay.cpp:165:28: note:   deduced conflicting types for parameter ‘const _Tp’ (‘long long int’ and ‘long int’)
                        node);
                            ^
In file included from /usr/include/c++/6/memory:62:0,
                 from /home/punky/develop/libosmscout-code/libosmscout-import/include/osmscout/import/RawWay.h:23,
                 from /home/punky/develop/libosmscout-code/libosmscout-import/src/osmscout/import/RawWay.cpp:20:
/usr/include/c++/6/bits/stl_algobase.h:243:5: note: candidate: template<class _Tp, class _Compare> const _Tp& std::min(const _Tp&, const _Tp&, _Compare)
     min(const _Tp& __a, const _Tp& __b, _Compare __comp)
     ^~~
/usr/include/c++/6/bits/stl_algobase.h:243:5: note:   template argument deduction/substitution failed:
/home/punky/develop/libosmscout-code/libosmscout-import/src/osmscout/import/RawWay.cpp:165:28: note:   deduced conflicting types for parameter ‘const _Tp’ (‘long long int’ and ‘long int’)
                        node);
                            ^
In file included from /usr/include/c++/6/algorithm:62:0,
                 from /home/punky/develop/libosmscout-code/libosmscout-import/src/osmscout/import/RawWay.cpp:22:
/usr/include/c++/6/bits/stl_algo.h:3447:5: note: candidate: template<class _Tp> _Tp std::min(std::initializer_list<_Tp>)
     min(initializer_list<_Tp> __l)
     ^~~
/usr/include/c++/6/bits/stl_algo.h:3447:5: note:   template argument deduction/substitution failed:
/home/punky/develop/libosmscout-code/libosmscout-import/src/osmscout/import/RawWay.cpp:165:28: note:   mismatched types ‘std::initializer_list<_Tp>’ and ‘long long int’
                        node);

**Comment by DerKleinePunk** [comment]
for (const auto node : nodes) {
        minId=std::min(minId,
                       node);
      }

?

**Comment by Framstag** [comment]
Fix should already be applied, builds are running.

**Comment by Framstag** [comment]
Central builds are all green again and showed the problem before, too. Closing the issue.
