### ISSUE TITLE
CMake Build Failed after cleanup

### ISSUE THREAD

**Issue by DerKleinePunk** [Framstag/libosmscout#589]
[ 86%] Building CXX object Tests/CMakeFiles/TilingTest.dir/src/TilingTest.cpp.o
/home/punky/develop/libosmscout-code/Tests/src/TilingTest.cpp:5:21: fatal error: catch.hpp: Datei oder Verzeichnis nicht gefunden
 #include <catch.hpp>
                     ^
/home/punky/develop/libosmscout-code/Tests/src/ScanConversion.cpp:4:21: fatal error: catch.hpp: Datei oder Verzeichnis nicht gefunden
 #include <catch.hpp>

 /home/punky/develop/libosmscout-code/Tests/src/ColorParse.cpp:6:21: fatal error: catch.hpp: Datei oder Verzeichnis nicht gefunden
 #include <catch.hpp>

 [ 89%] Building CXX object Tests/CMakeFiles/LocationLookupTest.dir/src/SearchForPOIByFormTest.cpp.o
/home/punky/develop/libosmscout-code/Tests/src/SearchForPOIByFormTest.cpp:1:21: fatal error: catch.hpp: Datei oder Verzeichnis nicht gefunden
 #include "catch.hpp"

 [ 90%] Building CXX object Tests/CMakeFiles/BitsAndBytesNeeded.dir/src/BitsAndBytesNeeded.cpp.o
/home/punky/develop/libosmscout-code/Tests/src/BitsAndBytesNeeded.cpp:8:21: fatal error: catch.hpp: Datei oder Verzeichnis nicht gefunden
 #include <catch.hpp>

 [ 91%] Building CXX object Tests/CMakeFiles/AccessParse.dir/src/AccessParse.cpp.o
/home/punky/develop/libosmscout-code/Tests/src/AccessParse.cpp:10:21: fatal error: catch.hpp: Datei oder Verzeichnis nicht gefunden
 #include <catch.hpp>

And many more

**Comment by Framstag** [comment]
Yes, after a lot of changes to the cmake build, it failed. Cause should be easy to fix, I'll tale a look during the day.

**Comment by Framstag** [comment]
@DerKleinePunk: That issues should now be solved. I'm still waiting for the directx-backend to build correctly. But if this is not active in your build, please already check and close the issue.

**Comment by DerKleinePunk** [comment]
@Framstag i have send you en Build log via mail. I think directx is build but i not tested it.

**Comment by Framstag** [comment]
Mail did not have an attachment, but the central builds do show that directx backend was build. Thus closing the issue.
