### ISSUE TITLE
OSMScout2 can't display offline map

### ISSUE THREAD

**Issue by jialinxie** [Framstag/libosmscout#593]
hi, i had build libosmscout successful on OSX 10.13.3, 
when i run `./OSMScout2 ../maps/hawaii-latest/ ../stylesheets/`, 
i got this pop-up window,[“OSMScout2” would like to use your current location.]
whatever i click yes/no, the OSMScout demo doesn't display anything

*following is the output information*
jacklindeMBP:OSMScout2 jack$ **./OSMScout2 ../maps/hawaii-latest/ ../stylesheets/**

Setting libosmscout logging to level: WARNING
Can't load translator for locale QLocale(Chinese, Simplified Han, China) / "zh_CN" ( "/Library/Application Support/libosmscout/OSMScout2/translations" )
Loading online tile providers from  ":/resources/online-tile-providers.json"
Loading map providers from  ":/resources/map-providers.json"
MapManager ctor
Initialize databases
qml: Gain focus, update popup
qml: Gain focus, update popup
TextFontSize: 17 px
Average char width: 11 px
qml: Position changed:
qml: Positioning is true
qml: Last error 3
focus-out event
qml: Position changed:
qml:   latitude: 22.628288023834358
qml:   longitude: 114.05688667777397
qml:   altitude: 98.3031997680664
qml:   horizontal accuracy: 65
qml:   vertical accuracy: 10
qml: Position changed:
qml:   latitude: 22.62826443044386
qml:   longitude: 114.05685953445062
qml:   altitude: 97.53117370605469
qml:   horizontal accuracy: 65
qml:   vertical accuracy: 10
qml: Position changed:
qml:   latitude: 22.628339965295808
qml:   longitude: 114.05689175885954
qml:   altitude: 97.43311309814453
qml:   horizontal accuracy: 65
qml:   vertical accuracy: 10
tap  QPoint(320,306)
qml: tap: 320x306 @ 75.71982226669682 22.670973315728375 (map center 73.48852372912498 8.02893998788187)
qml: Position changed:
qml:   latitude: 22.628377887960305
qml:   longitude: 114.05690793918733
qml:   altitude: 97.39010620117188
qml:   horizontal accuracy: 65
qml:   vertical accuracy: 10
focus-out event

how can i load translator for locale QLocale?
I would be grateful for your prompt reply!

**Comment by Karry** [comment]
Hi. OSMScout2 can display offline maps only. It is possible that map database was not found or displayed area is not covered by database (bit it is unlikely, OSMScout2 center covered area on startup) Can you setup OSMSCOUT_LOG variable to debug before start please? `export OSMSCOUT_LOG=debug` What is content of your directory `../maps/hawaii-latest/` ?

Translator warning is not relevant here. We dont have translation to Chinese yet, default english will be used...

**Comment by jialinxie** [comment]
Hi, Karry, thanks for your reply.

following is maps data produced by`./Import hawaii-latest.osm.pbf ./hawaii-latest`
jacklindeMBP:OSMScout2 jack$ **`ls ../maps/hawaii-latest`**
areaaddress.dat		distribution.dat	rawcoastline.dat	tag.html
areaarea.idx		index.html			rawcoords.dat		turnrestr.dat
areanode.idx		intersections.dat	rawdatapolygon.dat	types.dat
areas.dat			intersections.idx	rawnodes.dat		water.idx
areas.idmap			location.html		rawrel.idx		way.html
areas.tmp			location.idx		rawrels.dat		wayaddress.dat
areas2.tmp			location_full.txt	rawturnrestr.dat	wayarea.tmp
areas3.tmp			location_metrics.txtrawway.idx		wayareablack.dat
areasopt.dat		location_region.txt	rawways.dat		ways.dat
areaway.idx			nodeaddress.dat		relarea.tmp		ways.idmap
bounding.dat		nodes.dat			relation.html		ways.tmp
coord.dat			nodes.idmap			router.dat		waysopt.dat
coverage.idx		nodes.tmp			router2.dat		wayway.tmp


jacklindeMBP:OSMScout2 jack$` **./OSMScout2 ../maps/hawaii-latest/ ../stylesheets/standard.oss**`
Setting libosmscout logging to level: debug
Can't load translator for locale QLocale(English, Latin, UnitedStates) / "en_US" ( "/Library/Application Support/libosmscout/OSMScout2/translations" )
Loading online tile providers from  ":/resources/online-tile-providers.json"
Loading map providers from  ":/resources/map-providers.json"
MapManager ctor
Reported screen DPI: 113.50000
Map DPI override: 113.00000
Using stylesheet: /Users/jack/Documents/GitHub/libosmscout/stylesheets/standard.oss
Initialize databases
Map DPI override: 113.00000
qml: Gain focus, update popup
qml: Gain focus, update popup
TextFontSize: 17 px
Average char width: 11 px
qml: Position changed:
qml: Positioning is true
qml: Last error 3
Start data loading...
Start rendering timer:10ms
DrawMap()
Start data loading...
Start rendering timer:10ms
DrawMap()
focus-out event
qml: Position changed:
qml:   latitude: 22.62824979934069
qml:   longitude: 114.05691169553468
qml:   altitude: 101.95968627929688
qml:   horizontal accuracy: 65
qml:   vertical accuracy: 10
qml: Position changed:
qml:   latitude: 22.62821683058731
qml:   longitude: 114.05678594927622
qml:   altitude: 99.57131958007812
qml:   horizontal accuracy: 65
qml:   vertical accuracy: 10
qml: Position changed:
qml:   latitude: 22.628177347779328
qml:   longitude: 114.05680029133133
qml:   altitude: 99.66590118408203
qml:   horizontal accuracy: 65
qml:   vertical accuracy: 10
qml: Position changed:
qml:   latitude: 22.62815654378729
qml:   longitude: 114.05680718132957
qml:   altitude: 99.68997192382812
qml:   horizontal accuracy: 65
qml:   vertical accuracy: 10
focus-out event
tap  QPoint(176,384)
qml: tap: 176x384 @ 77.12795010052406 -24.632378192427197 (map center 80.72905103899294 8.09306759622107)
tap  QPoint(176,384)
qml: tap: 176x384 @ 77.12795010052406 -24.632378192427197 (map center 80.72905103899294 8.09306759622107)
focus-out event

still doesn't display map.
expect for your help, thank you!

**Comment by Karry** [comment]
I see the problem - you compiled osmscout without `marisa` library that is optional. So your database don't contains data files for full-text search (`textloc.dat, textother.dat, textpoi.dat, textregion.dat`). But OSMScout2 demo (Qt client library more correctly) don't expect it, it requires these files and skip database loading because it assumes that it is incomplete...

So, as a fast fix for you, install Marisa library on your system (https://github.com/s-yata/marisa-trie), build libosmscout with clean build directory and create your database again...

In will provide proper fix soon. I have to check all places where `text*.dat` files may be used in Qt library and make sure that there is some fallback...

**Comment by Framstag** [comment]
@Karry: OK, please also make a obvious log output, if offline maps are for some reasons disabled. The cause of the problem is not really obvious.

@jialinxie: I recently build and installed marisa library manually since I did not find any brew package. Build afterwards found the library, though I did not test, that is worked as expected. Sorry for the inconvenience.

**Comment by jialinxie** [comment]
@Karry 
@Framstag 
I installed  `marisa ` library just now, and `clean`, `build`, `Import ` again, finally it works!
Thank you very much!
