### ISSUE TITLE
how to build OSMScout2 and dependence-lib for arm-linux platform?

### ISSUE THREAD

**Issue by jialinxie** [Framstag/libosmscout#596]
Hi, i had build and test OSMScout2 demo on OSX and Ubuntu,  that's good!
but how to build it for NXP iM.X6(arm-linux platform with Qt5-sdk) , which libs are essential? is there any reference?
I would appreciate a reply as soon as possible.

**Comment by Framstag** [comment]
Build on other architectures is similar to building under Linux or OS X (or WIndows). We currently recommend the cmake build (while meson should be able to build for all platforms, too). If you need to do corss-compiling you have to do it the cmake make. I wrote a longer response to the mailing list recently regarding building libosmscout for Android + Qt5.

Regarding libraries:
* On the device you normally only need the base library (libosmscout) which contains all the code for loading the database and do routing and location lookup. You need libosmscout_map and libosmsocut_map_XXX (in your case Qt) to render maps using one of the render backend libraries.
* For Qt you might also use the libosmsocut_client_qt library, which already contains much of the needed client application code.
* So for the client you only need qt as external dependency and possibly low level libraries that should always be available (iconv, math,...).
* You do not need the import library on the device, as it is assumed that you build the databases on a separate central server system.

Does this answer your question? If yes, please close the issue. Also note, that questions are better asked on the mailing list instead by raising an issue (though we will handle the issue anyway), which suggests that there is a bug.

Also see: http://libosmscout.sourceforge.net/documentation/source/

**Comment by jialinxie** [comment]
Thank you very much!
