### ISSUE TITLE
cmake build on debian check for protobuf-compiler is missing

### ISSUE THREAD

**Issue by DerKleinePunk** [Framstag/libosmscout#597]
the cmake check for the libs an header but not for the compiler. cmake is green but on build it run into an error. Because with binary to compile is missing

**Comment by DerKleinePunk** [comment]
when libagg not found performenstest are not building

**Comment by Framstag** [comment]
Question: The third one is not an build but an "installation problem after successful build" problem? Right?

**Comment by Framstag** [comment]
Regardig protobuf: We use a custom version of the Findprotobuf.make file, perhaps we should first migrate to the version that is part of cmake? It looks like it does test for protoc, too!ß

**Comment by Framstag** [comment]
@DerKleinePunk: Regarding missing agg library: What is the exact error, I do not have agg under OS X IMHO and do not get an compiler error!?

**Comment by DerKleinePunk** [comment]
yes The third one is happend when tartget is install.

https://cmake.org/cmake/help/v3.0/module/FindProtobuf.html
PROTOBUF_PROTOC_EXECUTABLE i think it make test for the Binary

Agg i don't Understand it the Error message was PerformanceTest:40:36 Header not found

**Comment by Karry** [comment]
Hi. 

I prepared merge request that disable protobuf library when protoc is not installed.

But I can't reproduce libagg problem - when I am trying to build it in Ubuntu 17.10 docker without `libagg-dev` package, everything seems to be correct. `libosmscout-map-agg` is not compiled and Demos/PerformanceTest is build without error...

**Comment by Karry** [comment]
Please take a look what is your `HAVE_LIB_OSMSCOUTMAPAGG` variable:
```
cat Demos/include/PerformanceTest/config.h | grep HAVE_LIB_OSMSCOUTMAPAGG
```
It is possible that you are including different `config.h`. Can you check include paths by running `VERBOSE=1 make`, you will see full gcc arguments. And at the end, you may try to clean your build directory please?

**Comment by Framstag** [comment]
@DerKleinePunk: Can we close the issue or is the 3rd point still valid and has to be fixed?

**Comment by DerKleinePunk** [comment]
@Framstag we close it
