### ISSUE TITLE
OSMScout for arm-linux platform is too slow to render maps

### ISSUE THREAD

**Issue by jialinxie** [Framstag/libosmscout#598]
Hi, i build and run OSMScout demo on NXP iMX6ULL ,which is arm-linux platform,its frequency is 528MHz., i found that when i move and zoom, it renders too slow. 
Any way to make it rendering faster?
i want to know if using mesa lib will be faster. i would be grateful for your reply.

**Comment by Karry** [comment]
Hi.

Qt renderer use software rendering to canvas and it is displayed by QML frontend then (GLES on mobile systems usually). So, when moving of map canvas is fluent, but you are waiting for displaying the map, there is no many options how to improve it...

From my experiments, map rendering with osmscout is highly affected by storage speed. If this is your case, you can improve situation with bigger caches. When the main rendering tooks long time, you may try to use simpler map style... But you should run some reproducible performance test anyway. 

Please execute `Demos/PeformanceTest` on your device:
```
$ ./Demos/PerformanceTest 
DrawMap 
  <map directory> <style-file> 
  <lat_top> <lon_left> <lat_bottom> <lon_right> 
  <start zoom> <end zoom>
  <tile width> <tile height>
  <cairo|Qt|ag|opengl|noop|none>
  [heap profile prefix]
```
for example:
```
./Demos/PerformanceTest \
  ~/Maps/europe-czech-republic-20180323-085859 \
  ../stylesheets/standard.oss \
  50.1290 14.3341 \
  50.0326 14.5856 \
  8 16 \
  1200 1200 \
  Qt
```
It prints nice summary how long tooks rendering of one tile, how many memory it consumes and how many objects was loaded...
```
...
Level: 15
Tiles: 374
 Used memory: max: 58.4047 MiB avg: 43.0428 MiB
 Tot. data  : nodes: 7320 way: 2609654 areas: 2073478
 Avg. data  : nodes: 19 way: 6977 areas: 5544
 DB         : total: 45497.9 min: 32.2614 avg: 121.652 max: 477.177 
 Map        : total: 62583.3 min: 59.8442 avg: 167.335 max: 617.352
Level: 16
Tiles: 1343
 Used memory: max: 179.967 MiB avg: 59.8667 MiB
 Tot. data  : nodes: 1398789 way: 13792597 areas: 2645898
 Avg. data  : nodes: 1041 way: 10269 areas: 1970
 DB         : total: 299978 min: 41.8754 avg: 223.364 max: 1121.64 
 Map        : total: 220353 min: 43.5441 avg: 164.075 max: 699.328
```
From this output, it is visible that data loading (`DB`) tooks more time (milliseconds) on my notebook than rendering...

**Comment by Framstag** [comment]
Lukas answer is already very good and brings out the essence, if IO is your problem load less data,  if rendering is your problem reduce visual complexity (both of course will reduce the other likely, too). Note also that depending on the actual zoom level performance problems might change and may have different cause. 

Look also at http://libosmscout.sourceforge.net/tutorials/perfopt/ for more details. The page is a little bit old, but most of it should still be true (mainly the actual log output has changed).

**Comment by DerKleinePunk** [comment]
Data on Raspberry 2 B 1Ghz
Can't Test Ot  i'm not using in my project
Data Hessen from http://www.geofabrik.de

./PerformanceTest \
  /home/pi/devtest/map \
  /home/pi/devtest/stylesheets/standard.oss \
  50.0967 8.4868 \
  50.0973 8.5123 \
  8 16 \
  1200 1200 \
  cairo

´´Level: 15
Tiles: 3
 Used memory: max: 16.099 MiB avg: 15.7976 MiB
 Tot. data  : nodes: 31 way: 10842 areas: 18505
 Avg. data  : nodes: 10 way: 3614 areas: 6168
 DB         : total: 472.913 min: 98.8174 avg: 157.638 max: 252.906
 Map        : total: 1520.72 min: 428.465 avg: 506.907 max: 589.875
Level: 16
Tiles: 6
 Used memory: max: 16.8737 MiB avg: 16.771 MiB
 Tot. data  : nodes: 349 way: 32271 areas: 13333
 Avg. data  : nodes: 58 way: 5378 areas: 2222
 DB         : total: 878.262 min: 84.245 avg: 146.377 max: 307.922
 Map        : total: 3965.7 min: 433.539 avg: 660.95 max: 816.573
´´

**Comment by jialinxie** [comment]
@Karry @Framstag @DerKleinePunk 
Thank you!
i will do a PerformanceTest on arm-linux platform as soon as possible,there are some build errors didn't fix yet.
I have read Performance-optimizations docments, it is very comprehensive! I will do some optimization based on this document.
Thank you very much for your enthusiasm and hard work！
