### ISSUE TITLE
Runtime QML error while calling slot with default argument value (just Meson build)

### ISSUE THREAD

**Issue by Karry** [Framstag/libosmscout#607]
When using router with OSMScout2 demo application  (QML), it fails with this error:
```
qml: Routing...
qrc:/qml/SearchDialog.qml:36: Error: Unable to determine callable overload.  Candidates are:
    setStartAndTarget(LocationEntry*,LocationEntry*)
    setStartAndTarget(LocationEntry*,LocationEntry*,QString)
```
It happens just with OSMScout2 Meson build, CMake build is fine. It seems that Meson calls moc (Qt meta object compiler) incorrectly... We need to investigate if there is something wrong in our build or Meson upstream...

**Comment by Framstag** [comment]
Works for me now. Thanks Lukas!
