### ISSUE TITLE
the problem about looking up poi

### ISSUE THREAD

**Issue by lmclmc** [Framstag/libosmscout#620]
hello, I have a problem about looking up poi, when i input coordinate range and poi type , i got a lot of poi , but, some of poi have no name.         for example:

    + Node 10851094 amenity_atmlat = 40.0297 lon = 116.306 
+ Node 10851103 amenity_atmlat = 40.0299 lon = 116.306 
+ Node 10851142 amenity_atmlat = 40.0302 lon = 116.306 
+ Node 10861349 amenity_atmlat = 40.035 lon = 116.303 
+ Node 10877155 amenity_atmlat = 40.0459 lon = 116.403 华夏银行
+ Node 10877283 amenity_atmlat = 40.0459 lon = 116.404 交通银行
+ Node 10877844 amenity_atmlat = 40.0513 lon = 116.407 中信银行
+ Node 10887809 amenity_atmlat = 40.0563 lon = 116.304 工商银行ATM

my application startup instruction is "./test ./mapdir  39.866 116.38 39.876 116.40  amenity_bank"

I didn't find these poi without name in google map,
is there a problem for this?

thanks for your reply.

**Comment by Karry** [comment]
Hi. There is no problem probably. OSM Scout databases are generated from OpenStreeMap data. This geographical database is created by volunteers manually and from freely available data. It has nothing to do with Google Maps.

When I am looking to resulted coordinates, there are ATMs points without name. For example this one: https://www.openstreetmap.org/node/2291485118
