### ISSUE TITLE
Area is rendered with different type sometimes

### ISSUE THREAD

**Issue by Karry** [Framstag/libosmscout#622]
Hi. 

Areas are sometimes rendered with its "global" type and sometimes with type of its outer type. It depends on some weird conditions, like how big is rendered area. See attached renders and look at this islet on the river:
https://www.openstreetmap.org/relation/3366544

```
Area {
  OSM id: 3366544
  fileOffset: 95712737
  type: leisure_park
  boundingBox: [50,09431 N 14,43179 E - 50,09704 N 14,44883 E]
  center: 50,09568 N 14,44031 E
  cell level: 14


  master

  role[1] {
    outer
    type: place_islet

...
```

I am not sure what type should be used, but renderer should be stable.

Render commands:
```
./Demos/DrawMapQt \
  europe-czech-republic-20180623-155839 \
  ../stylesheets/standard.oss \
  2000 970  \
  14.41 50.08127 \
   $(( 1 << 14 )) \
  DrawMapQt-test14.1.png
```

![drawmapqt-970](https://user-images.githubusercontent.com/309458/42079275-869d38f0-7b7f-11e8-8f30-a2da1040b0e0.png)

```
./Demos/DrawMapQt \
  europe-czech-republic-20180623-155839 \
  ../stylesheets/standard.oss \
  2000 980  \
  14.41 50.08127 \
   $(( 1 << 14 )) \
  DrawMapQt-test14.1.png
```

![drawmapqt-980](https://user-images.githubusercontent.com/309458/42079276-86c1b69e-7b7f-11e8-9bc3-134f414905e2.png)

**Comment by Framstag** [comment]
OK, here is the problem. The island https://www.openstreetmap.org/way/4865922 is drawn multiple times!
It is once drawn as part of the above mentioned type. But it is also drawn (later on) as island itself as part of the following relation:

https://www.openstreetmap.org/relation/19221#map=13/50.0983/14.4313

Which one is draw first (and thus with which type it is drawn) is likely dependent on the sort order (=> AreaSorter) of two areas with exactly the same bounding box. It could even be possible, that the sorting is stable for me but not for you (C+ implementation detail).

The only solutions I could image is dropping one of the two usages during relation import. There is already a list to make sure, that areas are not rendered them self, if already part of a relation. I would also have to check for further occurrences during relation building and exchange them with a clipping area without a type. Problem: The first occurrence will win (with the resulting consequence regarding types). The type thing could be fixed though by storing the type as result of master ring relation handling, too.

The alternative would be to always only clip embedded areas and draw them as real areas later on. This will increase the database size as the list of nodes and type etc. will be stored two times.

Opinion?

**Comment by Karry** [comment]
Thank you for investigating this. Dealing with relations is pretty complex :-) I am suggesting to solve this concrete case in area sorter - just render outer-ring-areas later...

I am worry that more complex import processing will break another another areas.

**Comment by Framstag** [comment]
Yes, the solution is not the fastest (because it still may render areas multiple times), but the safest to implement. I too worry that other solutions are more complex with more side effects and hope that such cases are rare enough to not cause principle performance issues.

Thus thanks for the patch. Waiting for the builds to finish...
