### ISSUE TITLE
Building libosmscout opengl backend on Windows

### ISSUE THREAD

**Issue by shujaatak** [Framstag/libosmscout#625]
Where can I find step by step instructions to build libosmscout opengl backend on Windows? 
Also when I was trying to generate Visual Studio Project files using cmake I get this error: 
```
CMake Error at CMakeLists.txt:226 (create_private_config):
  Unknown CMake command "create_private_config".
```

**Comment by Framstag** [comment]
Hello and thanks for your interest.

We are doing a number of Windows-based builds. See https://ci.appveyor.com/project/Framstag/libosmscout

As you can see, we have successful Visual Studio 2015 based builds using meson or cmake. So for further analysis it would be interesting, where our build is different to the named appveyor build.

We current do not have a central build for OpenGL support under Windows and VisualStudio. The cmake (and meson) files should support OpenGL builds under Linux and Mac OS. From the Build logs I see that the meson msys build also builds the OpenGL backend.

The main build for missing support for OpenGL is likely just missing build dependencies in the central build. Also I do not know how complex it is to supply OpenGL dependencies under VisualStudio.

So the build should work in principle but smaller tweaks to the build environment and/or the build files may be possible. Note also that the OpenGL is not in similar quality as the QT or Cairo backends. It misses some rendering features (see issues) and is now to have some UTF-16/32 endianess problems at least under Mac OS (which should be easy to fix). While the rendering performance is great the integration of data rendering into the rendering pipeline seems to require further optimization. 

As such patches to the build or the code are very welcome!

**Comment by shujaatak** [comment]
As there is lack of documentation and also my understanding of the folders structure of this project so I dont even know from where to start working on it. 
Even a small one paragraph overview of the project  and its folders structure could suffice. 
Right now I am lost in the bunch of files and folders which are somehow magically interlinked together making for me difficult to understand which files & folders I need to look for. If I knew those pieces of information for OpenGL backend then I could have build this project on my system and resolved the missing dependencies if any.

**Comment by Framstag** [comment]
Ah, OK. I might help :-) See http://libosmscout.sourceforge.net/documentation/ and also the chapters Tutorials and Examples.

**Comment by shujaatak** [comment]
It seems I was wrong! There is alot of information here http://libosmscout.sourceforge.net/documentation/
Thank you for the link.

I am going to read the documentation and see if I can successfully build libosmscout.

**Comment by Framstag** [comment]
Closing because there were no further questions. If there are further questions please use the mailing list or create  new issue.
