### ISSUE TITLE
how to load or unload contour line independently?

### ISSUE THREAD

**Issue by jialinxie** [Framstag/libosmscout#647]
hi, i have added contour lines refer to [http://libosmscout.sourceforge.net/tutorials/importing/](url);
it use both files xxx.osm and xxx.osm.pbf as input of Import tool.
If i don't want to display this contour line, how to unload this contour line?
btw,how to import multiply contour line independently? Thanks for any reply!

**Comment by Karry** [comment]
Hi. 

Our standard style contains flags that may be used to deactivate some kind of objects for rendering. There already exists flag [`elevationContours`](https://github.com/Framstag/libosmscout/blob/master/stylesheets/standard.oss#L20) that may be used for hiding contour lines. Take a look to `StyleConfig::AddFlag` and its usages... In QML is available `StyleFlagsModel` to manipulate with style flags.

To your second question, you can import multiple osm files to one (lib)osmscout database. But there is no possibility to import them independently. I am expecting that you want to import contour lines from multiple sources and choose in runtime between them? Simples solution for that would be to import separate databases and combine it in renderer...

**Comment by jialinxie** [comment]
thank you very much, i tested this flag just now, it works.
And the second question, thanks for your advice, it is totally OK.

**Comment by jialinxie** [comment]
Hi, I will ask a similar question, :)
now i have imported several databases which all contains contour line, such as china, thailand, japan,   i want to activate contour line on china, but  hide contour line on Thailand and Japan, if i modify the flag elevationContours[https://github.com/Framstag/libosmscout/blob/master/stylesheets/standard.oss#L20](url), it only activate or deactivate contour line on all databse, how to operate alone？Thanks for any reply!

**Comment by Karry** [comment]
It is not possible with Qt client api right now. But it is possible in principle, you can create own UI model, and logic in DBThread... You can look to `DBThread::LoadStyle` how it is implemented currently... 

I am just curious, what is usecase for this, why do you want to do that?

**Comment by jialinxie** [comment]
thanks for your reply!
This is a small demand for our products, so it doesn't matter if there is no api, thanks anyway!
