### ISSUE TITLE
Build Windows VS2017 64 with vcpkg

### ISSUE THREAD

**Issue by DerKleinePunk** [Framstag/libosmscout#654]
build 

vcpkg install cairo:x64-windows
vcpkg install sdl2:x64-windows
vcpkg install sdl2-image[libjpeg-turbo]:x64-windows
vcpkg install sdl2-image[libwebp]:x64-windows --recurse
vcpkg install sdl2-mixer:x64-windows
vcpkg install sdl2-net:x64-windows
vcpkg install sdl2-ttf:x64-windows
vcpkg install pango:x64-windows
vcpkg install libxml2:x64-windows
vcpkg install protobuf:x64-windows

https://github.com/s-yata/marisa-trie/releases

set QTDIR=F:/Tools/Qt/5.11.1/msvc2017_64

SET MARISA_ROOT=.\marisa
set CMAKE_INCLUDE_PATH=%MARISA_ROOT%\include
set CMAKE_LIBRARY_PATH=%MARISA_ROOT%\lib

cmake -G "Visual Studio 15 2017 Win64" -DQTDIR=%QTDIR% -DCMAKE_PREFIX_PATH=%QTDIR%/lib/cmake -DCMAKE_INSTALL_PREFIX=.\output -DCMAKE_TOOLCHAIN_FILE=F:/Mine/OpenSource/vcpkg/scripts/buildsystems/vcpkg.cmake ..
cmake --build . --target install --config Debug

geting Error:

  f:\mine\opensource\libosmscout-code\libosmscout\include\osmscout\util\exception.h(62): error C3646: "_NOEXCEPT": Unbe
kannter Überschreibungsspezifizierer (Quelldatei wird kompiliert F:\Mine\OpenSource\libosmscout-code\libosmscout\src\os
mscout\CoordDataFile.cpp) [F:\Mine\OpenSource\libosmscout-code\vcbuild\libosmscout\OSMScout.vcxproj]

Fix in Exception.h :
#include <exception>
#include <string>

#include <osmscout/CoreImportExport.h>
#include <system_error>

#if defined(_MSC_VER)
	#if (_MSC_VER <= 1910)
		#include <yvals.h>
		#define OSMSCOUT_NOEXCEPT _NOEXCEPT
	#else
		#define OSMSCOUT_NOEXCEPT noexcept
	#endif
#else
#define OSMSCOUT_NOEXCEPT noexcept
#endif

**Comment by Framstag** [comment]
Push change. Please test.

**Comment by DerKleinePunk** [comment]
try with

cd F:\Mine\OpenSource\vcpkg
git pull
bootstrap-vcpkg.bat
cd F:\Mine\OpenSource\libosmscout-code\vcbuild
set path=%PATH%;F:\Mine\OpenSource\vcpkg
vcpkg upgrade --no-dry-run
vcpkg remove --outdated
vcpkg install cairo:x64-windows
vcpkg install sdl2:x64-windows
vcpkg install sdl2-image[libjpeg-turbo]:x64-windows
vcpkg install sdl2-image[libwebp]:x64-windows --recurse
vcpkg install sdl2-mixer:x64-windows
vcpkg install sdl2-net:x64-windows
vcpkg install sdl2-ttf:x64-windows
vcpkg install pango:x64-windows
vcpkg install libxml2:x64-windows
vcpkg install protobuf:x64-windows
vcpkg install glfw3:x64-windows
set QTDIR=F:/Tools/Qt/5.11.2/msvc2017_64
SET MARISA_ROOT=.\marisa
set CMAKE_INCLUDE_PATH=%MARISA_ROOT%\include
set CMAKE_LIBRARY_PATH=%MARISA_ROOT%\lib

cmake -G "Visual Studio 15 2017 Win64" -DQTDIR=%QTDIR% -DCMAKE_PREFIX_PATH=%QTDIR%/lib/cmake -DCMAKE_INSTALL_PREFIX=.\output -DCMAKE_TOOLCHAIN_FILE=F:/Mine/OpenSource/vcpkg/scripts/buildsystems/vcpkg.cmake ..
cmake --build . --target install --config Debug

Debug is not build because the libmarisad.lib is not used
libmarisa.lib(agent.obj) : error LNK2038: Konflikt ermittelt f³r "_ITERATOR_DEBUG_LEVEL": Der Wert "0" stimmt nicht m

cmake --build . --target install --config Release
is Build with  95 Warnung(en)

the most warnings are Type errors
f:\mine\opensource\libosmscout-code\libosmscout-map\include\osmscout\labellayouter.h(488): warning C4244: "Argument":
 Konvertierung von "T" in "int", möglicher Datenverlust [F:\Mine\OpenSource\libosmscout-code\vcbuild\libosmscout-map-directx\OSMScoutMapDirectX.vcxproj]

Strange:
-- Could NOT find GLFW (missing: GLFW_LIBRARIES) (found version "3.2.1")
It don't know if OpenGL is really need on Windows

Build Ok
But not Tested

**Comment by Framstag** [comment]
@DerKleinePunk: OK to close the issue or should I wait for test?
