### ISSUE TITLE
how to index government agencies and import POI?

### ISSUE THREAD

**Issue by jialinxie** [Framstag/libosmscout#670]
hi,
 i want to lookup for some government agencies POI from china-latest database.
 i tried many types from map.ost , but didn't find it. Is there any type in map.ost means government agencies? If not, how to import such OSM files contained poi to database?(I have converted a osm file from shp file which contains china's government agencies, but imported fail by Import tools)

**Comment by jialinxie** [comment]
thanks for your detailed answer, i will try as soon as possible!

**Comment by Karry** [comment]
You also wrote that your original source was `shp` format converted to `osm`. Can you share these files with us, to check where can be problem?
