### ISSUE TITLE
Is there any way to know whether the database include contour elevation data?

### ISSUE THREAD

**Issue by jialinxie** [Framstag/libosmscout#691]
Hi
I converted .hgt file to osm, then import osm to database, so i have several database folder now, but how to know whether it include contour elevation data? Is there any API or files, which i can get the answer.Thanks!

**Comment by Framstag** [comment]
You can read the distribution.dat using TypeDistributionDataFile. It is used during internal import processing and is thus not official part of "the database". But you can still use it anyway (if copied over), to check if your contour types have a count > 0.

Have not tried it, but should work, too.

**Comment by jialinxie** [comment]
thank you !
You all gave me a good answer!
