### ISSUE TITLE
Aqua alta in Venezia

### ISSUE THREAD

**Issue by vyskocil** [Framstag/libosmscout#697]
I built the map database from a quite old italy.osm.pbf from Geofabric and saw that Venice was "flooded' then I downloaded the lastet italy.osm.pbf from the same source (http://download.geofabrik.de/europe/italy-latest.osm.pbf) but the result was the same : 

https://www.casimages.com/i/19020803453421126216112977.png.html

https://www.casimages.com/i/19020803453321126216112976.png.html

**Comment by Karry** [comment]
Hi Vladimir. What arguments are you using for the import? Did you try to specify ` --bounding-polygon` with corresponding `*.poly` file? When I am looking to my latest import, it seems to be fine: https://osmscout.karry.cz/europe/italy-19-20190112-1612/

**Comment by Framstag** [comment]
I haven't looked at the current state, but in the past there was also the problem that parts of venice were not rendered correctly because island were not rendered with land background. See for example:

https://www.openstreetmap.org/relation/2683672 would require

 [MAG region-] {
   [TYPE place_island,
         place_islet] {
     AREA {color: @landColor;}
   }
 }

See also 

https://www.openstreetmap.org/relation/3049430

which shows that rendering Venice is not the usual water, land, coastline scenario.

At that time I was thinking of faking coastlines based on above correlation of relations, since this would/could make rendering simpler.

**Comment by vyskocil** [comment]
@Karry I passed to —bounding-polygon the .poly file found alongside the osm.pbf on geofabrik

**Comment by Karry** [comment]
Can you upload your type definition (`*.ost` file) used for import and your map style please? Or you are using files from Tim's master?

**Comment by Framstag** [comment]
Any news on this?

**Comment by vyskocil** [comment]
I'm back from Venezia and survived the map aqua alta ;-)
Here are the map.ost and rando.oss files that are slightly modified from the reference files : 

[Archive.zip](https://github.com/Framstag/libosmscout/files/2879314/Archive.zip)

**Comment by Karry** [comment]
Problem is in your stylesheet, you don't have style for `place_island` area...

```
 [MAG region-] {
   [TYPE place_island,
         place_islet] {
     AREA {color: #ff0000;}
   }
 }
```

![obrazek](https://user-images.githubusercontent.com/309458/53154258-aaf6c900-35ba-11e9-963d-e986e87e6b8b.png)

**Comment by Karry** [comment]
Btw, when you are using stylesheet with multiple databases, consider comment-out `_tile_coast` style...

**Comment by Karry** [comment]
Btw, can I use your style as alternative one in my application? I is more contrast and I like some visuals, like cliff :-)

**Comment by vyskocil** [comment]
Thanks @Karry the `place_island, place_islet` style has solved the issue !
Also for the `_tile_coast` style that I forgot to comment in this stylesheet.
You are welcome to use this stylesheet, but there are still some issues with road labels / road names : I want to display both along the path and don't display the shields...
I will also add natural_ridge drawing, as I found it missing when hiking in Slovenia ;-)
