### ISSUE TITLE
Eastern european chars like Č,... break label displaying for iOS

### ISSUE THREAD

**Issue by vyskocil** [Framstag/libosmscout#703]
When a label contains a "č" the label is cut sometimes only the č is displayed if it's the first letter or the label is cut in the middle where this char occur.
I'll try to fix it in libosmscoutiosx library.

**Comment by Karry** [comment]
Sadly, I have no change how to check it. Or do you know about some way howto build iOS renderer on Linux?

**Comment by vyskocil** [comment]
I think it's not possible (ie legal) to build iOS renderer on Linux...
But I'll have a look at this soon, maybe the issue is only that the "č" glyph is not available in the font I use...

**Comment by vyskocil** [comment]
I was right, the font I was using on the iPhone: Gill Sans is the culprit. I removed `drawParameter.SetFontName("GillSans");` initialization in my code and the issue is gone !
Maybe some very clever glyph substitution is possible in the label drawing code when a glyph is missing in the chosen font but for now it'll stay like that...
