### ISSUE TITLE
Add support for forward/backward maxpeed

### ISSUE THREAD

**Issue by Karry** [Framstag/libosmscout#717]
When speed is different for every direction, `maxspeed:backward` and `maxspeed:forward` may be used. We don't support these tags currently. I can imagine that we will use minimum from both directions as simple, fast and little bit wrong solution. But these tags are used for [short segments usually](http://overpass-turbo.eu/s/HH2) and it would be possible without changing database format. Proper solution would be to enhance current MaxSpeed feature, but every place would need to evaluate way direction...

**Comment by Framstag** [comment]
@Karry Please check and close if OK (or keep, if you actually want to split max speed into to values).

**Comment by Karry** [comment]
Thank you! Minimum of both is better than nothing.
