### ISSUE TITLE
Overlapping icons with alpha channel are clipped away

### ISSUE THREAD

**Issue by Framstag** [Framstag/libosmscout#752]
If you activate the highway_Street_lamp type and style (ost and oss files), you'll see, that the actual symbols are clipping each other away on the way. Most of the time you only see 50% of the symbols ;-)

That did work before, I assume that the new LabelLayouter behaves differently.

@Karry: Can you take a look? Is it possible to special case this?

**Comment by Karry** [comment]
Hi Tim. 

I will re-check this. But yes, current label layouter (merged year ago) behaves differently than the old one. Icon/symbol paddings are not merged. It means, when you have one symbol with padding 5mm and second symbol with padding 3mm and distance between them is 5mm, old layouter draw both. But new one needs space between these two symbols 8mm... I decreased default padding for that reason (if I remember correctly).

**Comment by Karry** [comment]
...it really seems to be too aggressive with removing, it removes many lamps even when using smaller symbol and no padding...

**Comment by Framstag** [comment]
Yes, looks like bounding box of icons/symbols is not correctly calculated or similar.  In the old solution I special-cased bounding box between "only-icon" labels (as far as I remember). In principle this could be done again (if it is not still the case). But the problem in this case seems to be "bigger" ;-)

**Comment by Karry** [comment]
Problem is in the ground projection in symbol, on many places it is not handled properly. One such place is label / icon / symbol layouter... I will prepare merge request.

**Comment by Karry** [comment]
Specially for lamp symbol, it would make sense to me define symbol padding in stylesheet and allow negative values - this will allow us to render light cyrcle with overlaps.

**Comment by Framstag** [comment]
I tested this again. The effect seams to be still there - depending on zoom level lamps appear and disappear.

I'm not sure if a padding values would help. What about disabling collision detection if the objects under comparison have (both?) alpha channel?

**Comment by Karry** [comment]
It may be option too. But for symbols (lamp, tree), only outer primitive may have alpha channel. It will be even more complicated with SVG icons, that are backend specific. Padding solution seems to me more general...

**Comment by Framstag** [comment]
OK, this is an argument. Let's try the padding solution. In case of "lamp" we would then just define the padding in a way, that complete overlap is possible!?

Can you gibe a concrete example how this could/would look like in the style sheet? What would we/I need to do, to get this to work?

**Comment by Karry** [comment]
> ...define the padding in a way, that complete overlap is possible!?

yes, when padding will be negative and bigger that symbol size

> Can you give a concrete example how this could/would look like in the style sheet? 

I can imagine something like this:
```
[TYPE highway_street_lamp] NODE.ICON { 
    symbol: highway_street_lamp;
    padding:  -2.0mm;
}
```

> What would we/I need to do, to get this to work?

In `LabelLayouter` usage of `MapParameter::iconPadding` should be replaced by explictly defined padding in icon/symbol style... Plus special condition when padding is greater than object dimension.

**Comment by Framstag** [comment]
Added overlay boolean flag for icon style.

The overlay flag (default: false) sets the clipping relevant boundary
of the icon to 0,0, thus assuring that the icon is not clipped at all
because of other icon/symbols,labels... Make sure, that is has enough
alpha channel for this to look good.

Is is still possible to add padding options to the style, too. overlay was just simpler to implement and more convenient to use.
