### ISSUE TITLE
C# binding is broken on Ubuntu 14.04.5 (cmake)

### ISSUE THREAD

**Issue by martonmiklos** [Framstag/libosmscout#77]
The build fails with the following error:

`[ 99%] Swig source
/home/mm/Projektek/jolla/libosmscout/libosmscout-binding/../libosmscout/include/osmscout/TypeConfig.h:265: Warning 325: Nested struct not currently supported (TypeCondition ignored)
/home/mm/Projektek/jolla/libosmscout/libosmscout-binding/../libosmscout/include/osmscout/TypeConfig.h:875: Error: Syntax error in input(3).
make[2]: *** [libosmscout-binding/CSharp/libosmscoutCSHARP_wrap.cxx] Error 1
make[1]: *** [libosmscout-binding/CMakeFiles/osmscout_binding_csharp.dir/all] Error 2
make: *** [all] Error 2
`

OS: Ubuntu 14.04.5 64 bit
cmake 3.5.2 from this PPA: https://launchpad.net/~george-edison55/+archive/ubuntu/cmake-3.x
(I do not think it is matters)

**Comment by Framstag** [comment]
OgreTransporter offered a pull request to seems to reducing building the bindings if VisualStudio is available. If this fixes your problem, please close,. If not, please tell under which conditions the build should (not) work.

**Comment by martonmiklos** [comment]
C# binding is now disabled by the cmake. Thank you!
