### ISSUE TITLE
Weird results from "way low zoom" index

### ISSUE THREAD

**Issue by Karry** [Framstag/libosmscout#771]
Hi. 

I found that some highways are missing when data are loaded for "low zoom" index. Minimum reproducible case that I was able to found is with "US west" database [1].

When map is rendered with this command:
```
./Demos/DrawMapSVG --debug --dpi 391 north-america-us-west-20190810-153136 \
  standard.oss \
  1920 1078 \
  38.86168979875609 -112.43876813899314 \
  64 highway-64-391-1078.svg
```

highway `I 15` is displayed on the map [2], but when map high is decreased just by one pixel, this highway disapears [3]!

```
./Demos/DrawMapSVG --debug --dpi 391 north-america-us-west-20190810-153136 \
  standard.oss \
  1920 1077 \
  38.86168979875609 -112.43876813899314 \
  64 highway-64-391-1077.svg
```

Tim, do you have any idea where the problem may be? I Hope that I will be able to dig it deeper soon... 

1) https://osmscout.karry.cz/north-america/us-west-19-20190810-1526/
2) https://osmscout.karry.cz/bugs/highway-64-391-1078.svg
3) https://osmscout.karry.cz/bugs/highway-64-391-1077.svg

**Comment by Karry** [comment]
This one was hard, but I found it during my 5 hour transfer on Franfurkt airport :-) I will submit merge request when I will be on usable wifi...

**Comment by Framstag** [comment]
I've seen your request, but had not yet time to look at it. I'm glad you found it.

you are in Germany? Likely not close to Dortmund?

**Comment by Karry** [comment]
Unfortunately no. I was just transfering there. I'm in the Denver (US) for Cppcon that starts at Monday...

**Comment by Framstag** [comment]
@Karry: I assume, this issue can be closed now?
