### ISSUE TITLE
Import parameter --langOrder is not working

### ISSUE THREAD

**Issue by vyskocil** [Framstag/libosmscout#777]
I imported the latest france.osm.pbf from geofabrik with the following command :
 
`Import --destinationDirectory . --langOrder fr,# --bounding-polygon ../france.poly ../france.osm.pbf ../france.hgt.osm.pbf`

I expected that `name:fr` tags would be parsed before `name` tags but this isn't working.
Here is a sample, a peak at the French and Italian border, the "Grand Cimon de Rabuons" in french and "Becco Alto d'Ischiator" for the Italian people. Here is the OpenStreetMap data : 

<img width="599" alt="Screenshot 2019-10-06 at 12 08 36" src="https://user-images.githubusercontent.com/452704/66267649-f0a78f80-e833-11e9-91c6-44be06166bed.png">

Here follow screenshots from OSMScout2 where we could see that this is always the Italian name that is drawn and we could not find the french name : 

<img width="484" alt="Screenshot 2019-10-06 at 12 06 21" src="https://user-images.githubusercontent.com/452704/66267676-572cad80-e834-11e9-9ca0-c2452f2a7a9d.png">

Searching for "Grand Cimon de Rabuons"... it is not found. We could also see that the search text is overlapping the textfield : 

<img width="481" alt="Screenshot 2019-10-06 at 12 27 19" src="https://user-images.githubusercontent.com/452704/66267709-b094dc80-e834-11e9-926e-31bb6e2310e1.png">

Searching for "Becco Alto d'Ischiator" : 

<img width="480" alt="Screenshot 2019-10-06 at 12 07 36" src="https://user-images.githubusercontent.com/452704/66267685-6f9cc800-e834-11e9-9d60-dfff8ebd80e5.png">

**Comment by vyskocil** [comment]
I also noticed this repeating warning in the logs :

```
Error in UTF8StringToWString()Illegal byte sequence
Error in UTF8StringToWString()Illegal byte sequence
Error in UTF8StringToWString()Illegal byte sequence
Error in UTF8StringToWString()Illegal byte sequence
Error in UTF8StringToWString()Illegal byte sequence
Error in UTF8StringToWString()Illegal byte sequence
...
```

**Comment by Framstag** [comment]
This is not the way the lang feature works. Depending on the mang sitch names are stored in to the Name and NameAlt feature. During rendring you can the register a LabelProvider/Factory implementation to the StyleConfig that returns a label string based on the MapParameter and a FeatureValueBuffer. I'm not sure, which one is assigned by default in the demo application, but in case you should write on of these to implement the behaviour that you expect. Does this help?

Regarding the errors: 
This is an error from the iconv library. The string read is no valid UTF-8. Please check if this is correct. Possibly there is an initialisation error with iconv in case you get too many or wrong errors?

**Comment by vyskocil** [comment]
I'm not interested in this case with the NameAlt feature, only the Name feature, I would like it to be ordered at Import time, `name:fr` first, then `name` and I thought that the `--langOrder` was just doing this reading the help from the Import command : 

```
 --langOrder <#|lang1[,#|lang2]..>    language order when parsing lang[:language] and place_name[:language] tags
                                      # is the default language (no :language) (default: #)
```

If this is not what the --langOrder parameter should do, what does it mean ?

**Comment by Framstag** [comment]
The relevant code is in the Import-Library, Import.cpp starting with line 1117:

```
    progress.Info("Parsed language(s) :");
    uint32_t langIndex = 0;
    for(const auto& lang : parameter.GetLangOrder()){
      if(lang=="#"){
        progress.Info("  default");
        typeConfig->GetTagRegistry().RegisterNameTag("name", langIndex);
        typeConfig->GetTagRegistry().RegisterNameTag("place_name", langIndex+1);
        typeConfig->GetTagRegistry().RegisterNameTag("brand", langIndex+2);
      } else {
          progress.Info("  " + lang);
          typeConfig->GetTagRegistry().RegisterNameTag("name:"+lang, langIndex);
          typeConfig->GetTagRegistry().RegisterNameTag("place_name:"+lang, langIndex+1);
          typeConfig->GetTagRegistry().RegisterNameTag("brand:"+lang, langIndex+2);
      }
      langIndex+=3;
    }
```

See also the TagRegistry class in Tag.h/.cpp

```
    TagId RegisterNameTag(const std::string& tagName,
                          uint32_t priority);
```

and finally the NameFeature Implementation in TypeFeature.cpp, starting with line 89:

```
  void NameFeature::Parse(TagErrorReporter& /*errorReporter*/,
                          const TagRegistry& tagRegistry,
                          const FeatureInstance& feature,
                          const ObjectOSMRef& /*object*/,
                          const TagMap& tags,
                          FeatureValueBuffer& buffer) const
  {
    std::string name;
    uint32_t    namePriority=0;

    for (const auto &tag : tags) {
      uint32_t ntPrio;
      bool     isNameTag=tagRegistry.IsNameTag(tag.first,ntPrio);

      if (isNameTag &&
          (name.empty() || ntPrio>namePriority)) {
        name=tag.second;
        namePriority=ntPrio;
      }
    }

    if (!name.empty()) {
      auto* value=static_cast<NameFeatureValue*>(buffer.AllocateValue(feature.GetIndex()));

      value->SetName(name);
    }
  }
```

So you can register multiple languages in --langOrder. The priority is increasing. The tag language specific name tag with the highest priority should win. You can use "#" as a placeholder for the non-language specific version. Parameters int he langOrder string are divided by "," (as you can see from ParseLangOrderArgument in Import.cpp of the Importer itself).

Sorry for the late answer, I hope this helps?

**Comment by vyskocil** [comment]
Thank you for the detailed answer, I think I understood the code but I still could not get it why the import command from my initial question ie :

```Import --destinationDirectory . --langOrder fr,# --bounding-polygon ../france.poly ../france.osm.pbf ../france.hgt.osm.pbf```

don't do what I want, that is order the name tags with ":fr" first, then "#", and in my example get the french name first for the peak that has name and a name:fr tags ?

**Comment by Karry** [comment]
Hi Vladimir. Renderer shows "default names" (without language) by default. You have to switch preference of "alternative language" for renderer by setting `MapParameter::SetShowAltLanguage` to true... Take a look Qt renderer: https://github.com/Framstag/libosmscout/blob/master/libosmscout-client-qt/src/osmscout/TiledMapRenderer.cpp#L442

**Comment by vyskocil** [comment]
Hi Karry, thank you for your response, I tried it but it seems this has no effect in my case perhaps because I'm not using alt languages, all I want to achieve is to order what should be parsed for the primary name. 
In my example the peak has a `name` and a `name:fr` tag and I parsed it with `--langOrder fr,#`, so I thought that the primary name I would get when drawing the map would be the name in `name:fr` tag, otherwise what is the meaning of the `--langOrder` flag ?
Here is the help for these `import` flags :  
```
 --langOrder <#|lang1[,#|lang2]..>    language order when parsing lang[:language] and place_name[:language] tags
                                      # is the default language (no :language) (default: #)
 --altLangOrder <#|lang1[,#|lang2]..> same as --langOrder for a second alternate language (default: none)
```
I'm not using `--altLangOrder` only `--langOrder`. Previously I used '--altLangOrder' successfully because I wanted to be able to switch between primary and alt language but in this case I only want to order the primary language and I'm not interested to have a alt language.

**Comment by vyskocil** [comment]
This is what the import process output : 
```
...
+ Loading type config...
   Number of types: 444
   Number of node types: 212 1 byte(s)
   Number of way types: 88 1 byte(s)
   Number of area types: 252 1 byte(s)
   Parsed language(s) :
     fr
     default
   Parsed alt language(s) :
...
```

**Comment by Karry** [comment]
Sorry for misunderstanding. It really looks like a bug :-/ I will take a look on that.

**Comment by Framstag** [comment]
@vyskocil : Please close the issue now (if the fix solves the problem :-))

**Comment by vyskocil** [comment]
Pull request https://github.com/Framstag/libosmscout/pull/784 fixed the issue
