### ISSUE TITLE
how to flush all cache when hide main.qml for OSMScout

### ISSUE THREAD

**Issue by jialinxie** [Framstag/libosmscout#827]
hi
i port OSMScout2 demo to my application, When I open the map(set visible as true on main.qml), the map rendering takes up more than 30M of memory, and as the map is browsed and zoomed, the memory is getting higher and higher. When I exit the map, the memory is not released, so I would like to ask how to release the map memory ?

I have tried calling
`void MapService :: FlushTileCache () `and 
`void MapService :: CleanupTileCache ()` 
 but the memory occupied by the map is not completely released

Any reply or suggestions are greatly appreciated

**Comment by Karry** [comment]
Hi. 

In my mapping application, I want to solve exactly the same problem - release caches when application is on the background for some time: https://github.com/Karry/osmscout-sailfish/issues/193

`FlushTileCache` is enough to clear data tile cache. But there are another layer of caches. When you are using tiled rendering, `TiledMapRenderer` holding cache of rendered map tiles. There is no method to flush this cache out, but it is easy to implement in `TileCache` class. Another cache is object cache (node, way, area) in `DataFile` class and various area indexes. See `Database` class for more details. Again, there is no way howto clear or reduce these caches - yet.

**Comment by Framstag** [comment]
The simplest (and possibly currently most efficient) solution would be to just close the database. I however assume that the time to reopen the database might take too long.

Why? If you for example take a look at AreaNodeIndex.cpp you see, that it builds up an in memory index based on the data while opening the index. Such memory is currently not handled as cachable (which would require a flush() method together wit a check for valid in memory data on every access - and carefully locking). 

I thus suggest to start with a simple manual test application (some of the tests are not automatically started on build but are for manually testing some aspects) that starts the stack, does some rendering waits, calls the existing flush methods, wait and then closes the database. Together with valgrind massif, this show give us hints, how big the potential for more flushing of internal data structures actually is - and how much is required to help you.

**Comment by jialinxie** [comment]
Thank you for your help. Now I temporarily use Flush TileCache, and if the database is closed directly, the memory is not released the next time the database is opened.

**Comment by Framstag** [comment]
Hi, @jialinxie I'm not sure how to interpret your comment. Is there a bug in the close(), open() cyclus, is there something that we can improve or is everything working as expected? Does closing the database free (measurably) more memory that flushing caches?

**Comment by Karry** [comment]
Hi. When you look to `Database::Close()` method, all data files and indexes are destructed there (cleared shared pointer). When the used memory is not decreased after close, I would guess that your allocator don't return memory to the system... There are multiple ways to ask allocator about its caches, fragmentation and real allocated memory... I may recommend you to use Google perf-tools and its tcmalloc for detailed analysis.

**Comment by Karry** [comment]
Btw, you may try to run `malloc_stats();` before and after cache flush. When released memory is not returned to the kernel, you may also try to call `malloc_trim(0)`. I just implemented of releasing caches when system memory is under pressure and it works like a charm :-) https://github.com/Karry/osmscout-sailfish/blob/master/src/MemoryManager.cpp
