### ISSUE TITLE
Qt 5.15 deprecations

### ISSUE THREAD

**Issue by Framstag** [Framstag/libosmscout#879]
Qt 5.15 seems to have new deprecations that result in compiler warnings

```
QPoint QWheelEvent::pos() const
bool QVariant::operator>(const QVariant&) const
int qrand()
```

**Comment by OgreTransporter** [comment]
You missed one ;-)

`/Users/travis/build/Framstag/libosmscout/libosmscout-client-qt/src/osmscout/MapWidget.cpp:108:65: warning: 'QFlags' is deprecated`

Unfortunately I have not (yet) been able to find a fix for this.

**Comment by Framstag** [comment]
Currently no warnings anymore :-)
