### ISSUE TITLE
Routing issue with roundabouts

### ISSUE THREAD

**Issue by vyskocil** [Framstag/libosmscout#887]
Quite recently something was broken with routing, I hadn't used the car profile for some time because I usually use foot itineraries calculations in my app but yesterday I couldn't calculate a route using the car profile which used to work before...
I tried to narrow the problem and found that the culprit seems to be  roundabouts between the start point and the destinations.
Here are two screenshots made with the latest libosmscout code and france.osm.pbf data around location (43.61598, 6.97264), the first one is calculated with the car profile when the destination is just before the roundabout (at the bottom of the picture), if the destination is in the roundabout or after it the route could not be calculated :

![IMG_8318](https://user-images.githubusercontent.com/452704/86243673-12595b80-bba7-11ea-8cc8-e3605540873f.jpg)

Here is a route calculated with the pedestrian profile, it is ok even when the destination is after 2 roundabouts but we could see that the second one is taken on the whole around ! : 

![IMG_8320](https://user-images.githubusercontent.com/452704/86243882-649a7c80-bba7-11ea-8560-66eaf51d35ac.jpg)

**Comment by vyskocil** [comment]
Maybe it is not the roundabout the cause of this issue, I found that if the starting point is after the black dot on the following picture the route could be calculated but if it is before it in the red zone on the picture the route calculation fail : 

![Screenshot 2020-07-01 at 19 29 05](https://user-images.githubusercontent.com/452704/86274400-ed2e1280-bbd1-11ea-946a-0dc996b44080.JPG)

**Comment by Karry** [comment]
Can you provide me exact coordinates when routing fails? I tried for example `43.61630 6.97148` as a start and `43.61457 6.97354` as destination and it works fine... 

Here is last step from routing animation:
```
./Demos/RoutingAnimation \
  --zoom 18 \
  --style ../stylesheets/standard.oss \
  ~/Maps/europe-france-20200701-200659 \
  43.61630 6.97148 \
  43.61457 6.97354
```

![0000079](https://user-images.githubusercontent.com/309458/86326226-ad067880-bc41-11ea-96a9-ef440caab1ae.png)

**Comment by vyskocil** [comment]
Hi Karry !
Thank you for investigating !
I tried with the from/to coordinates of your sample and it also works for me with ./Demos/RoutingAnimation but not in my app... I'll check what's wrong with my code because the same calculation used to work...

**Comment by Karry** [comment]
I recently changed how route cost is calculated. Do you use custom RoutingProfile ? Make sure that you have all routable types in your "carSpeedTable"...

**Comment by vyskocil** [comment]
I found the issue, it is indeed related with the carSpeedTable 👍

**Comment by Karry** [comment]
Wtf? I was expecting that some type may be missing, but just change of some speed should not break it! It seems that "cost reserve" is too small and we should increase the default...

**Comment by vyskocil** [comment]
The fix solved the issue for the route in the sample above but unfortunately I found another case that breaks with the patched code : 
In the same area if I try to route frome Start1=(43.61616, 6.97239) to End = (43.62246, 6.97482) no route is found for car profile with this SpeedTable : 
```
    map["highway_motorway"]=130.0;
    map["highway_motorway_trunk"]=100.0;
    map["highway_motorway_primary"]=70.0;
    map["highway_motorway_link"]=60.0;
    map["highway_motorway_junction"]=60.0;
    map["highway_trunk"]=100.0;
    map["highway_trunk_link"]=60.0;
    map["highway_primary"]=70.0;
    map["highway_primary_link"]=60.0;
    map["highway_secondary"]=60.0;
    map["highway_secondary_link"]=50.0;
    map["highway_tertiary"]=55.0;
    map["highway_tertiary_link"]=45.0;
    map["highway_unclassified"]=50.0;
    map["highway_road"]=50.0;
    map["highway_residential"]=40.0;
    map["highway_roundabout"]=40.0;
    map["highway_living_street"]=10.0;
    map["highway_service"]=10.0;
    map["highway_residential_area"]=10.0;
    map["highway_service_area"]=10.0;
```

But if I use Start2=(43.61606, 6.97255) which is just a few meters away the route is found : 

![IMG_0355](https://user-images.githubusercontent.com/452704/86511215-2b584b80-bdf7-11ea-8c70-d7007b66e443.PNG)

**Comment by Karry** [comment]
It is again problem with cost computation and cost limit. Cost limit for this start and destination is computed to 11:41 (time), but route cost with junction penalties is estimated to 12:24 (you can see it when override limit to infinity). Google maps are estimating route cost to 5 minutes and mapy.cz to 2 minutes... 

So, junction penalties are possibly too aggressive or our cost limit is too low. I will take a look on it and do some experiments.

**Comment by Karry** [comment]
With junction penalty limit (10 seconds) https://github.com/Framstag/libosmscout/pull/890 route price is 05:55. It is more realistic.

**Comment by Framstag** [comment]
I merged the fix of Lukas. @vyskocil please give feedback if it works now or if you still see strange effects.

IMHO this just shows that we do need automatic tests that o some simple test regarding routing calculation. The question is, is it enough to just define some simple abstract paths/networks (possibly extending the test DSL) that provoke corner cases or do we need to test against more complex real scenarios, which force us to work with real databases like Lukas already did?

If we need both, what is more important?

**Comment by vyskocil** [comment]
It is ok with the tests I did so far, thanks for the quick solution !
I have to explain why I lowered the speed of service roads: in some case the router used some weird shortcuts trough commercial or residential area and I wanted to avoid this. Maybe this kind of road could be flagged as "destination only" ie the router could use them only at the start and the end of the itinerary ?

**Comment by Karry** [comment]
> Maybe this kind of road could be flagged as "destination only" ie the router could use them only at the start and the end of the itinerary ? 

This behaviour is used when some route has ["access=destination"](https://wiki.openstreetmap.org/wiki/Key:access) tag. But I am worry that it would lead to some weird routes or even no routes at all, when we will be using it for some types implicitly... Lowering allowed speed for residential streets is better IMO.

**Comment by Framstag** [comment]
destination only should only we set as attribute in OSM, if it is "ground truth", which means, that there is a sign at the road, that access is restricted to people with local interest. As such I aggree with @Karry that we should not trick the router by faking this.

We must find more general criteria that replicate the decision-process of an actual person and it "feeling" of "it's faster" or "better".

We can use penalty for this. @Karry did this recently by giving penalty if you have to turn. We can also take in to account traffic lights, number of lanes, state of the road etc...

**Comment by vyskocil** [comment]
The routing issue seems to be fixed now, in the future we might use some penalty to avoid that the routing algorithm  find weird shortcuts trough residential or commercial areas.
