### ISSUE TITLE
Enhancement: Remove unused GLUT

### ISSUE THREAD

**Issue by OgreTransporter** [Framstag/libosmscout#894]
GLUT has not been supported for 20 years but is still required in CMake for OpenGL. The remnants of GLUT should be removed from CMake as it is no longer used in the code. If GLUT is required again, it should be replaced with FreeGLUT (https://www.opengl.org/resources/libraries/glut/).

**Comment by Framstag** [comment]
Assigned bug to ticket author, since he already offered a patch :-)
