### ISSUE TITLE
Import routing data only

### ISSUE THREAD

**Issue by zedxxx** [Framstag/libosmscout#915]
I want to use only routing functionality in my application. Using Import tool I can convert small *.pbf files fast enough, but with large files (whole Europe, for example) it take ages.  So my question is: Is it possible to skip unnecessary steps (if any) in Import process ([one of this 27-28 steps](https://github.com/Framstag/libosmscout/blob/master/libosmscout-import/src/osmscout/import/Import.cpp#L154)) to speed up data importing?

**Comment by Karry** [comment]
Hi. 

You can remove some data types from `map.ost` to make import faster. You may removes almost all types that are marked with keyword `PATH` (some other types are required by code import code itself, but I don't know exact list). 

Another way howto speedup import is running just selected steps. On this diagram https://osmscout.karry.cz/europe/czech-republic-21-20200922-1128/stats.svg you may track which temporary files and steps are required for "RouteDataGenerator". But I think that you cannot skip something big...

**Comment by zedxxx** [comment]
Can you explain what is `map.ost` and how can I remove something from it? I use `*.osm.pbf` from here http://download.geofabrik.de/europe.html

**Comment by Karry** [comment]
During import, you have to provide `--typefile <somepath>/map.ost` argument to Import tool. That `map.ost ` file is paced in `stylesheets/map.ost` in repository. It is text file with definition of types that are extracted from OSM data file and used in database. When you are interested just for router feature, you don't need to import areas, nodes and even ways that are not used later for generating router data files...

Syntax of that file is described here: http://libosmscout.sourceforge.net/documentation/typedef/

**Comment by Framstag** [comment]
If you want to leave out steps, you can use -s <step> or -e <step> to limit the number of steps run. Note though, that for a correct database most steps have a dependency on earlier steps. This is the reason, why it is safer to keep all steps but reduce the list of imported data,

Note also that it is better, to set individual types to "IGNORE" instead of removing it. Since some objects could map to multiple types, removing some may result in wrong mapping to other types. IGNORE removes matching objects without importing them, prohibiting later matches,

**Comment by zedxxx** [comment]
Ok, I got it. I will try to edit the `map.ost` by adding IGNORE and report the results.

**Comment by zedxxx** [comment]
My stylesheet optimized for routing only: [route.ost](https://gist.github.com/zedxxx/11221e187fc971720530b63535b7b47a)

Import is ~3x faster with this file.

**Comment by zedxxx** [comment]
Also, steps 18-21/22 can be safety skipped. If you need street names for your rote, than don't skip step 22 (`location.idx` generation).

**Comment by Framstag** [comment]
I'm glad to hear things are working out for you. Note that there a number of optimizations options for import and at runtime. If you have further questions, just ask...!
