### ISSUE TITLE
The new CMake files build static libs instead of frameworks on iOS

### ISSUE THREAD

**Issue by vyskocil** [Framstag/libosmscout#921]
I just upgraded to the latest code and compiled it to target iOS using : 

```build.ios % ~/Bin/cmake -DCMAKE_TOOLCHAIN_FILE=../cmake/iOS.cmake -DMARISA_INCLUDE_DIRS=~/Dev/marisa/lib -DPKG_CONFIG_EXECUTABLE=/usr/local/bin/pkg-config  ..```

Before that I still had to add ```set(MARISA_FOUND 1)``` in ```libosmscout/CMakeLists.txt``` because autodetect is not working for me.

Then I compiled it and found that the generated libs are now static archive instead of the usual frameworks : 

```build.ios % ls -al ./libosmscout/       
total 500384
drwxr-xr-x   7 vyskocil  staff        224 Sep 24 23:58 .
drwxr-xr-x  22 vyskocil  staff        704 Sep 24 23:54 ..
drwxr-xr-x   5 vyskocil  staff        160 Sep 24 23:54 CMakeFiles
-rw-r--r--   1 vyskocil  staff     154082 Sep 24 23:54 Makefile
-rw-r--r--   1 vyskocil  staff       2130 Sep 24 23:54 cmake_install.cmake
drwxr-xr-x   3 vyskocil  staff         96 Sep 24 23:54 include
-rw-r--r--   1 vyskocil  staff  256033328 Sep 24 23:58 libosmscout.a
```

Is this intended ? Did I missed a new option to get the usual frameworks ?

**Comment by vyskocil** [comment]
I also checked MacOS build and it this case the generated libs are dynamic libs instead of frameworks : 

``` build % ls -al libosmscout 
total 5584
drwxr-xr-x   8 vyskocil  staff      256 Sep 25 00:00 .
drwxr-xr-x  27 vyskocil  staff      864 Sep 24 23:57 ..
drwxr-xr-x   5 vyskocil  staff      160 Sep 24 23:57 CMakeFiles
-rw-r--r--   1 vyskocil  staff   153366 Sep 24 23:57 Makefile
-rw-r--r--   1 vyskocil  staff     2410 Sep 24 23:57 cmake_install.cmake
drwxr-xr-x   3 vyskocil  staff       96 Sep 24 23:57 include
-rwxr-xr-x   1 vyskocil  staff  2699000 Sep 25 00:00 libosmscout.0.1.0.dylib
lrwxr-xr-x   1 vyskocil  staff       23 Sep 25 00:00 libosmscout.dylib -> libosmscout.0.1.0.dylib```

**Comment by OgreTransporter** [comment]
I am very sorry about that. I made a mistake. I have prefixed all options (exception: `BUILD_SHARED_LIBS`) with `OSMSCOUT_`, so that you can easily build libosmscout as a subproject in your own projects. The variable for the frameworks is now called `OSMSCOUT_BUILD_FRAMEWORKS` and not `BUILD_FRAMEWORKS`. Unfortunately I forgot to rename it in some files. Patch: https://github.com/Framstag/libosmscout/pull/917/commits/d50ec22d4f48f0e69a0eac83782ccedb851783ff

**Comment by vyskocil** [comment]
The patch did the works, thank you !
