### ISSUE TITLE
Use custom cmake repository for Ubuntu bionic based CI builds

### ISSUE THREAD

**Issue by Framstag** [Framstag/libosmscout#951]
See https://apt.kitware.com/

Having an up-to-date cmake allows us to use UNITY_BUILDs and common command-line handling over all cmake builds.

Unity builds should speed up CI builds (especially Appveyor is currently by far the slowest since it serializes builds).

**Comment by OgreTransporter** [comment]
What about launchpad?

See https://help.launchpad.net/Packaging

**Comment by Framstag** [comment]
I personally do not see a need for packages. I have no problem with integrating another build system, but there should be some concrete advantage by doing so. I started using GitHub Actions simply because  build before took to long thus distribution the load helped.

Using a more current cmake version under Appveyor would allows us to use the unity build support in more recent version, this making the build simply faster.

**Comment by OgreTransporter** [comment]
According to https://www.appveyor.com/docs/linux-images-software/ CMake 3.17.2 is used everywhere under Linux. [UNITY_BUILD](https://cmake.org/cmake/help/v3.16/prop_tgt/UNITY_BUILD.html) exists since CMake 3.16.

To build packages there should be some kind of version numbering. In CMake I have already set a version number (currently 1.1.1).
https://github.com/Framstag/libosmscout/blob/fa8627141f2ceeba83d011f23583a018450a29ef/CMakeLists.txt#L3

I would create a vcpkg package. On my Jenkins I build nuget packages for Visual Studio.

**Comment by Framstag** [comment]
I set the project version to 1.1.1 in the meson build file, too.

**Comment by OgreTransporter** [comment]
https://github.com/microsoft/vcpkg/pull/14485

**Comment by OgreTransporter** [comment]
libosmscout can now be built and installed with vcpkg.

**Comment by Framstag** [comment]
@OgreTransporter I'm sure that I initially activated Unity builds for all platform to reduce build time (and some small improvement in project include structure s tested by a unity build) and had to remove it again on some because it was not correctly detected.

It is possible that the cause was different than I assumed. Perhaps we can simply dump the version of cmake from the build file (so we do not call cmake --version in all builds) to clarify this? This might help in other future cases, too?

Thanks for the vcpkg support!

Currently we do not do "real" releases that automatically increase the build version in the build files. This would definitely a nice thing to do, together with release notes based on patch and issue names.

**Comment by Framstag** [comment]
I'll close this. @Karry has updated the appveyor ubuntu version, I did the same for GitHub actions. So we should now have recent images everywhere. BY moving OS X builds to github build times should have been reduced again, too.

It would still nice to have cmake dump its version on configure/build but it is "nice to have" not "urgent".
