### ISSUE TITLE
DirectX character encoding

### ISSUE THREAD

**Issue by OgreTransporter** [Framstag/libosmscout#962]
The DirectX renderer ist not working with non-ascii characters. It should be possible to fix, because GDI+ is working ;-)

**Comment by ghpl210312** [comment]
I had a quick look into the DirectX-renderer and I changed the lines 130 to 140 in MapPainterDirectX.cpp as follows:

	std::wstring text2 = UTF8StringToWString(text);
	double horizontalOffset = 0;
	//for (size_t ch = 0; ch < text.length(); ch++) {
	for (size_t ch = 0; ch < text2.length(); ch++) {
		result.emplace_back();

#ifdef MBUC
		//std::wstring sample = s2w(text.substr(ch,1));
		std::wstring sample = text2.substr(ch,1);

That did the trick for me.

**Comment by Karry** [comment]
nice :-) may you send a merge request please?

**Comment by ghpl210312** [comment]
Hi,
I'm completely new to github and despite of reading various READMEs I am totally lost.
I have checked out the project with SVN. Do I have to create a branch from the trunk, apply the changes to it and commit?
Sorry.

**Comment by Karry** [comment]
Ok then, I prepared merge request. But I have no Windows machine with setup development environment. Can you review it and test it please?

Thank you!

**Comment by ghpl210312** [comment]
Sure, I will do.
Thank you.
