### ISSUE TITLE
Missing documentation for some map.ost keyword

### ISSUE THREAD

**Issue by vyskocil** [Framstag/libosmscout#963]
I'm trying to catch up on new features introduced recently like lanes, routes,... but documentation is missing about some of them at http://libosmscout.sourceforge.net/documentation/typedef/ or in the sample map.ost.
The missing keyword documentation is about : 
LANES[ ]
DESC
Sideway

older keyword GROUP is briefly mentioned in the doc but not in the provided map.ost file.

**Comment by Framstag** [comment]
I have added some documentation for LANES, DESC and GROUP. I did not find SIDEWAY but only sidecar as a style sheet option, see http://libosmscout.sourceforge.net/documentation/stylesheet/

Thanks for hinting that documentation is missing.

Please close issue if new documentation is OK for you.

**Comment by Framstag** [comment]
Closing it, please reopen if something is still missing.
