### ISSUE TITLE
MSys/MinGW tests fail

### ISSUE THREAD

**Issue by Framstag** [Framstag/libosmscout#990]
I have activated the tests for MinGW/MSys build on GitHub Actions. Most of the tests fail with exception for the CMake based build, while under meson all triggered tests succeed.

**Comment by Karry** [comment]
By fast google query, exit code 0xC0000135 means STATUS_DLL_NOT_FOUND... Some tests that are not loading libosmscout (EncodeNumber, BitsAndBytesNeeded...) were successful. But I have no idea howto fix it. Is there some equivalent of rpath?

**Comment by Framstag** [comment]
Seems to be a path problem:

```
Tim Teulings@Kiste MINGW64 /c/projects/libosmscout/build/Tests
$ echo $PATH
/mingw64/bin:/usr/local/bin:/usr/bin:/bin:/c/Windows/System32:/c/Windows:/c/Windows/System32/Wbem:/c/Windows/System32/WindowsPowerShell/v1.0/:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl

Tim Teulings@Kiste MINGW64 /c/projects/libosmscout/build/Tests
$ ./AccessParse.exe
C:/projects/libosmscout/build/Tests/AccessParse.exe: error while loading shared libraries: libstdc++-6.dll: cannot open shared object file: No such file or directory

Tim Teulings@Kiste MINGW64 /c/projects/libosmscout/build/Tests
$ export PATH=$PATH:/c/projects/libosmscout/debug/libosmscout

Tim Teulings@Kiste MINGW64 /c/projects/libosmscout/build/Tests
$ ./AccessParse.exe
===============================================================================
All tests passed (5 assertions in 5 test cases)
```

**Comment by Framstag** [comment]
See https://stackoverflow.com/questions/59376924/ctest-cmake-mingw-executables-build-but-fail-to-run-because-fresh-dll-is-n for some possible solutions.

**Comment by Framstag** [comment]
I do not like to copy dlls around or let tests point to the DLL directory as working directory. In a multi-library project this will likely not work in the long run.

Seems like this reduces it to: https://cmake.org/pipermail/cmake/2015-November/061978.html or setting the path manually from the GitHub actions build description.

I thunk I prefer the second option since it would be only a few entries but would work for all tests in return.

**Comment by Framstag** [comment]
Fixed by setting PATH as part of the actual ctest call, currently fixing resulting test failure. Closing issue.
